/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 广场浏览
         * @description 返回**黑盒安全**的展示信息，绝不包含 persona、编排图等内部定义。
         */
        get: operations["browseMarketplace"];
        put?: never;
        /**
         * 发布资源到广场
         * @description 发布前做**递归依赖闭包校验**：被发布资源传递依赖的每一层
         *     （Bundle → Agent → MCP/Skill/Tool）都必须已发布，任一层存在
         *     未发布的私有资源即返回 422 + 错误码 70001。
         *
         *     校验按精确版本匹配——Bundle 引用的是 Agent 的具体版本，
         *     必须是「该版本」已发布，不是「该 Agent 有任意版本发过」。
         *
         *     存在多个未发布依赖时一次性全部返回，`details` 给出完整依赖路径。
         *     循环依赖返回 70008。
         */
        post: operations["publishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        /**
         * 广场资源详情
         * @description 黑盒资源仅返回 `display_meta` 与 `constraints_summary`。
         *     **`constraints_summary` 是黑盒规则的必要例外**——不暴露 persona 和
         *     编排图，但必须暴露执行约束，否则订阅者无法预估 Token 成本。
         */
        get: operations["getListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings/{ref}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 举报该资源
         * @description 提交后进入运营中心的管理员举报队列（GET /moderation/reports）。
         */
        post: operations["reportListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止分发
         * @description 停止分发后广场不再展示，但**不影响存量订阅者**（他们继续可用）。
         *
         *     若该资源正被其他**已发布**资源依赖，拒绝停止分发（70007）——
         *     否则上游资源的依赖闭包会断裂，订阅了上游的用户会突然跑不了。
         *     响应的 details 列出具体依赖方。
         */
        post: operations["unpublishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings/{id}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 订阅
         * @description 订阅关系绑定到**该 listing 的具体版本**（快照隔离）。
         *     作者后续发布新版本不影响本次订阅，订阅者需显式升级。
         *     订阅动作会把对应资源版本标记为不可变，防止作者事后修改。
         */
        post: operations["subscribeListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的订阅 */
        get: operations["listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 退订 */
        delete: operations["unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/subscriptions/{id}/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 升级订阅到新版本
         * @description 显式操作，不会自动发生。升级后旧版本的运行历史仍可查。
         */
        post: operations["upgradeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 资源列表 */
        get: operations["listResources"];
        put?: never;
        /** 注册资源 */
        post: operations["createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新资源（含启用/禁用） */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/resources/{id}/delete-check": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * 删除前占用检查
         * @description 返回该资源被哪些 Agent 引用，供前端在确认弹窗中展示影响范围
         */
        get: operations["checkResourceDeletable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/kb/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 一个 knowledge_base 类型资源的 id；其他类型返回 404 */
                id: string;
            };
            cookie?: never;
        };
        /** 已摄入的文档列表（按 source_ref 聚合，不是按 chunk） */
        get: operations["listKnowledgeBaseDocuments"];
        put?: never;
        /**
         * 摄入一份文档（分块、向量化、存储）
         * @description 用相同 source_ref 重新摄入即为更新——旧的 chunk 会先被整体替换
         */
        post: operations["ingestKnowledgeBaseDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/kb/documents/{source_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除一份文档的全部 chunk */
        delete: operations["deleteKnowledgeBaseDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/kb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 检索预览——手动验证摄入的内容能不能被合理召回 */
        post: operations["searchKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent 列表（每个 ref 返回最新启用版本） */
        get: operations["listAgents"];
        put?: never;
        /**
         * 创建 Agent（新建或新增版本）
         * @description 请求体中的 `definition` 会用 Agent DSL 的 JSON Schema 严格校验。
         *     校验失败返回 400 + 错误码 40001，`details` 中给出具体字段路径。
         */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除 Agent
         * @description 删除前校验两类占用：
         *     1. 该 Agent 的任一版本已被发布且有存量订阅者 → 拒绝（快照隔离要求），只能停止分发
         *     2. 被其他 Bundle 引用中 → 拒绝，并在 details 列出具体 Bundle
         *     删除不影响历史运行记录的可查性。
         */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{ref}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某个 Agent 的全部版本 */
        get: operations["listAgentVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bundle 列表 */
        get: operations["listBundles"];
        put?: never;
        /**
         * 创建 Bundle
         * @description 除 JSON Schema 校验外，还会做**编排图静态校验**：
         *     entry 节点存在、边引用的节点均已声明、不存在因自环边被计入 join
         *     前置条件而永远无法触发的死锁节点。图校验失败返回 422 + 错误码 40003。
         */
        post: operations["createBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundles/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除 Bundle
         * @description 已被订阅的版本不可删除，只能停止分发。删除不影响历史运行记录。
         */
        delete: operations["deleteBundle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行列表 */
        get: operations["listRuns"];
        put?: never;
        /**
         * 启动一次 Bundle 运行
         * @description 异步启动，立即返回 run_id。前端随后连接 `/runs/{id}/stream` 消费事件流。
         *     强烈建议携带 `Idempotency-Key`：一次运行可能消耗大量 Token，
         *     网络抖动导致的重复提交是真实的成本损失。
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 运行详情（含最新 shared_state） */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/stream": {
        parameters: {
            query?: {
                /** @description 断线续传游标，只推送 id 大于该值的事件 */
                after_id?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * 运行事件流（NDJSON，chunked）
         * @description **唯一不使用统一信封的接口**，因为是流式响应。
         *
         *     - `Content-Type: application/x-ndjson`，每行一个独立 JSON 事件对象
         *     - 建连后先补发历史事件（可用 `after_id` 续传），再进入增量推送
         *     - 服务端在 `bundle.finished` / `bundle.failed` 后主动关闭连接
         *     - 鉴权失败等**建连阶段**的错误仍用常规信封 + 对应 HTTP 状态码返回；
         *       连接建立后发生的错误以一条 `type: "stream.error"` 事件推送后关闭
         *     - 响应头必须带 `X-Accel-Buffering: no`，避免 nginx 缓冲导致伪流式
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止运行
         * @description 用户主动终止一次运行，避免继续消耗 Token。停止在 5 秒内生效，
         *     不等待当前 Agent 执行完。已产生的产出与事件完整保留，
         *     **已消耗的 Token 照常计费**（无法退回）。
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/gate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * human gate 审批
         * @description **必须做审批人角色的二次校验**——具备 Bundle 查看权限不等于具备审批权限，
         *     这是安全边界，不能只在网关层做身份校验。
         */
        post: operations["resolveGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 我的用量与成本
         * @description 当前用户自己的消耗，与运营中心的管理员全局报表区分。
         *     黑盒资源的运行消耗计入**发起运行的人**（即订阅者）。
         */
        get: operations["getMyUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 我的审计日志
         * @description 当前用户自己发起的操作（V1 仅 human gate 审批/驳回）。
         *     Append-only，数据库触发器拒绝 UPDATE/DELETE（迁移 0010）。
         */
        get: operations["listMyAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 待处理举报队列（仅管理员） */
        get: operations["listPendingReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/reports/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 处理举报（仅管理员）
         * @description `action: takedown` 会禁用被举报资源本身（Agent/Bundle/Skill/MCP 的
         *     `status`），使其立即无法通过校验被新的运行引用（30002）——这是存量
         *     订阅者失去访问权限的方式；同时把该 listing 标记为管理员下架，
         *     广场不再展示。`action: dismiss` 仅关闭举报，不影响资源。
         */
        post: operations["resolveReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按模态浏览的模型目录（展示数据，不是绑定契约）
         * @description Agent 的 model.name 仍然是自由文本；这个目录只是给用户挑选时看的参考
         */
        get: operations["listModelCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已接入的 Provider 列表（不返回凭证） */
        get: operations["listModelProviders"];
        put?: never;
        /** 接入 Provider */
        post: operations["createModelProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-catalog/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 目录 Provider 列表（含禁用），管理员 */
        get: operations["listCatalogProviders"];
        put?: never;
        /** 新增目录 Provider，管理员 */
        post: operations["createCatalogProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-catalog/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除 Provider（级联删除其下所有 Model），管理员 */
        delete: operations["deleteCatalogProvider"];
        options?: never;
        head?: never;
        /** 启用/禁用 Provider，管理员 */
        patch: operations["updateCatalogProviderStatus"];
        trace?: never;
    };
    "/model-catalog/providers/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某 Provider 下的 Model 列表（含禁用），管理员 */
        get: operations["listCatalogModels"];
        put?: never;
        /** 在 Provider 下新增 Model（如 deepseek-v3），管理员 */
        post: operations["createCatalogModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-catalog/providers/{id}/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除 Model，管理员 */
        delete: operations["deleteCatalogModel"];
        options?: never;
        head?: never;
        /** 启用/禁用 Model，管理员 */
        patch: operations["updateCatalogModelStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /**
             * @description 0 为成功；非 0 为五位业务错误码
             * @example 0
             */
            code: number;
            /** @example ok */
            message: string;
            /** @description 业务数据，无返回内容时为 null */
            data?: unknown;
            /**
             * @description 全链路追踪 ID，等同 OTel trace_id
             * @example req-a1b2c3d4
             */
            request_id: string;
            /** @description 字段级错误，表单场景使用 */
            details?: {
                field: string;
                reason: string;
            }[];
        };
        /**
         * @description 1 启用 / 2 停用
         * @enum {integer}
         */
        Status: 1 | 2;
        /** @enum {string} */
        ResourceType: "tool" | "skill" | "mcp" | "knowledge_base" | "memory";
        /** @enum {string} */
        ProviderName: "anthropic" | "openai" | "google" | "deepseek" | "qwen" | "custom";
        /** @enum {string} */
        RunStatus: "running" | "finished" | "failed";
        Resource: {
            id: string;
            type: components["schemas"]["ResourceType"];
            ref: string;
            display_name?: string;
            config?: {
                [key: string]: unknown;
            };
            status: components["schemas"]["Status"];
            /**
             * @description MCP Server 等外部资源的健康状态
             * @enum {string}
             */
            health?: "unknown" | "healthy" | "unhealthy";
            /** Format: date-time */
            created_at: string;
        };
        AgentDefinition: {
            /** @example architect */
            agent: string;
            /** @example 系统架构师 */
            role: string;
            version: string;
            model: {
                provider: components["schemas"]["ProviderName"];
                /** @example claude-sonnet-5 */
                name: string;
                /** @description 主模型不可用时按顺序降级，格式 provider/name */
                fallback?: string[];
                temperature?: number;
            };
            /** @description 角色设定，支持模板变量如 {{shared_state.requirements}} */
            persona: string;
            capabilities: {
                tools?: string[];
                skills?: string[];
                /** @description ADK 自带工具，不经过资源中心登记 */
                builtin_tools?: ("google_search" | "load_memory" | "preload_memory" | "load_artifacts" | "exit_loop")[];
                hooks?: {
                    before_tool_call?: string[];
                    after_tool_call?: string[];
                    before_response?: string[];
                    after_response?: string[];
                    on_error?: string[];
                };
            };
            constraints: {
                max_tokens_per_turn?: number;
                max_tool_calls?: number;
                max_turns?: number;
                timeout_seconds?: number;
                forbidden_actions?: string[];
                /** @description 该 Agent 产出必须满足的 JSON Schema 引用 */
                output_schema?: string;
            };
            handoff?: {
                accepts_input_from?: string[];
                produces_output_to?: string[];
                requires_review?: boolean;
            };
        };
        Agent: {
            id: string;
            agent_ref: string;
            version: string;
            definition: components["schemas"]["AgentDefinition"];
            status: components["schemas"]["Status"];
            /** Format: date-time */
            created_at: string;
        };
        BundleDefinition: {
            bundle: string;
            version: string;
            description?: string;
            agents: {
                ref: string;
                /** @description 同一 Agent 在一个 Bundle 中多次出现时用于区分 */
                alias?: string;
                version?: string;
            }[];
            orchestration: {
                /** @enum {string} */
                mode: "pipeline" | "graph";
                entry: string;
                edges: {
                    from: string;
                    /** @description 单个目标、多个目标（并行 fan-out），或字面量 END */
                    to: string | string[];
                    /** @enum {string} */
                    mode?: "sequential" | "parallel";
                    /** @enum {string} */
                    join?: "wait_all" | "wait_any";
                    /**
                     * @description 基于 shared_state 的路由表达式（expr-lang 语法）
                     * @example shared_state.tests_passed == true
                     */
                    condition?: string;
                }[];
                human_gates?: {
                    after: string;
                    timeout_seconds?: number;
                    /** @enum {string} */
                    on_timeout?: "auto_approve" | "auto_reject" | "abort";
                    /** @description 有资格审批的角色，为空则回退到团队默认审批角色 */
                    approver_roles?: string[];
                }[];
            };
            limits?: {
                max_total_tokens?: number;
                max_wall_clock_seconds?: number;
                max_cost_usd?: number;
            };
        };
        Bundle: {
            id: string;
            bundle_ref: string;
            version: string;
            definition: components["schemas"]["BundleDefinition"];
            status: components["schemas"]["Status"];
            /** Format: date-time */
            created_at: string;
        };
        RunSummary: {
            /** @example run-9e67931d5c38024e */
            run_id: string;
            bundle_ref: string;
            bundle_version?: string;
            status: components["schemas"]["RunStatus"];
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        RunDetail: components["schemas"]["RunSummary"] & {
            /**
             * @description 跨 Agent 共享的结构化上下文。当 `is_owner` 为 false（订阅者
             *     查看黑盒资源）时，仅包含该资源 display_meta.io_description.outputs
             *     声明的字段。
             */
            shared_state: {
                [key: string]: unknown;
            };
            /**
             * @description 当前请求者是否为该运行所用 Bundle 的作者本人。为 false 时前端
             *     进入黑盒降级展示：执行图只显示占位节点，共享状态与事件流已由
             *     后端过滤为声明的输出子集。
             */
            is_owner: boolean;
            /** @description 本次运行的资源消耗，用于 Chat 页右侧栏展示 */
            usage?: {
                total_tokens?: number;
                cost_usd?: number;
                duration_seconds?: number;
            };
        };
        /**
         * @description 事件流中的单条事件。前端 Chat 界面据此驱动：
         *     `node.thinking` → 打字机效果；`node.tool_call.*` → 气泡内工具调用状态条；
         *     `human_gate.waiting` → 内联审批卡片。
         */
        RunEvent: {
            /**
             * Format: int64
             * @description 自增主键，作为断线续传游标
             */
            id: number;
            /** @enum {string} */
            type: "bundle.started" | "bundle.finished" | "bundle.failed" | "node.queued" | "node.started" | "node.thinking" | "node.tool_call.started" | "node.tool_call.finished" | "node.finished" | "node.failed" | "human_gate.waiting" | "human_gate.resolved" | "shared_state.updated" | "stream.error";
            run_id: string;
            /** @description 事件关联的节点（bundle 级事件为空） */
            node?: string;
            /** Format: date-time */
            timestamp: string;
            /** @description 因事件类型而异 */
            payload?: unknown;
        };
        AuthResult: {
            /** @description JWT，有效期 2h */
            access_token: string;
            /** @description 有效期 7d */
            refresh_token: string;
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /**
             * @description 是否拥有运营中心的管理员权限（举报处理）。V1 无角色系统，仅此一个布尔位。
             * @default false
             */
            is_admin: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        ListingResourceType: "agent" | "bundle" | "skill" | "mcp";
        /**
         * @description **可公开展示**的元信息，与资源的 definition 分离存储。
         *     黑盒发布下，订阅者只能看到本对象的内容。
         */
        ListingDisplayMeta: {
            /** @example 全栈应用生成器 */
            display_name: string;
            description: string;
            /** @description 使用说明（怎么用、注意什么） */
            usage?: string;
            /** @description 输入输出说明；黑盒运行时，共享状态面板只展示此处声明的输出字段 */
            io_description?: {
                input?: string;
                /**
                 * @example [
                 *       "requirements",
                 *       "architecture_doc",
                 *       "ui_spec",
                 *       "code_diff"
                 *     ]
                 */
                outputs?: string[];
            };
        };
        /**
         * @description 执行约束摘要。黑盒规则的**必要例外**：不暴露内部定义，
         *     但必须让订阅者能预估运行成本。
         */
        ConstraintsSummary: {
            max_tool_calls?: number;
            timeout_seconds?: number;
            /** @example 30000~60000 */
            estimated_tokens_range?: string;
        };
        ListingSummary: {
            id: string;
            /** @description 广场内的稳定标识，跨版本不变 */
            listing_ref: string;
            resource_type: components["schemas"]["ListingResourceType"];
            version: string;
            /**
             * @description V1 仅支持 blackbox；public 模式见 PRD P2-4
             * @enum {string}
             */
            visibility?: "blackbox";
            display_meta: components["schemas"]["ListingDisplayMeta"];
            author: components["schemas"]["User"];
            subscriber_count: number;
            run_count?: number;
            /** @description 当前用户是否已订阅（用于广场卡片显示"进入使用"） */
            subscribed?: boolean;
            /** Format: date-time */
            published_at?: string;
        };
        ListingDetail: components["schemas"]["ListingSummary"] & {
            constraints_summary?: components["schemas"]["ConstraintsSummary"];
            /** @description 版本历史，只含作者手写的 changelog，不含 diff */
            versions?: {
                version?: string;
                changelog?: string;
                /** Format: date-time */
                published_at?: string;
            }[];
        };
        Subscription: {
            id: string;
            listing: components["schemas"]["ListingSummary"];
            /** @description 订阅时绑定的版本（快照隔离），不随作者发新版而变 */
            subscribed_version: string;
            /** @description 订阅者可在自己空间内重命名 */
            local_alias?: string | null;
            /** @description 作者当前最新版本；与 subscribed_version 不同则前端提示"有新版本" */
            latest_version?: string | null;
            /** @description 最新版本的更新说明，供订阅者判断是否升级 */
            latest_changelog?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        UsageSummary: {
            /** @example 2026-08 */
            period: string;
            /** Format: int64 */
            total_tokens: number;
            total_cost_usd: number;
            run_count?: number;
            /** @description 按 bundle 或按天的分组明细 */
            breakdown: {
                /** @description bundle_ref 或日期 */
                key?: string;
                /** Format: int64 */
                tokens?: number;
                cost_usd?: number;
                run_count?: number;
            }[];
        };
        AuditLog: {
            id: string;
            /** @example human_gate.approved */
            action: string;
            /** @example human_gate */
            target_type: string;
            target_id: string;
            detail?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        Report: {
            id: string;
            listing_ref: string;
            reason: string;
            /** @description 被举报 listing 的存量订阅者数量，供下架确认弹窗展示影响范围 */
            subscriber_count?: number;
            /** @enum {string} */
            status: "pending" | "resolved";
            /** @enum {string|null} */
            resolution?: "dismiss" | "takedown" | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            resolved_at?: string | null;
        };
        ModelProvider: {
            id: string;
            provider: components["schemas"]["ProviderName"];
            base_url?: string;
            status: components["schemas"]["Status"];
            /** Format: date-time */
            created_at: string;
        };
        /** @description 一条模型广场展示行，来自系统配置 → 模型提供商里管理员登记的 Provider + Model 联合读取；provider 是该 Provider 的 key（自由文本），不是 ProviderName 那个 为已接入凭证准备的封闭枚举。 */
        ModelCatalogEntry: {
            /** @example deepseek */
            provider: string;
            /** @example DeepSeek */
            provider_display_name: string;
            /** @description URL 或 data: URI */
            provider_icon?: string;
            /** @example deepseek-v3 */
            model: string;
            display_name: string;
            description: string;
            modality: components["schemas"]["CatalogModality"];
            featured: boolean;
        };
        /**
         * @description 模型广场按此筛选的"模型类型"标签
         * @enum {string}
         */
        CatalogModality: "text" | "image" | "video" | "vision" | "embedding";
        /** @description 系统配置 → 模型提供商登记的一个 Provider（不是已接入的凭证） */
        CatalogProvider: {
            id: string;
            /** @example deepseek */
            key: string;
            /** @example DeepSeek */
            display_name: string;
            /** @description URL 或 data: URI */
            icon?: string;
            base_url?: string;
            status: components["schemas"]["Status"];
            /** Format: date-time */
            created_at: string;
        };
        CatalogModel: {
            id: string;
            provider_id: string;
            /** @example deepseek-v3 */
            model: string;
            display_name: string;
            description?: string;
            modality: components["schemas"]["CatalogModality"];
            featured: boolean;
            status: components["schemas"]["Status"];
            /** Format: date-time */
            created_at: string;
        };
        KnowledgeBaseDocument: {
            source_ref: string;
            chunk_count: number;
            /** Format: date-time */
            ingested_at: string;
        };
        KnowledgeBaseSearchResult: {
            source_ref: string;
            content: string;
            /** @description 1 - 余弦距离，越大越相关 */
            score: number;
        };
    };
    responses: {
        /** @description 请求参数格式错误或 Schema 校验失败 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description 未认证（20001 / 20002） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description 已认证但无权限（20003） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
    };
    parameters: {
        /** @description 默认 20，上限 100，超出按上限截断而非报错 */
        Limit: number;
        /** @description 游标分页令牌，来自上一页响应的 next_cursor */
        Cursor: string;
        /** @description 客户端生成的 UUID，24h 内相同 Key 重复请求直接返回首次结果 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    display_name: string;
                };
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AuthResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 邮箱已注册 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AuthResult"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    browseMarketplace: {
        parameters: {
            query?: {
                resource_type?: components["schemas"]["ListingResourceType"];
                /** @description 按名称/描述搜索 */
                q?: string;
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["ListingSummary"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    publishListing: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的 UUID，24h 内相同 Key 重复请求直接返回首次结果 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    resource_type: components["schemas"]["ListingResourceType"];
                    /** @description 作者空间内的资源标识 */
                    resource_ref: string;
                    /** @example 2.0 */
                    version: string;
                    display_meta: components["schemas"]["ListingDisplayMeta"];
                    /**
                     * @description 本版本的更新说明，由作者手写。**不提供自动 diff**——
                     *     diff 会泄露黑盒内容。
                     */
                    changelog?: string;
                };
            };
        };
        responses: {
            /** @description 发布成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ListingDetail"];
                    };
                };
            };
            /** @description 依赖完整性校验失败（70001） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ListingDetail"];
                    };
                };
            };
            /** @description listing 不存在或已下架（70002） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    reportListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 描述与实际功能严重不符 */
                    reason: string;
                };
            };
        };
        responses: {
            /** @description 已提交 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Report"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description listing 不存在（70002） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    unpublishListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已停止分发 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 被其他已发布资源依赖（70007） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    subscribeListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 订阅成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Subscription"];
                    };
                };
            };
            /** @description listing 不存在或已停止分发（70002） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 已订阅该版本（70004） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listSubscriptions: {
        parameters: {
            query?: {
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["Subscription"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 退订成功（历史运行记录仍可查） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    upgradeSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 2.0 */
                    target_version: string;
                };
            };
        };
        responses: {
            /** @description 升级成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Subscription"];
                    };
                };
            };
            /** @description 目标版本不存在（70002） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listResources: {
        parameters: {
            query?: {
                type?: components["schemas"]["ResourceType"];
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["Resource"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createResource: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的 UUID，24h 内相同 Key 重复请求直接返回首次结果 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type: components["schemas"]["ResourceType"];
                    /**
                     * @description Agent DSL 中引用该资源使用的 ID
                     * @example internal-search
                     */
                    ref: string;
                    display_name?: string;
                    /**
                     * @description 因资源类型而异的连接配置
                     * @example {
                     *       "endpoint": "https://mcp.internal/search",
                     *       "auth_type": "bearer"
                     *     }
                     */
                    config: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Resource"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description ref 重复（错误码 30003） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name?: string;
                    config?: {
                        [key: string]: unknown;
                    };
                    status?: components["schemas"]["Status"];
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Resource"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    checkResourceDeletable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            deletable?: boolean;
                            referenced_by?: {
                                type?: string;
                                ref?: string;
                                version?: string;
                            }[];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listKnowledgeBaseDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 一个 knowledge_base 类型资源的 id；其他类型返回 404 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["KnowledgeBaseDocument"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    ingestKnowledgeBaseDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 一个 knowledge_base 类型资源的 id；其他类型返回 404 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 文档标识，如文件名或标题 */
                    source_ref: string;
                    content: string;
                };
            };
        };
        responses: {
            /** @description 摄入成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            chunk_count?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description embedding 调用失败或维度不匹配 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    deleteKnowledgeBaseDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                source_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    searchKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    /** @default 5 */
                    top_k?: number;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["KnowledgeBaseSearchResult"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAgents: {
        parameters: {
            query?: {
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["Agent"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的 UUID，24h 内相同 Key 重复请求直接返回首次结果 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    definition: components["schemas"]["AgentDefinition"];
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Agent"];
                    };
                };
            };
            /** @description DSL 校验失败（40001）或引用了被禁用的资源（30002） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 存在占用无法删除（70005 已被订阅 / 40004 被引用） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listAgentVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Agent"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBundles: {
        parameters: {
            query?: {
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["Bundle"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createBundle: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的 UUID，24h 内相同 Key 重复请求直接返回首次结果 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    definition: components["schemas"]["BundleDefinition"];
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Bundle"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 图校验失败（40003） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    deleteBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 已被订阅无法删除（70005） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                bundle_ref?: string;
                status?: components["schemas"]["RunStatus"];
                /** @description 字段名前加 `-` 表示倒序 */
                sort?: string;
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["RunSummary"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的 UUID，24h 内相同 Key 重复请求直接返回首次结果 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example web-app-builder */
                    bundle_ref: string;
                    /**
                     * @description 省略则使用最新启用版本
                     * @example 1.0
                     */
                    bundle_version?: string;
                    /**
                     * @description 初始需求，写入 shared_state
                     * @example {
                     *       "requirements": "做一个待办事项 Web 应用"
                     *     }
                     */
                    input: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RunSummary"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            /** @description 引用资源被禁用（30002）/ Agent 版本不存在（40004）/ Provider 未配置（60001） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RunDetail"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: {
                /** @description 断线续传游标，只推送 id 大于该值的事件 */
                after_id?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件流 */
            200: {
                headers: {
                    "X-Accel-Buffering"?: "no";
                    "Cache-Control"?: "no-cache";
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["RunEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已发出停止指令 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            /** @description 运行已结束（50002） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    resolveGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example architect */
                    node: string;
                    approved: boolean;
                    /** @description 审批意见，写入审计日志 */
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description 处理成功（无响应体，不带信封） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 非指定审批角色（50004） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description gate 已被处理（50003）或 run 已结束（50002） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getMyUsage: {
        parameters: {
            query?: {
                period?: "day" | "week" | "month";
                group_by?: "bundle" | "day";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["UsageSummary"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyAuditLogs: {
        parameters: {
            query?: {
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["AuditLog"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPendingReports: {
        parameters: {
            query?: {
                /** @description 默认 20，上限 100，超出按上限截断而非报错 */
                limit?: components["parameters"]["Limit"];
                /** @description 游标分页令牌，来自上一页响应的 next_cursor */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            items: components["schemas"]["Report"][];
                            next_cursor?: string | null;
                            has_more: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 非管理员（20003） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    resolveReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action: "dismiss" | "takedown";
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Report"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 非管理员（20003） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 举报不存在（80001） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 该举报已处理（80002） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listModelCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ModelCatalogEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listModelProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ModelProvider"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createModelProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    provider: components["schemas"]["ProviderName"];
                    /** @description 加密存储，任何接口都不回显 */
                    api_key: string;
                    /** @description 自定义调用地址；provider 为 custom 时必填，其余 provider 缺省时使用官方地址 */
                    base_url?: string;
                };
            };
        };
        responses: {
            /** @description 接入成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ModelProvider"];
                    };
                };
            };
            /** @description 凭证无效（60002） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listCatalogProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogProvider"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createCatalogProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example deepseek */
                    key: string;
                    /** @example DeepSeek */
                    display_name: string;
                    /** @description URL 或 data: URI */
                    icon?: string;
                    base_url?: string;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogProvider"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description provider key 已存在（60007） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    deleteCatalogProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description provider 不存在（60005） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    updateCatalogProviderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["Status"];
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description provider 不存在（60005） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listCatalogModels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogModel"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createCatalogModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example deepseek-v3 */
                    model: string;
                    display_name: string;
                    description?: string;
                    modality: components["schemas"]["CatalogModality"];
                    featured?: boolean;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogModel"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description provider 不存在（60005） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description 该 provider 下已存在同名模型（60007） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    deleteCatalogModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateCatalogModelStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["Status"];
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
