// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: adk_session.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendADKSessionEvent = `-- name: AppendADKSessionEvent :exec
INSERT INTO adk_session_events (app_name, user_id, session_id, event_id, author, event)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendADKSessionEventParams struct {
	AppName   string `json:"app_name"`
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
	EventID   string `json:"event_id"`
	Author    string `json:"author"`
	Event     []byte `json:"event"`
}

func (q *Queries) AppendADKSessionEvent(ctx context.Context, arg AppendADKSessionEventParams) error {
	_, err := q.db.Exec(ctx, appendADKSessionEvent,
		arg.AppName,
		arg.UserID,
		arg.SessionID,
		arg.EventID,
		arg.Author,
		arg.Event,
	)
	return err
}

const deleteADKSession = `-- name: DeleteADKSession :exec
DELETE FROM adk_sessions WHERE app_name = $1 AND user_id = $2 AND session_id = $3
`

type DeleteADKSessionParams struct {
	AppName   string `json:"app_name"`
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) DeleteADKSession(ctx context.Context, arg DeleteADKSessionParams) error {
	_, err := q.db.Exec(ctx, deleteADKSession, arg.AppName, arg.UserID, arg.SessionID)
	return err
}

const getADKAppState = `-- name: GetADKAppState :one
SELECT state FROM adk_app_state WHERE app_name = $1
`

func (q *Queries) GetADKAppState(ctx context.Context, appName string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getADKAppState, appName)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const getADKSession = `-- name: GetADKSession :one
SELECT app_name, user_id, session_id, state, created_at, updated_at
FROM adk_sessions
WHERE app_name = $1 AND user_id = $2 AND session_id = $3
`

type GetADKSessionParams struct {
	AppName   string `json:"app_name"`
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetADKSession(ctx context.Context, arg GetADKSessionParams) (AdkSession, error) {
	row := q.db.QueryRow(ctx, getADKSession, arg.AppName, arg.UserID, arg.SessionID)
	var i AdkSession
	err := row.Scan(
		&i.AppName,
		&i.UserID,
		&i.SessionID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getADKUserState = `-- name: GetADKUserState :one
SELECT state FROM adk_user_state WHERE app_name = $1 AND user_id = $2
`

type GetADKUserStateParams struct {
	AppName string `json:"app_name"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetADKUserState(ctx context.Context, arg GetADKUserStateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getADKUserState, arg.AppName, arg.UserID)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const listADKSessionEvents = `-- name: ListADKSessionEvents :many
SELECT seq, event_id, author, event, created_at
FROM adk_session_events
WHERE app_name = $1 AND user_id = $2 AND session_id = $3
ORDER BY seq ASC
`

type ListADKSessionEventsParams struct {
	AppName   string `json:"app_name"`
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
}

type ListADKSessionEventsRow struct {
	Seq       int64              `json:"seq"`
	EventID   string             `json:"event_id"`
	Author    string             `json:"author"`
	Event     []byte             `json:"event"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListADKSessionEvents(ctx context.Context, arg ListADKSessionEventsParams) ([]ListADKSessionEventsRow, error) {
	rows, err := q.db.Query(ctx, listADKSessionEvents, arg.AppName, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListADKSessionEventsRow{}
	for rows.Next() {
		var i ListADKSessionEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.EventID,
			&i.Author,
			&i.Event,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listADKSessions = `-- name: ListADKSessions :many
SELECT app_name, user_id, session_id, state, created_at, updated_at
FROM adk_sessions
WHERE app_name = $1 AND user_id = $2
ORDER BY updated_at DESC
`

type ListADKSessionsParams struct {
	AppName string `json:"app_name"`
	UserID  string `json:"user_id"`
}

// 只列会话本身，不带事件：ADK 的 List 语义就是"会话清单"，把每段对话的
// 全部事件都拉出来会让一次列表变成全表扫描。
func (q *Queries) ListADKSessions(ctx context.Context, arg ListADKSessionsParams) ([]AdkSession, error) {
	rows, err := q.db.Query(ctx, listADKSessions, arg.AppName, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdkSession{}
	for rows.Next() {
		var i AdkSession
		if err := rows.Scan(
			&i.AppName,
			&i.UserID,
			&i.SessionID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeADKAppState = `-- name: MergeADKAppState :exec
INSERT INTO adk_app_state (app_name, state) VALUES ($1, $2)
ON CONFLICT (app_name) DO UPDATE
SET state = adk_app_state.state || EXCLUDED.state, updated_at = now()
`

type MergeADKAppStateParams struct {
	AppName string `json:"app_name"`
	State   []byte `json:"state"`
}

// || 是 jsonb 的浅合并，右侧覆盖左侧——正好是 ADK state delta 的语义。
func (q *Queries) MergeADKAppState(ctx context.Context, arg MergeADKAppStateParams) error {
	_, err := q.db.Exec(ctx, mergeADKAppState, arg.AppName, arg.State)
	return err
}

const mergeADKUserState = `-- name: MergeADKUserState :exec
INSERT INTO adk_user_state (app_name, user_id, state) VALUES ($1, $2, $3)
ON CONFLICT (app_name, user_id) DO UPDATE
SET state = adk_user_state.state || EXCLUDED.state, updated_at = now()
`

type MergeADKUserStateParams struct {
	AppName string `json:"app_name"`
	UserID  string `json:"user_id"`
	State   []byte `json:"state"`
}

func (q *Queries) MergeADKUserState(ctx context.Context, arg MergeADKUserStateParams) error {
	_, err := q.db.Exec(ctx, mergeADKUserState, arg.AppName, arg.UserID, arg.State)
	return err
}

const setADKSessionState = `-- name: SetADKSessionState :exec
UPDATE adk_sessions SET state = $4, updated_at = now()
WHERE app_name = $1 AND user_id = $2 AND session_id = $3
`

type SetADKSessionStateParams struct {
	AppName   string `json:"app_name"`
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
	State     []byte `json:"state"`
}

func (q *Queries) SetADKSessionState(ctx context.Context, arg SetADKSessionStateParams) error {
	_, err := q.db.Exec(ctx, setADKSessionState,
		arg.AppName,
		arg.UserID,
		arg.SessionID,
		arg.State,
	)
	return err
}

const upsertADKSession = `-- name: UpsertADKSession :one

INSERT INTO adk_sessions (app_name, user_id, session_id, state)
VALUES ($1, $2, $3, $4)
ON CONFLICT (app_name, user_id, session_id) DO UPDATE SET app_name = EXCLUDED.app_name
RETURNING app_name, user_id, session_id, state, created_at, updated_at
`

type UpsertADKSessionParams struct {
	AppName   string `json:"app_name"`
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
	State     []byte `json:"state"`
}

// ADK 会话持久化。见 migrations/0030_agent_sessions.up.sql 的表注释。
// 建会话。已存在就原样返回——ADK 的 AutoCreateSession 每轮都会尝试建一
// 次，冲突是常态而不是错误。
func (q *Queries) UpsertADKSession(ctx context.Context, arg UpsertADKSessionParams) (AdkSession, error) {
	row := q.db.QueryRow(ctx, upsertADKSession,
		arg.AppName,
		arg.UserID,
		arg.SessionID,
		arg.State,
	)
	var i AdkSession
	err := row.Scan(
		&i.AppName,
		&i.UserID,
		&i.SessionID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
