// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one

INSERT INTO agents (owner_user_id, agent_ref, version, definition, display_meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at
`

type CreateAgentParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
	Definition  []byte `json:"definition"`
	DisplayMeta []byte `json:"display_meta"`
}

// Owner-view and subscriber-view queries are kept physically separate so the
// subscriber path can never accidentally SELECT `definition` (see
// docs/架构设计文档_AI-Agent平台_V1.md 五、"黑盒发布的实现要点").
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.OwnerUserID,
		arg.AgentRef,
		arg.Version,
		arg.Definition,
		arg.DisplayMeta,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AgentRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgentDisplayForSubscriber = `-- name: GetAgentDisplayForSubscriber :one
SELECT id, owner_user_id, agent_ref, version, display_meta, status, created_at
FROM agents
WHERE id = $1
`

type GetAgentDisplayForSubscriberRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	AgentRef    string             `json:"agent_ref"`
	Version     string             `json:"version"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAgentDisplayForSubscriber(ctx context.Context, id int64) (GetAgentDisplayForSubscriberRow, error) {
	row := q.db.QueryRow(ctx, getAgentDisplayForSubscriber, id)
	var i GetAgentDisplayForSubscriberRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AgentRef,
		&i.Version,
		&i.DisplayMeta,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentForOwner = `-- name: GetAgentForOwner :one
SELECT id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at FROM agents
WHERE owner_user_id = $1 AND agent_ref = $2 AND version = $3
`

type GetAgentForOwnerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
}

func (q *Queries) GetAgentForOwner(ctx context.Context, arg GetAgentForOwnerParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentForOwner, arg.OwnerUserID, arg.AgentRef, arg.Version)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AgentRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentsForOwner = `-- name: ListAgentsForOwner :many
SELECT id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at FROM agents
WHERE owner_user_id = $1
ORDER BY agent_ref, created_at DESC
`

func (q *Queries) ListAgentsForOwner(ctx context.Context, ownerUserID int64) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.AgentRef,
			&i.Version,
			&i.Definition,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentImmutable = `-- name: MarkAgentImmutable :exec
UPDATE agents SET immutable = true WHERE id = $1
`

func (q *Queries) MarkAgentImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAgentImmutable, id)
	return err
}
