// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSubscribedListingsForAgentRef = `-- name: CountActiveSubscribedListingsForAgentRef :one
SELECT count(*) FROM marketplace_listings ml
JOIN agents a ON a.id = ml.resource_id
WHERE ml.resource_type = 'agent' AND a.owner_user_id = $1 AND a.agent_ref = $2 AND ml.subscriber_count > 0
`

type CountActiveSubscribedListingsForAgentRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
}

func (q *Queries) CountActiveSubscribedListingsForAgentRef(ctx context.Context, arg CountActiveSubscribedListingsForAgentRefParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscribedListingsForAgentRef, arg.OwnerUserID, arg.AgentRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one

INSERT INTO agents (owner_user_id, agent_ref, version, definition, display_meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at
`

type CreateAgentParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
	Definition  []byte `json:"definition"`
	DisplayMeta []byte `json:"display_meta"`
}

// Owner-view and subscriber-view queries are kept physically separate so the
// subscriber path can never accidentally SELECT `definition` (see
// docs/架构设计文档_AI-Agent平台_V1.md 五、"黑盒发布的实现要点").
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.OwnerUserID,
		arg.AgentRef,
		arg.Version,
		arg.Definition,
		arg.DisplayMeta,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AgentRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const deleteAgentsByRef = `-- name: DeleteAgentsByRef :exec
DELETE FROM agents WHERE owner_user_id = $1 AND agent_ref = $2
`

type DeleteAgentsByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
}

func (q *Queries) DeleteAgentsByRef(ctx context.Context, arg DeleteAgentsByRefParams) error {
	_, err := q.db.Exec(ctx, deleteAgentsByRef, arg.OwnerUserID, arg.AgentRef)
	return err
}

const findBundlesReferencingAgentRef = `-- name: FindBundlesReferencingAgentRef :many
SELECT bundle_ref, version FROM bundles
WHERE owner_user_id = $1
  AND definition->'agents' @> jsonb_build_array(jsonb_build_object('ref', $2::text))
`

type FindBundlesReferencingAgentRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Column2     string `json:"column_2"`
}

type FindBundlesReferencingAgentRefRow struct {
	BundleRef string `json:"bundle_ref"`
	Version   string `json:"version"`
}

func (q *Queries) FindBundlesReferencingAgentRef(ctx context.Context, arg FindBundlesReferencingAgentRefParams) ([]FindBundlesReferencingAgentRefRow, error) {
	rows, err := q.db.Query(ctx, findBundlesReferencingAgentRef, arg.OwnerUserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindBundlesReferencingAgentRefRow{}
	for rows.Next() {
		var i FindBundlesReferencingAgentRefRow
		if err := rows.Scan(&i.BundleRef, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentDisplayForSubscriber = `-- name: GetAgentDisplayForSubscriber :one
SELECT id, owner_user_id, agent_ref, version, display_meta, status, created_at
FROM agents
WHERE id = $1
`

type GetAgentDisplayForSubscriberRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	AgentRef    string             `json:"agent_ref"`
	Version     string             `json:"version"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAgentDisplayForSubscriber(ctx context.Context, id int64) (GetAgentDisplayForSubscriberRow, error) {
	row := q.db.QueryRow(ctx, getAgentDisplayForSubscriber, id)
	var i GetAgentDisplayForSubscriberRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AgentRef,
		&i.Version,
		&i.DisplayMeta,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentForOwner = `-- name: GetAgentForOwner :one
SELECT id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at FROM agents
WHERE owner_user_id = $1 AND agent_ref = $2 AND version = $3
`

type GetAgentForOwnerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
}

func (q *Queries) GetAgentForOwner(ctx context.Context, arg GetAgentForOwnerParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentForOwner, arg.OwnerUserID, arg.AgentRef, arg.Version)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AgentRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentLatestByRef = `-- name: GetAgentLatestByRef :one
SELECT id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at FROM agents
WHERE owner_user_id = $1 AND agent_ref = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetAgentLatestByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
}

func (q *Queries) GetAgentLatestByRef(ctx context.Context, arg GetAgentLatestByRefParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentLatestByRef, arg.OwnerUserID, arg.AgentRef)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AgentRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentVersionsForOwner = `-- name: ListAgentVersionsForOwner :many
SELECT id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at FROM agents
WHERE owner_user_id = $1 AND agent_ref = $2
ORDER BY created_at DESC
`

type ListAgentVersionsForOwnerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
}

func (q *Queries) ListAgentVersionsForOwner(ctx context.Context, arg ListAgentVersionsForOwnerParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentVersionsForOwner, arg.OwnerUserID, arg.AgentRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.AgentRef,
			&i.Version,
			&i.Definition,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsForOwner = `-- name: ListAgentsForOwner :many
SELECT id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at FROM agents
WHERE owner_user_id = $1
ORDER BY agent_ref, created_at DESC
`

func (q *Queries) ListAgentsForOwner(ctx context.Context, ownerUserID int64) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.AgentRef,
			&i.Version,
			&i.Definition,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsForOwnerLatestPage = `-- name: ListAgentsForOwnerLatestPage :many
SELECT DISTINCT ON (agent_ref) id, owner_user_id, agent_ref, version, definition, display_meta, status, immutable, created_at
FROM agents
WHERE owner_user_id = $1 AND agent_ref > $2
ORDER BY agent_ref ASC, created_at DESC
LIMIT $3
`

type ListAgentsForOwnerLatestPageParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Limit       int32  `json:"limit"`
}

// One row per agent_ref (its most recently created version), per
// api/openapi.yaml's "每个 ref 返回最新启用版本" list contract.
func (q *Queries) ListAgentsForOwnerLatestPage(ctx context.Context, arg ListAgentsForOwnerLatestPageParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsForOwnerLatestPage, arg.OwnerUserID, arg.AgentRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.AgentRef,
			&i.Version,
			&i.Definition,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentImmutable = `-- name: MarkAgentImmutable :exec
UPDATE agents SET immutable = true WHERE id = $1
`

func (q *Queries) MarkAgentImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAgentImmutable, id)
	return err
}

const setAgentDisplayMeta = `-- name: SetAgentDisplayMeta :exec
UPDATE agents SET display_meta = $2 WHERE id = $1
`

type SetAgentDisplayMetaParams struct {
	ID          int64  `json:"id"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) SetAgentDisplayMeta(ctx context.Context, arg SetAgentDisplayMetaParams) error {
	_, err := q.db.Exec(ctx, setAgentDisplayMeta, arg.ID, arg.DisplayMeta)
	return err
}

const setAgentStatusByID = `-- name: SetAgentStatusByID :exec
UPDATE agents SET status = $2 WHERE id = $1
`

type SetAgentStatusByIDParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetAgentStatusByID(ctx context.Context, arg SetAgentStatusByIDParams) error {
	_, err := q.db.Exec(ctx, setAgentStatusByID, arg.ID, arg.Status)
	return err
}
