// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (owner_user_id, name, key_hash)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, name, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Name        string `json:"name"`
	KeyHash     string `json:"key_hash"`
}

type CreateAPIKeyRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Name        string             `json:"name"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.OwnerUserID, arg.Name, arg.KeyHash)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, owner_user_id, name, key_hash, last_used_at, revoked_at, created_at FROM api_keys WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysForOwner = `-- name: ListAPIKeysForOwner :many
SELECT id, owner_user_id, name, last_used_at, revoked_at, created_at
FROM api_keys
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysForOwnerRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Name        string             `json:"name"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysForOwner(ctx context.Context, ownerUserID int64) ([]ListAPIKeysForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysForOwnerRow{}
	for rows.Next() {
		var i ListAPIKeysForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND owner_user_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
