// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bundles.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSubscribedListingsForBundleRef = `-- name: CountActiveSubscribedListingsForBundleRef :one
SELECT count(*) FROM marketplace_listings ml
JOIN bundles b ON b.id = ml.resource_id
WHERE ml.resource_type = 'bundle' AND b.owner_user_id = $1 AND b.bundle_ref = $2 AND ml.subscriber_count > 0
`

type CountActiveSubscribedListingsForBundleRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	BundleRef   string `json:"bundle_ref"`
}

func (q *Queries) CountActiveSubscribedListingsForBundleRef(ctx context.Context, arg CountActiveSubscribedListingsForBundleRefParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscribedListingsForBundleRef, arg.OwnerUserID, arg.BundleRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBundle = `-- name: CreateBundle :one
INSERT INTO bundles (owner_user_id, bundle_ref, version, definition, display_meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, bundle_ref, version, definition, display_meta, status, immutable, created_at
`

type CreateBundleParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	BundleRef   string `json:"bundle_ref"`
	Version     string `json:"version"`
	Definition  []byte `json:"definition"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) CreateBundle(ctx context.Context, arg CreateBundleParams) (Bundle, error) {
	row := q.db.QueryRow(ctx, createBundle,
		arg.OwnerUserID,
		arg.BundleRef,
		arg.Version,
		arg.Definition,
		arg.DisplayMeta,
	)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BundleRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBundle = `-- name: DeleteBundle :exec
DELETE FROM bundles WHERE id = $1
`

func (q *Queries) DeleteBundle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBundle, id)
	return err
}

const deleteBundlesByRef = `-- name: DeleteBundlesByRef :exec
DELETE FROM bundles WHERE owner_user_id = $1 AND bundle_ref = $2
`

type DeleteBundlesByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	BundleRef   string `json:"bundle_ref"`
}

func (q *Queries) DeleteBundlesByRef(ctx context.Context, arg DeleteBundlesByRefParams) error {
	_, err := q.db.Exec(ctx, deleteBundlesByRef, arg.OwnerUserID, arg.BundleRef)
	return err
}

const getBundleByID = `-- name: GetBundleByID :one
SELECT id, owner_user_id, bundle_ref, version, definition, display_meta, status, immutable, created_at FROM bundles WHERE id = $1
`

// Internal use only (spec-11 run engine): fetches the full row, including
// `definition`, by raw id regardless of owner — a run compiles a Bundle
// whose owner may not be the requesting subscriber. Never exposed
// directly to an HTTP response; the blackbox boundary is enforced by the
// handler layer, not by this query.
func (q *Queries) GetBundleByID(ctx context.Context, id int64) (Bundle, error) {
	row := q.db.QueryRow(ctx, getBundleByID, id)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BundleRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getBundleDisplayForSubscriber = `-- name: GetBundleDisplayForSubscriber :one
SELECT id, owner_user_id, bundle_ref, version, display_meta, status, created_at
FROM bundles
WHERE id = $1
`

type GetBundleDisplayForSubscriberRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	BundleRef   string             `json:"bundle_ref"`
	Version     string             `json:"version"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetBundleDisplayForSubscriber(ctx context.Context, id int64) (GetBundleDisplayForSubscriberRow, error) {
	row := q.db.QueryRow(ctx, getBundleDisplayForSubscriber, id)
	var i GetBundleDisplayForSubscriberRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BundleRef,
		&i.Version,
		&i.DisplayMeta,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBundleForOwner = `-- name: GetBundleForOwner :one
SELECT id, owner_user_id, bundle_ref, version, definition, display_meta, status, immutable, created_at FROM bundles
WHERE owner_user_id = $1 AND bundle_ref = $2 AND version = $3
`

type GetBundleForOwnerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	BundleRef   string `json:"bundle_ref"`
	Version     string `json:"version"`
}

func (q *Queries) GetBundleForOwner(ctx context.Context, arg GetBundleForOwnerParams) (Bundle, error) {
	row := q.db.QueryRow(ctx, getBundleForOwner, arg.OwnerUserID, arg.BundleRef, arg.Version)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BundleRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getBundleLatestByRef = `-- name: GetBundleLatestByRef :one
SELECT id, owner_user_id, bundle_ref, version, definition, display_meta, status, immutable, created_at FROM bundles
WHERE owner_user_id = $1 AND bundle_ref = $2 AND status = 1
ORDER BY created_at DESC
LIMIT 1
`

type GetBundleLatestByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	BundleRef   string `json:"bundle_ref"`
}

// "Latest enabled version" per api/openapi.yaml's createRun: "bundle_version
// 省略则使用最新启用版本".
func (q *Queries) GetBundleLatestByRef(ctx context.Context, arg GetBundleLatestByRefParams) (Bundle, error) {
	row := q.db.QueryRow(ctx, getBundleLatestByRef, arg.OwnerUserID, arg.BundleRef)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BundleRef,
		&i.Version,
		&i.Definition,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const listBundleVersionsForOwner = `-- name: ListBundleVersionsForOwner :many
SELECT id, owner_user_id, bundle_ref, version, definition, display_meta, status, immutable, created_at FROM bundles
WHERE owner_user_id = $1 AND bundle_ref = $2
ORDER BY created_at DESC
`

type ListBundleVersionsForOwnerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	BundleRef   string `json:"bundle_ref"`
}

func (q *Queries) ListBundleVersionsForOwner(ctx context.Context, arg ListBundleVersionsForOwnerParams) ([]Bundle, error) {
	rows, err := q.db.Query(ctx, listBundleVersionsForOwner, arg.OwnerUserID, arg.BundleRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bundle{}
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BundleRef,
			&i.Version,
			&i.Definition,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundlesForOwner = `-- name: ListBundlesForOwner :many
SELECT id, owner_user_id, bundle_ref, version, definition, display_meta, status, immutable, created_at FROM bundles
WHERE owner_user_id = $1
ORDER BY bundle_ref, created_at DESC
`

func (q *Queries) ListBundlesForOwner(ctx context.Context, ownerUserID int64) ([]Bundle, error) {
	rows, err := q.db.Query(ctx, listBundlesForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bundle{}
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BundleRef,
			&i.Version,
			&i.Definition,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundlesForOwnerLatestPage = `-- name: ListBundlesForOwnerLatestPage :many
SELECT DISTINCT ON (bundle_ref) id, owner_user_id, bundle_ref, version, definition, display_meta, status, immutable, created_at
FROM bundles
WHERE owner_user_id = $1 AND bundle_ref > $2
ORDER BY bundle_ref ASC, created_at DESC
LIMIT $3
`

type ListBundlesForOwnerLatestPageParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	BundleRef   string `json:"bundle_ref"`
	Limit       int32  `json:"limit"`
}

// One row per bundle_ref (its most recently created version).
func (q *Queries) ListBundlesForOwnerLatestPage(ctx context.Context, arg ListBundlesForOwnerLatestPageParams) ([]Bundle, error) {
	rows, err := q.db.Query(ctx, listBundlesForOwnerLatestPage, arg.OwnerUserID, arg.BundleRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bundle{}
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BundleRef,
			&i.Version,
			&i.Definition,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBundleImmutable = `-- name: MarkBundleImmutable :exec
UPDATE bundles SET immutable = true WHERE id = $1
`

func (q *Queries) MarkBundleImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markBundleImmutable, id)
	return err
}

const setBundleDisplayMeta = `-- name: SetBundleDisplayMeta :exec
UPDATE bundles SET display_meta = $2 WHERE id = $1
`

type SetBundleDisplayMetaParams struct {
	ID          int64  `json:"id"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) SetBundleDisplayMeta(ctx context.Context, arg SetBundleDisplayMetaParams) error {
	_, err := q.db.Exec(ctx, setBundleDisplayMeta, arg.ID, arg.DisplayMeta)
	return err
}

const setBundleStatusByID = `-- name: SetBundleStatusByID :exec
UPDATE bundles SET status = $2 WHERE id = $1
`

type SetBundleStatusByIDParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetBundleStatusByID(ctx context.Context, arg SetBundleStatusByIDParams) error {
	_, err := q.db.Exec(ctx, setBundleStatusByID, arg.ID, arg.Status)
	return err
}
