// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: human_gates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHumanGate = `-- name: CreateHumanGate :one
INSERT INTO human_gates (run_id, node, timeout_seconds, on_timeout, approver_roles)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, node, status, timeout_seconds, on_timeout, approver_roles, resolved_by, comment, created_at, resolved_at
`

type CreateHumanGateParams struct {
	RunID          string      `json:"run_id"`
	Node           string      `json:"node"`
	TimeoutSeconds pgtype.Int4 `json:"timeout_seconds"`
	OnTimeout      string      `json:"on_timeout"`
	ApproverRoles  []byte      `json:"approver_roles"`
}

func (q *Queries) CreateHumanGate(ctx context.Context, arg CreateHumanGateParams) (HumanGate, error) {
	row := q.db.QueryRow(ctx, createHumanGate,
		arg.RunID,
		arg.Node,
		arg.TimeoutSeconds,
		arg.OnTimeout,
		arg.ApproverRoles,
	)
	var i HumanGate
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Node,
		&i.Status,
		&i.TimeoutSeconds,
		&i.OnTimeout,
		&i.ApproverRoles,
		&i.ResolvedBy,
		&i.Comment,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getHumanGateByID = `-- name: GetHumanGateByID :one
SELECT id, run_id, node, status, timeout_seconds, on_timeout, approver_roles, resolved_by, comment, created_at, resolved_at FROM human_gates WHERE id = $1
`

func (q *Queries) GetHumanGateByID(ctx context.Context, id int64) (HumanGate, error) {
	row := q.db.QueryRow(ctx, getHumanGateByID, id)
	var i HumanGate
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Node,
		&i.Status,
		&i.TimeoutSeconds,
		&i.OnTimeout,
		&i.ApproverRoles,
		&i.ResolvedBy,
		&i.Comment,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPendingHumanGateForRunNode = `-- name: GetPendingHumanGateForRunNode :one
SELECT id, run_id, node, status, timeout_seconds, on_timeout, approver_roles, resolved_by, comment, created_at, resolved_at FROM human_gates
WHERE run_id = $1 AND node = $2 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingHumanGateForRunNodeParams struct {
	RunID string `json:"run_id"`
	Node  string `json:"node"`
}

// A node can gate more than once across a Bundle's lifetime (e.g. inside a
// self-loop retry), so this always resolves to the most recent occurrence
// for that run+node — the one actually blocking right now.
func (q *Queries) GetPendingHumanGateForRunNode(ctx context.Context, arg GetPendingHumanGateForRunNodeParams) (HumanGate, error) {
	row := q.db.QueryRow(ctx, getPendingHumanGateForRunNode, arg.RunID, arg.Node)
	var i HumanGate
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Node,
		&i.Status,
		&i.TimeoutSeconds,
		&i.OnTimeout,
		&i.ApproverRoles,
		&i.ResolvedBy,
		&i.Comment,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listHumanGatesForRun = `-- name: ListHumanGatesForRun :many
SELECT id, run_id, node, status, timeout_seconds, on_timeout, approver_roles, resolved_by, comment, created_at, resolved_at FROM human_gates WHERE run_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListHumanGatesForRun(ctx context.Context, runID string) ([]HumanGate, error) {
	rows, err := q.db.Query(ctx, listHumanGatesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HumanGate{}
	for rows.Next() {
		var i HumanGate
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Node,
			&i.Status,
			&i.TimeoutSeconds,
			&i.OnTimeout,
			&i.ApproverRoles,
			&i.ResolvedBy,
			&i.Comment,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHumanGatesPastTimeout = `-- name: ListPendingHumanGatesPastTimeout :many
SELECT id, run_id, node, status, timeout_seconds, on_timeout, approver_roles, resolved_by, comment, created_at, resolved_at FROM human_gates
WHERE status = 'pending'
  AND timeout_seconds IS NOT NULL
  AND created_at + make_interval(secs => timeout_seconds) < now()
ORDER BY created_at ASC
`

// Backs the timeout-scanning job (spec-11): a pending gate with a
// timeout_seconds set, whose deadline has passed.
func (q *Queries) ListPendingHumanGatesPastTimeout(ctx context.Context) ([]HumanGate, error) {
	rows, err := q.db.Query(ctx, listPendingHumanGatesPastTimeout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HumanGate{}
	for rows.Next() {
		var i HumanGate
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Node,
			&i.Status,
			&i.TimeoutSeconds,
			&i.OnTimeout,
			&i.ApproverRoles,
			&i.ResolvedBy,
			&i.Comment,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveHumanGate = `-- name: ResolveHumanGate :one
UPDATE human_gates
SET status = $2, resolved_by = $3, comment = $4, resolved_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, run_id, node, status, timeout_seconds, on_timeout, approver_roles, resolved_by, comment, created_at, resolved_at
`

type ResolveHumanGateParams struct {
	ID         int64       `json:"id"`
	Status     string      `json:"status"`
	ResolvedBy pgtype.Int8 `json:"resolved_by"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) ResolveHumanGate(ctx context.Context, arg ResolveHumanGateParams) (HumanGate, error) {
	row := q.db.QueryRow(ctx, resolveHumanGate,
		arg.ID,
		arg.Status,
		arg.ResolvedBy,
		arg.Comment,
	)
	var i HumanGate
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Node,
		&i.Status,
		&i.TimeoutSeconds,
		&i.OnTimeout,
		&i.ApproverRoles,
		&i.ResolvedBy,
		&i.Comment,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
