// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: idempotency.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, owner_user_id, status_code, response_body, created_at, expires_at FROM idempotency_keys WHERE key = $1 AND expires_at > now()
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.OwnerUserID,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const putIdempotencyKey = `-- name: PutIdempotencyKey :exec
INSERT INTO idempotency_keys (key, owner_user_id, status_code, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO NOTHING
`

type PutIdempotencyKeyParams struct {
	Key          string             `json:"key"`
	OwnerUserID  int64              `json:"owner_user_id"`
	StatusCode   int32              `json:"status_code"`
	ResponseBody []byte             `json:"response_body"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, putIdempotencyKey,
		arg.Key,
		arg.OwnerUserID,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	return err
}
