// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: kb_chunks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const deleteKBChunksBySource = `-- name: DeleteKBChunksBySource :exec
DELETE FROM kb_chunks WHERE knowledge_base_id = $1 AND owner_user_id = $2 AND source_ref = $3
`

type DeleteKBChunksBySourceParams struct {
	KnowledgeBaseID int64  `json:"knowledge_base_id"`
	OwnerUserID     int64  `json:"owner_user_id"`
	SourceRef       string `json:"source_ref"`
}

func (q *Queries) DeleteKBChunksBySource(ctx context.Context, arg DeleteKBChunksBySourceParams) error {
	_, err := q.db.Exec(ctx, deleteKBChunksBySource, arg.KnowledgeBaseID, arg.OwnerUserID, arg.SourceRef)
	return err
}

const insertKBChunk = `-- name: InsertKBChunk :one
INSERT INTO kb_chunks (knowledge_base_id, owner_user_id, source_ref, chunk_index, content, embedding)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertKBChunkParams struct {
	KnowledgeBaseID int64           `json:"knowledge_base_id"`
	OwnerUserID     int64           `json:"owner_user_id"`
	SourceRef       string          `json:"source_ref"`
	ChunkIndex      int32           `json:"chunk_index"`
	Content         string          `json:"content"`
	Embedding       pgvector.Vector `json:"embedding"`
}

func (q *Queries) InsertKBChunk(ctx context.Context, arg InsertKBChunkParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertKBChunk,
		arg.KnowledgeBaseID,
		arg.OwnerUserID,
		arg.SourceRef,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listKBSources = `-- name: ListKBSources :many
SELECT source_ref, count(*)::int AS chunk_count, min(created_at)::timestamptz AS ingested_at
FROM kb_chunks
WHERE knowledge_base_id = $1 AND owner_user_id = $2
GROUP BY source_ref
ORDER BY min(created_at) DESC
`

type ListKBSourcesParams struct {
	KnowledgeBaseID int64 `json:"knowledge_base_id"`
	OwnerUserID     int64 `json:"owner_user_id"`
}

type ListKBSourcesRow struct {
	SourceRef  string             `json:"source_ref"`
	ChunkCount int32              `json:"chunk_count"`
	IngestedAt pgtype.Timestamptz `json:"ingested_at"`
}

func (q *Queries) ListKBSources(ctx context.Context, arg ListKBSourcesParams) ([]ListKBSourcesRow, error) {
	rows, err := q.db.Query(ctx, listKBSources, arg.KnowledgeBaseID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKBSourcesRow{}
	for rows.Next() {
		var i ListKBSourcesRow
		if err := rows.Scan(&i.SourceRef, &i.ChunkCount, &i.IngestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKBChunks = `-- name: SearchKBChunks :many
SELECT id, source_ref, chunk_index, content, (embedding <=> $3)::float8 AS distance
FROM kb_chunks
WHERE knowledge_base_id = $1 AND owner_user_id = $2
ORDER BY embedding <=> $3
LIMIT $4
`

type SearchKBChunksParams struct {
	KnowledgeBaseID int64           `json:"knowledge_base_id"`
	OwnerUserID     int64           `json:"owner_user_id"`
	Embedding       pgvector.Vector `json:"embedding"`
	Limit           int32           `json:"limit"`
}

type SearchKBChunksRow struct {
	ID         int64   `json:"id"`
	SourceRef  string  `json:"source_ref"`
	ChunkIndex int32   `json:"chunk_index"`
	Content    string  `json:"content"`
	Distance   float64 `json:"distance"`
}

func (q *Queries) SearchKBChunks(ctx context.Context, arg SearchKBChunksParams) ([]SearchKBChunksRow, error) {
	rows, err := q.db.Query(ctx, searchKBChunks,
		arg.KnowledgeBaseID,
		arg.OwnerUserID,
		arg.Embedding,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKBChunksRow{}
	for rows.Next() {
		var i SearchKBChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceRef,
			&i.ChunkIndex,
			&i.Content,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
