// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: knowledge_bases.sql

package store

import (
	"context"
)

const createKnowledgeBase = `-- name: CreateKnowledgeBase :one
INSERT INTO knowledge_bases (owner_user_id, ref, version, config, display_meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type CreateKnowledgeBaseParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
	Config      []byte `json:"config"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRow(ctx, createKnowledgeBase,
		arg.OwnerUserID,
		arg.Ref,
		arg.Version,
		arg.Config,
		arg.DisplayMeta,
	)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const findAgentsReferencingKnowledgeBaseRef = `-- name: FindAgentsReferencingKnowledgeBaseRef :many
SELECT owner_user_id, agent_ref, version FROM agents
WHERE owner_user_id = $1
  AND (definition->'capabilities'->'tools') ? $2::text
`

type FindAgentsReferencingKnowledgeBaseRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Column2     string `json:"column_2"`
}

type FindAgentsReferencingKnowledgeBaseRefRow struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
}

// Knowledge bases surface to an Agent as an entry in capabilities.tools
// (the DSL has no separate knowledge_base array) — same lookup as tools.
func (q *Queries) FindAgentsReferencingKnowledgeBaseRef(ctx context.Context, arg FindAgentsReferencingKnowledgeBaseRefParams) ([]FindAgentsReferencingKnowledgeBaseRefRow, error) {
	rows, err := q.db.Query(ctx, findAgentsReferencingKnowledgeBaseRef, arg.OwnerUserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAgentsReferencingKnowledgeBaseRefRow{}
	for rows.Next() {
		var i FindAgentsReferencingKnowledgeBaseRefRow
		if err := rows.Scan(&i.OwnerUserID, &i.AgentRef, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKnowledgeBaseByIDForOwner = `-- name: GetKnowledgeBaseByIDForOwner :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM knowledge_bases WHERE id = $1 AND owner_user_id = $2
`

type GetKnowledgeBaseByIDForOwnerParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) GetKnowledgeBaseByIDForOwner(ctx context.Context, arg GetKnowledgeBaseByIDForOwnerParams) (KnowledgeBasis, error) {
	row := q.db.QueryRow(ctx, getKnowledgeBaseByIDForOwner, arg.ID, arg.OwnerUserID)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const listKnowledgeBasesForOwnerPage = `-- name: ListKnowledgeBasesForOwnerPage :many
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM knowledge_bases WHERE owner_user_id = $1 AND id > $2 ORDER BY id ASC LIMIT $3
`

type ListKnowledgeBasesForOwnerPageParams struct {
	OwnerUserID int64 `json:"owner_user_id"`
	ID          int64 `json:"id"`
	Limit       int32 `json:"limit"`
}

func (q *Queries) ListKnowledgeBasesForOwnerPage(ctx context.Context, arg ListKnowledgeBasesForOwnerPageParams) ([]KnowledgeBasis, error) {
	rows, err := q.db.Query(ctx, listKnowledgeBasesForOwnerPage, arg.OwnerUserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeBasis{}
	for rows.Next() {
		var i KnowledgeBasis
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Ref,
			&i.Version,
			&i.Config,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markKnowledgeBaseImmutable = `-- name: MarkKnowledgeBaseImmutable :exec
UPDATE knowledge_bases SET immutable = true WHERE id = $1
`

func (q *Queries) MarkKnowledgeBaseImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markKnowledgeBaseImmutable, id)
	return err
}

const updateKnowledgeBase = `-- name: UpdateKnowledgeBase :one
UPDATE knowledge_bases SET display_meta = $3, config = $4, status = $5
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type UpdateKnowledgeBaseParams struct {
	ID          int64  `json:"id"`
	OwnerUserID int64  `json:"owner_user_id"`
	DisplayMeta []byte `json:"display_meta"`
	Config      []byte `json:"config"`
	Status      int16  `json:"status"`
}

func (q *Queries) UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRow(ctx, updateKnowledgeBase,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayMeta,
		arg.Config,
		arg.Status,
	)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}
