// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: marketplace.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListing = `-- name: CreateListing :one
INSERT INTO marketplace_listings
    (author_user_id, resource_type, resource_id, listing_ref, version, changelog)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, author_user_id, resource_type, resource_id, listing_ref, version, visibility, changelog, distribution, subscriber_count, run_count, published_at
`

type CreateListingParams struct {
	AuthorUserID int64       `json:"author_user_id"`
	ResourceType string      `json:"resource_type"`
	ResourceID   int64       `json:"resource_id"`
	ListingRef   string      `json:"listing_ref"`
	Version      string      `json:"version"`
	Changelog    pgtype.Text `json:"changelog"`
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (MarketplaceListing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.AuthorUserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.ListingRef,
		arg.Version,
		arg.Changelog,
	)
	var i MarketplaceListing
	err := row.Scan(
		&i.ID,
		&i.AuthorUserID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ListingRef,
		&i.Version,
		&i.Visibility,
		&i.Changelog,
		&i.Distribution,
		&i.SubscriberCount,
		&i.RunCount,
		&i.PublishedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (subscriber_id, listing_id, local_alias)
VALUES ($1, $2, $3)
RETURNING id, subscriber_id, listing_id, local_alias, created_at
`

type CreateSubscriptionParams struct {
	SubscriberID int64       `json:"subscriber_id"`
	ListingID    int64       `json:"listing_id"`
	LocalAlias   pgtype.Text `json:"local_alias"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.SubscriberID, arg.ListingID, arg.LocalAlias)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.ListingID,
		&i.LocalAlias,
		&i.CreatedAt,
	)
	return i, err
}

const decrementListingSubscriberCount = `-- name: DecrementListingSubscriberCount :exec
UPDATE marketplace_listings SET subscriber_count = subscriber_count - 1 WHERE id = $1
`

func (q *Queries) DecrementListingSubscriberCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementListingSubscriberCount, id)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = $1 AND subscriber_id = $2
`

type DeleteSubscriptionParams struct {
	ID           int64 `json:"id"`
	SubscriberID int64 `json:"subscriber_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.ID, arg.SubscriberID)
	return err
}

const getListingByRefVersion = `-- name: GetListingByRefVersion :one
SELECT id, author_user_id, resource_type, resource_id, listing_ref, version, visibility, changelog, distribution, subscriber_count, run_count, published_at FROM marketplace_listings
WHERE listing_ref = $1 AND version = $2
`

type GetListingByRefVersionParams struct {
	ListingRef string `json:"listing_ref"`
	Version    string `json:"version"`
}

func (q *Queries) GetListingByRefVersion(ctx context.Context, arg GetListingByRefVersionParams) (MarketplaceListing, error) {
	row := q.db.QueryRow(ctx, getListingByRefVersion, arg.ListingRef, arg.Version)
	var i MarketplaceListing
	err := row.Scan(
		&i.ID,
		&i.AuthorUserID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ListingRef,
		&i.Version,
		&i.Visibility,
		&i.Changelog,
		&i.Distribution,
		&i.SubscriberCount,
		&i.RunCount,
		&i.PublishedAt,
	)
	return i, err
}

const incrementListingSubscriberCount = `-- name: IncrementListingSubscriberCount :exec
UPDATE marketplace_listings SET subscriber_count = subscriber_count + 1 WHERE id = $1
`

func (q *Queries) IncrementListingSubscriberCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementListingSubscriberCount, id)
	return err
}

const listListingsByType = `-- name: ListListingsByType :many
SELECT id, author_user_id, resource_type, resource_id, listing_ref, version, visibility, changelog, distribution, subscriber_count, run_count, published_at FROM marketplace_listings
WHERE resource_type = $1 AND distribution = 1
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListListingsByTypeParams struct {
	ResourceType string `json:"resource_type"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListListingsByType(ctx context.Context, arg ListListingsByTypeParams) ([]MarketplaceListing, error) {
	rows, err := q.db.Query(ctx, listListingsByType, arg.ResourceType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketplaceListing{}
	for rows.Next() {
		var i MarketplaceListing
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUserID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ListingRef,
			&i.Version,
			&i.Visibility,
			&i.Changelog,
			&i.Distribution,
			&i.SubscriberCount,
			&i.RunCount,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForUser = `-- name: ListSubscriptionsForUser :many
SELECT id, subscriber_id, listing_id, local_alias, created_at FROM subscriptions
WHERE subscriber_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsForUser(ctx context.Context, subscriberID int64) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUser, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.SubscriberID,
			&i.ListingID,
			&i.LocalAlias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setListingDistribution = `-- name: SetListingDistribution :exec
UPDATE marketplace_listings SET distribution = $2 WHERE id = $1
`

type SetListingDistributionParams struct {
	ID           int64 `json:"id"`
	Distribution int16 `json:"distribution"`
}

func (q *Queries) SetListingDistribution(ctx context.Context, arg SetListingDistributionParams) error {
	_, err := q.db.Exec(ctx, setListingDistribution, arg.ID, arg.Distribution)
	return err
}
