// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMarketMCPServersByReview = `-- name: CountMarketMCPServersByReview :many
SELECT review_status, COUNT(*)::bigint AS count
FROM market_mcp_servers
WHERE ($1::bigint IS NULL OR source_id = $1::bigint)
GROUP BY review_status
`

type CountMarketMCPServersByReviewRow struct {
	ReviewStatus string `json:"review_status"`
	Count        int64  `json:"count"`
}

// 审核台顶部的状态计数。source_id 为空时统计全部源；审核台是按源进的，
// 那里必须传源 ID，否则顶部计数和下面的列表对不上。
func (q *Queries) CountMarketMCPServersByReview(ctx context.Context, sourceID pgtype.Int8) ([]CountMarketMCPServersByReviewRow, error) {
	rows, err := q.db.Query(ctx, countMarketMCPServersByReview, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMarketMCPServersByReviewRow{}
	for rows.Next() {
		var i CountMarketMCPServersByReviewRow
		if err := rows.Scan(&i.ReviewStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMarketMCPServersForReview = `-- name: CountMarketMCPServersForReview :one
SELECT COUNT(*)::bigint
FROM market_mcp_servers m
JOIN mcp_sources s ON s.id = m.source_id
WHERE ($1::text IS NULL OR m.review_status = $1::text)
  AND ($2::bigint IS NULL OR m.source_id = $2::bigint)
  AND ($3::text IS NULL
       OR m.slug ILIKE '%' || $3::text || '%'
       OR m.name ILIKE '%' || $3::text || '%'
       OR COALESCE(m.summary, '') ILIKE '%' || $3::text || '%')
`

type CountMarketMCPServersForReviewParams struct {
	ReviewStatus pgtype.Text `json:"review_status"`
	SourceID     pgtype.Int8 `json:"source_id"`
	Search       pgtype.Text `json:"search"`
}

// 与 ListMarketMCPServersForReview 同一套筛选条件下的总数，供前端算总页数。
func (q *Queries) CountMarketMCPServersForReview(ctx context.Context, arg CountMarketMCPServersForReviewParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMarketMCPServersForReview, arg.ReviewStatus, arg.SourceID, arg.Search)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMCPSource = `-- name: CreateMCPSource :one
INSERT INTO mcp_sources (name, base_url, protocol, api_prefix, api_key_encrypted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at, protocol, api_prefix, api_key_encrypted
`

type CreateMCPSourceParams struct {
	Name            string      `json:"name"`
	BaseUrl         string      `json:"base_url"`
	Protocol        string      `json:"protocol"`
	ApiPrefix       string      `json:"api_prefix"`
	ApiKeyEncrypted pgtype.Text `json:"api_key_encrypted"`
}

func (q *Queries) CreateMCPSource(ctx context.Context, arg CreateMCPSourceParams) (McpSource, error) {
	row := q.db.QueryRow(ctx, createMCPSource,
		arg.Name,
		arg.BaseUrl,
		arg.Protocol,
		arg.ApiPrefix,
		arg.ApiKeyEncrypted,
	)
	var i McpSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.Protocol,
		&i.ApiPrefix,
		&i.ApiKeyEncrypted,
	)
	return i, err
}

const deleteMCPSource = `-- name: DeleteMCPSource :execrows
DELETE FROM mcp_sources WHERE id = $1
`

func (q *Queries) DeleteMCPSource(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCPSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleMarketMCPServers = `-- name: DeleteStaleMarketMCPServers :execrows
DELETE FROM market_mcp_servers
WHERE source_id = $1 AND slug <> ALL($2::text[])
`

type DeleteStaleMarketMCPServersParams struct {
	SourceID int64    `json:"source_id"`
	Column2  []string `json:"column_2"`
}

func (q *Queries) DeleteStaleMarketMCPServers(ctx context.Context, arg DeleteStaleMarketMCPServersParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleMarketMCPServers, arg.SourceID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMCPSource = `-- name: GetMCPSource :one
SELECT id, name, base_url, status, last_synced_at, last_sync_error, created_at, protocol, api_prefix, api_key_encrypted FROM mcp_sources WHERE id = $1
`

func (q *Queries) GetMCPSource(ctx context.Context, id int64) (McpSource, error) {
	row := q.db.QueryRow(ctx, getMCPSource, id)
	var i McpSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.Protocol,
		&i.ApiPrefix,
		&i.ApiKeyEncrypted,
	)
	return i, err
}

const getMCPSourceByURL = `-- name: GetMCPSourceByURL :one
SELECT id, name, base_url, status, last_synced_at, last_sync_error, created_at, protocol, api_prefix, api_key_encrypted FROM mcp_sources WHERE base_url = $1
`

func (q *Queries) GetMCPSourceByURL(ctx context.Context, baseUrl string) (McpSource, error) {
	row := q.db.QueryRow(ctx, getMCPSourceByURL, baseUrl)
	var i McpSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.Protocol,
		&i.ApiPrefix,
		&i.ApiKeyEncrypted,
	)
	return i, err
}

const getMarketMCPServer = `-- name: GetMarketMCPServer :one
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.repository_url, m.remote_url, m.remote_type, m.topics, m.updated_at, m.raw, m.synced_at, m.review_status, m.review_note, m.reviewed_at, m.reviewed_by, m.icon_url, s.name AS source_name, s.base_url AS source_base_url
FROM market_mcp_servers m
JOIN mcp_sources s ON s.id = m.source_id
WHERE m.id = $1
`

type GetMarketMCPServerRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	RepositoryUrl pgtype.Text        `json:"repository_url"`
	RemoteUrl     pgtype.Text        `json:"remote_url"`
	RemoteType    pgtype.Text        `json:"remote_type"`
	Topics        []string           `json:"topics"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	ReviewStatus  string             `json:"review_status"`
	ReviewNote    pgtype.Text        `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.Int8        `json:"reviewed_by"`
	IconUrl       pgtype.Text        `json:"icon_url"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

// 对外一律用行 id 寻址：上游的限定名带点和斜杠，做不了 URL 路径参数。
func (q *Queries) GetMarketMCPServer(ctx context.Context, id int64) (GetMarketMCPServerRow, error) {
	row := q.db.QueryRow(ctx, getMarketMCPServer, id)
	var i GetMarketMCPServerRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Version,
		&i.License,
		&i.RepositoryUrl,
		&i.RemoteUrl,
		&i.RemoteType,
		&i.Topics,
		&i.UpdatedAt,
		&i.Raw,
		&i.SyncedAt,
		&i.ReviewStatus,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.IconUrl,
		&i.SourceName,
		&i.SourceBaseUrl,
	)
	return i, err
}

const listMCPSources = `-- name: ListMCPSources :many
SELECT s.id, s.name, s.base_url, s.status, s.last_synced_at, s.last_sync_error, s.created_at, s.protocol, s.api_prefix, s.api_key_encrypted, COUNT(m.id)::bigint AS server_count
FROM mcp_sources s
LEFT JOIN market_mcp_servers m ON m.source_id = s.id
GROUP BY s.id
ORDER BY s.created_at DESC
`

type ListMCPSourcesRow struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	BaseUrl         string             `json:"base_url"`
	Status          int16              `json:"status"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncError   pgtype.Text        `json:"last_sync_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Protocol        string             `json:"protocol"`
	ApiPrefix       string             `json:"api_prefix"`
	ApiKeyEncrypted pgtype.Text        `json:"api_key_encrypted"`
	ServerCount     int64              `json:"server_count"`
}

// 左联 market_mcp_servers 只为拿每个源的条目数，设置页直接展示。
func (q *Queries) ListMCPSources(ctx context.Context) ([]ListMCPSourcesRow, error) {
	rows, err := q.db.Query(ctx, listMCPSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPSourcesRow{}
	for rows.Next() {
		var i ListMCPSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.CreatedAt,
			&i.Protocol,
			&i.ApiPrefix,
			&i.ApiKeyEncrypted,
			&i.ServerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketMCPServers = `-- name: ListMarketMCPServers :many
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.repository_url, m.remote_url, m.remote_type, m.topics, m.updated_at, m.raw, m.synced_at, m.review_status, m.review_note, m.reviewed_at, m.reviewed_by, m.icon_url, s.name AS source_name, s.base_url AS source_base_url
FROM market_mcp_servers m
JOIN mcp_sources s ON s.id = m.source_id AND s.status = 1
WHERE m.review_status = 'approved'
ORDER BY m.updated_at DESC NULLS LAST
`

type ListMarketMCPServersRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	RepositoryUrl pgtype.Text        `json:"repository_url"`
	RemoteUrl     pgtype.Text        `json:"remote_url"`
	RemoteType    pgtype.Text        `json:"remote_type"`
	Topics        []string           `json:"topics"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	ReviewStatus  string             `json:"review_status"`
	ReviewNote    pgtype.Text        `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.Int8        `json:"reviewed_by"`
	IconUrl       pgtype.Text        `json:"icon_url"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

// MCP 管理 → 市场视图：所有启用源里**审核通过**的缓存条目。未过审的条目
// 对普通用户根本不存在（审核台走 ListMarketMCPServersForReview）。
func (q *Queries) ListMarketMCPServers(ctx context.Context) ([]ListMarketMCPServersRow, error) {
	rows, err := q.db.Query(ctx, listMarketMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketMCPServersRow{}
	for rows.Next() {
		var i ListMarketMCPServersRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.Version,
			&i.License,
			&i.RepositoryUrl,
			&i.RemoteUrl,
			&i.RemoteType,
			&i.Topics,
			&i.UpdatedAt,
			&i.Raw,
			&i.SyncedAt,
			&i.ReviewStatus,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.IconUrl,
			&i.SourceName,
			&i.SourceBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketMCPServersForReview = `-- name: ListMarketMCPServersForReview :many
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.repository_url, m.remote_url, m.remote_type, m.topics, m.updated_at, m.raw, m.synced_at, m.review_status, m.review_note, m.reviewed_at, m.reviewed_by, m.icon_url, s.name AS source_name, s.base_url AS source_base_url
FROM market_mcp_servers m
JOIN mcp_sources s ON s.id = m.source_id
WHERE ($1::text IS NULL OR m.review_status = $1::text)
  AND ($2::bigint IS NULL OR m.source_id = $2::bigint)
  AND ($3::text IS NULL
       OR m.slug ILIKE '%' || $3::text || '%'
       OR m.name ILIKE '%' || $3::text || '%'
       OR COALESCE(m.summary, '') ILIKE '%' || $3::text || '%')
ORDER BY m.review_status = 'pending' DESC, m.synced_at DESC, m.slug
LIMIT $5 OFFSET $4
`

type ListMarketMCPServersForReviewParams struct {
	ReviewStatus pgtype.Text `json:"review_status"`
	SourceID     pgtype.Int8 `json:"source_id"`
	Search       pgtype.Text `json:"search"`
	Off          int32       `json:"off"`
	Lim          int32       `json:"lim"`
}

type ListMarketMCPServersForReviewRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	RepositoryUrl pgtype.Text        `json:"repository_url"`
	RemoteUrl     pgtype.Text        `json:"remote_url"`
	RemoteType    pgtype.Text        `json:"remote_type"`
	Topics        []string           `json:"topics"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	ReviewStatus  string             `json:"review_status"`
	ReviewNote    pgtype.Text        `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.Int8        `json:"reviewed_by"`
	IconUrl       pgtype.Text        `json:"icon_url"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

// 审核台（系统配置 → MCP 源）：不筛源状态、不筛审核状态地列出同步条目。
// 分页和搜索都在库里做——一个公开注册中心动辄上千条。
func (q *Queries) ListMarketMCPServersForReview(ctx context.Context, arg ListMarketMCPServersForReviewParams) ([]ListMarketMCPServersForReviewRow, error) {
	rows, err := q.db.Query(ctx, listMarketMCPServersForReview,
		arg.ReviewStatus,
		arg.SourceID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketMCPServersForReviewRow{}
	for rows.Next() {
		var i ListMarketMCPServersForReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.Version,
			&i.License,
			&i.RepositoryUrl,
			&i.RemoteUrl,
			&i.RemoteType,
			&i.Topics,
			&i.UpdatedAt,
			&i.Raw,
			&i.SyncedAt,
			&i.ReviewStatus,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.IconUrl,
			&i.SourceName,
			&i.SourceBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMCPSourceSyncError = `-- name: MarkMCPSourceSyncError :one
UPDATE mcp_sources
SET last_synced_at = now(), last_sync_error = $2
WHERE id = $1
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at, protocol, api_prefix, api_key_encrypted
`

type MarkMCPSourceSyncErrorParams struct {
	ID            int64       `json:"id"`
	LastSyncError pgtype.Text `json:"last_sync_error"`
}

func (q *Queries) MarkMCPSourceSyncError(ctx context.Context, arg MarkMCPSourceSyncErrorParams) (McpSource, error) {
	row := q.db.QueryRow(ctx, markMCPSourceSyncError, arg.ID, arg.LastSyncError)
	var i McpSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.Protocol,
		&i.ApiPrefix,
		&i.ApiKeyEncrypted,
	)
	return i, err
}

const markMCPSourceSynced = `-- name: MarkMCPSourceSynced :one
UPDATE mcp_sources
SET last_synced_at = now(), last_sync_error = NULL
WHERE id = $1
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at, protocol, api_prefix, api_key_encrypted
`

func (q *Queries) MarkMCPSourceSynced(ctx context.Context, id int64) (McpSource, error) {
	row := q.db.QueryRow(ctx, markMCPSourceSynced, id)
	var i McpSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.Protocol,
		&i.ApiPrefix,
		&i.ApiKeyEncrypted,
	)
	return i, err
}

const setMCPSourceAPIKey = `-- name: SetMCPSourceAPIKey :execrows
UPDATE mcp_sources SET api_key_encrypted = $2 WHERE id = $1
`

type SetMCPSourceAPIKeyParams struct {
	ID              int64       `json:"id"`
	ApiKeyEncrypted pgtype.Text `json:"api_key_encrypted"`
}

// 单独换密钥：密钥过期时不必删掉源再重建（那会连审核结论一起丢掉）。
func (q *Queries) SetMCPSourceAPIKey(ctx context.Context, arg SetMCPSourceAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMCPSourceAPIKey, arg.ID, arg.ApiKeyEncrypted)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMarketMCPServerReview = `-- name: SetMarketMCPServerReview :execrows
UPDATE market_mcp_servers
SET review_status = $2, review_note = $3, reviewed_at = now(), reviewed_by = $4
WHERE id = $1
`

type SetMarketMCPServerReviewParams struct {
	ID           int64       `json:"id"`
	ReviewStatus string      `json:"review_status"`
	ReviewNote   pgtype.Text `json:"review_note"`
	ReviewedBy   pgtype.Int8 `json:"reviewed_by"`
}

func (q *Queries) SetMarketMCPServerReview(ctx context.Context, arg SetMarketMCPServerReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMarketMCPServerReview,
		arg.ID,
		arg.ReviewStatus,
		arg.ReviewNote,
		arg.ReviewedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMarketMCPServer = `-- name: UpsertMarketMCPServer :one
INSERT INTO market_mcp_servers (source_id, slug, name, summary, version, license, repository_url, remote_url, remote_type, topics, updated_at, raw, icon_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (source_id, slug) DO UPDATE SET
    name           = EXCLUDED.name,
    summary        = EXCLUDED.summary,
    version        = EXCLUDED.version,
    license        = EXCLUDED.license,
    repository_url = EXCLUDED.repository_url,
    remote_url     = EXCLUDED.remote_url,
    remote_type    = EXCLUDED.remote_type,
    icon_url       = EXCLUDED.icon_url,
    topics         = EXCLUDED.topics,
    updated_at     = EXCLUDED.updated_at,
    raw            = EXCLUDED.raw,
    synced_at      = now()
RETURNING id, source_id, slug, name, summary, version, license, repository_url, remote_url, remote_type, topics, updated_at, raw, synced_at, review_status, review_note, reviewed_at, reviewed_by, icon_url
`

type UpsertMarketMCPServerParams struct {
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	RepositoryUrl pgtype.Text        `json:"repository_url"`
	RemoteUrl     pgtype.Text        `json:"remote_url"`
	RemoteType    pgtype.Text        `json:"remote_type"`
	Topics        []string           `json:"topics"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	IconUrl       pgtype.Text        `json:"icon_url"`
}

// 同步落库：同一 (source, slug) 覆盖刷新，上次同步后被上游下架的条目由
// Sync 清理（见 DeleteStaleMarketMCPServers）。
//
// review_* 刻意不在 DO UPDATE 里：审核结论是本地判断，不是上游字段。每次
// 同步都重置的话，管理员批准过的条目会在下次同步后集体打回待审。
func (q *Queries) UpsertMarketMCPServer(ctx context.Context, arg UpsertMarketMCPServerParams) (MarketMcpServer, error) {
	row := q.db.QueryRow(ctx, upsertMarketMCPServer,
		arg.SourceID,
		arg.Slug,
		arg.Name,
		arg.Summary,
		arg.Version,
		arg.License,
		arg.RepositoryUrl,
		arg.RemoteUrl,
		arg.RemoteType,
		arg.Topics,
		arg.UpdatedAt,
		arg.Raw,
		arg.IconUrl,
	)
	var i MarketMcpServer
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Version,
		&i.License,
		&i.RepositoryUrl,
		&i.RemoteUrl,
		&i.RemoteType,
		&i.Topics,
		&i.UpdatedAt,
		&i.Raw,
		&i.SyncedAt,
		&i.ReviewStatus,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.IconUrl,
	)
	return i, err
}
