// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_servers.sql

package store

import (
	"context"
)

const createMCPServer = `-- name: CreateMCPServer :one
INSERT INTO mcp_servers (owner_user_id, ref, version, config, display_meta, health)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_user_id, ref, version, config, display_meta, status, health, immutable, created_at
`

type CreateMCPServerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
	Config      []byte `json:"config"`
	DisplayMeta []byte `json:"display_meta"`
	Health      string `json:"health"`
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, createMCPServer,
		arg.OwnerUserID,
		arg.Ref,
		arg.Version,
		arg.Config,
		arg.DisplayMeta,
		arg.Health,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Health,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const findAgentsReferencingMCPServerRef = `-- name: FindAgentsReferencingMCPServerRef :many
SELECT owner_user_id, agent_ref, version FROM agents
WHERE owner_user_id = $1
  AND (definition->'capabilities'->'tools') ? $2::text
`

type FindAgentsReferencingMCPServerRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Column2     string `json:"column_2"`
}

type FindAgentsReferencingMCPServerRefRow struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
}

func (q *Queries) FindAgentsReferencingMCPServerRef(ctx context.Context, arg FindAgentsReferencingMCPServerRefParams) ([]FindAgentsReferencingMCPServerRefRow, error) {
	rows, err := q.db.Query(ctx, findAgentsReferencingMCPServerRef, arg.OwnerUserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAgentsReferencingMCPServerRefRow{}
	for rows.Next() {
		var i FindAgentsReferencingMCPServerRefRow
		if err := rows.Scan(&i.OwnerUserID, &i.AgentRef, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMCPServerByIDForOwner = `-- name: GetMCPServerByIDForOwner :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, health, immutable, created_at FROM mcp_servers WHERE id = $1 AND owner_user_id = $2
`

type GetMCPServerByIDForOwnerParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) GetMCPServerByIDForOwner(ctx context.Context, arg GetMCPServerByIDForOwnerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerByIDForOwner, arg.ID, arg.OwnerUserID)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Health,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPServerByRefVersionForOwner = `-- name: GetMCPServerByRefVersionForOwner :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, health, immutable, created_at FROM mcp_servers WHERE owner_user_id = $1 AND ref = $2 AND version = $3
`

type GetMCPServerByRefVersionForOwnerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
}

func (q *Queries) GetMCPServerByRefVersionForOwner(ctx context.Context, arg GetMCPServerByRefVersionForOwnerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerByRefVersionForOwner, arg.OwnerUserID, arg.Ref, arg.Version)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Health,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPServerLatestByRef = `-- name: GetMCPServerLatestByRef :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, health, immutable, created_at FROM mcp_servers WHERE owner_user_id = $1 AND ref = $2 ORDER BY created_at DESC LIMIT 1
`

type GetMCPServerLatestByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
}

func (q *Queries) GetMCPServerLatestByRef(ctx context.Context, arg GetMCPServerLatestByRefParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerLatestByRef, arg.OwnerUserID, arg.Ref)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Health,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPServerLatestStatusByRef = `-- name: GetMCPServerLatestStatusByRef :one
SELECT status FROM mcp_servers WHERE owner_user_id = $1 AND ref = $2 ORDER BY created_at DESC LIMIT 1
`

type GetMCPServerLatestStatusByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
}

func (q *Queries) GetMCPServerLatestStatusByRef(ctx context.Context, arg GetMCPServerLatestStatusByRefParams) (int16, error) {
	row := q.db.QueryRow(ctx, getMCPServerLatestStatusByRef, arg.OwnerUserID, arg.Ref)
	var status int16
	err := row.Scan(&status)
	return status, err
}

const listMCPServersForOwnerPage = `-- name: ListMCPServersForOwnerPage :many
SELECT id, owner_user_id, ref, version, config, display_meta, status, health, immutable, created_at FROM mcp_servers WHERE owner_user_id = $1 AND id > $2 ORDER BY id ASC LIMIT $3
`

type ListMCPServersForOwnerPageParams struct {
	OwnerUserID int64 `json:"owner_user_id"`
	ID          int64 `json:"id"`
	Limit       int32 `json:"limit"`
}

func (q *Queries) ListMCPServersForOwnerPage(ctx context.Context, arg ListMCPServersForOwnerPageParams) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServersForOwnerPage, arg.OwnerUserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Ref,
			&i.Version,
			&i.Config,
			&i.DisplayMeta,
			&i.Status,
			&i.Health,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMCPServerImmutable = `-- name: MarkMCPServerImmutable :exec
UPDATE mcp_servers SET immutable = true WHERE id = $1
`

func (q *Queries) MarkMCPServerImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMCPServerImmutable, id)
	return err
}

const setMCPServerDisplayMeta = `-- name: SetMCPServerDisplayMeta :exec
UPDATE mcp_servers SET display_meta = $2 WHERE id = $1
`

type SetMCPServerDisplayMetaParams struct {
	ID          int64  `json:"id"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) SetMCPServerDisplayMeta(ctx context.Context, arg SetMCPServerDisplayMetaParams) error {
	_, err := q.db.Exec(ctx, setMCPServerDisplayMeta, arg.ID, arg.DisplayMeta)
	return err
}

const setMCPServerStatusByID = `-- name: SetMCPServerStatusByID :exec
UPDATE mcp_servers SET status = $2 WHERE id = $1
`

type SetMCPServerStatusByIDParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetMCPServerStatusByID(ctx context.Context, arg SetMCPServerStatusByIDParams) error {
	_, err := q.db.Exec(ctx, setMCPServerStatusByID, arg.ID, arg.Status)
	return err
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers SET display_meta = $3, config = $4, status = $5
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, ref, version, config, display_meta, status, health, immutable, created_at
`

type UpdateMCPServerParams struct {
	ID          int64  `json:"id"`
	OwnerUserID int64  `json:"owner_user_id"`
	DisplayMeta []byte `json:"display_meta"`
	Config      []byte `json:"config"`
	Status      int16  `json:"status"`
}

func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMCPServer,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayMeta,
		arg.Config,
		arg.Status,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Health,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const updateMCPServerHealth = `-- name: UpdateMCPServerHealth :exec
UPDATE mcp_servers SET health = $2 WHERE id = $1
`

type UpdateMCPServerHealthParams struct {
	ID     int64  `json:"id"`
	Health string `json:"health"`
}

func (q *Queries) UpdateMCPServerHealth(ctx context.Context, arg UpdateMCPServerHealthParams) error {
	_, err := q.db.Exec(ctx, updateMCPServerHealth, arg.ID, arg.Health)
	return err
}
