// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: memories.sql

package store

import (
	"context"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (owner_user_id, ref, version, config, display_meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type CreateMemoryParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
	Config      []byte `json:"config"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.OwnerUserID,
		arg.Ref,
		arg.Version,
		arg.Config,
		arg.DisplayMeta,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getMemoryByIDForOwner = `-- name: GetMemoryByIDForOwner :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM memories WHERE id = $1 AND owner_user_id = $2
`

type GetMemoryByIDForOwnerParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) GetMemoryByIDForOwner(ctx context.Context, arg GetMemoryByIDForOwnerParams) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemoryByIDForOwner, arg.ID, arg.OwnerUserID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getNewestEnabledMemoryForOwner = `-- name: GetNewestEnabledMemoryForOwner :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM memories WHERE owner_user_id = $1 AND status = 1 ORDER BY created_at DESC LIMIT 1
`

// The run engine's "which memory store backs this owner's runs" lookup —
// newest-enabled-wins, the same rule postgres.ProviderKeyStore already
// applies to provider credentials.
func (q *Queries) GetNewestEnabledMemoryForOwner(ctx context.Context, ownerUserID int64) (Memory, error) {
	row := q.db.QueryRow(ctx, getNewestEnabledMemoryForOwner, ownerUserID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const listMemoriesForOwnerPage = `-- name: ListMemoriesForOwnerPage :many
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM memories WHERE owner_user_id = $1 AND id > $2 ORDER BY id ASC LIMIT $3
`

type ListMemoriesForOwnerPageParams struct {
	OwnerUserID int64 `json:"owner_user_id"`
	ID          int64 `json:"id"`
	Limit       int32 `json:"limit"`
}

func (q *Queries) ListMemoriesForOwnerPage(ctx context.Context, arg ListMemoriesForOwnerPageParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesForOwnerPage, arg.OwnerUserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Ref,
			&i.Version,
			&i.Config,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories SET display_meta = $3, config = $4, status = $5
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type UpdateMemoryParams struct {
	ID          int64  `json:"id"`
	OwnerUserID int64  `json:"owner_user_id"`
	DisplayMeta []byte `json:"display_meta"`
	Config      []byte `json:"config"`
	Status      int16  `json:"status"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, updateMemory,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayMeta,
		arg.Config,
		arg.Status,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}
