// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: memory_entries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMemoryEntry = `-- name: InsertMemoryEntry :one
INSERT INTO memory_entries (memory_id, owner_user_id, app_name, agent_user_id, session_id, author, content)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertMemoryEntryParams struct {
	MemoryID    int64  `json:"memory_id"`
	OwnerUserID int64  `json:"owner_user_id"`
	AppName     string `json:"app_name"`
	AgentUserID string `json:"agent_user_id"`
	SessionID   string `json:"session_id"`
	Author      string `json:"author"`
	Content     string `json:"content"`
}

func (q *Queries) InsertMemoryEntry(ctx context.Context, arg InsertMemoryEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMemoryEntry,
		arg.MemoryID,
		arg.OwnerUserID,
		arg.AppName,
		arg.AgentUserID,
		arg.SessionID,
		arg.Author,
		arg.Content,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const searchMemoryEntries = `-- name: SearchMemoryEntries :many
SELECT id, author, content, created_at
FROM memory_entries
WHERE memory_id = $1 AND owner_user_id = $2 AND app_name = $3 AND agent_user_id = $4
  AND content_tsv @@ plainto_tsquery('simple', $5)
ORDER BY ts_rank(content_tsv, plainto_tsquery('simple', $5)) DESC
LIMIT $6
`

type SearchMemoryEntriesParams struct {
	MemoryID       int64  `json:"memory_id"`
	OwnerUserID    int64  `json:"owner_user_id"`
	AppName        string `json:"app_name"`
	AgentUserID    string `json:"agent_user_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
}

type SearchMemoryEntriesRow struct {
	ID        int64              `json:"id"`
	Author    string             `json:"author"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchMemoryEntries(ctx context.Context, arg SearchMemoryEntriesParams) ([]SearchMemoryEntriesRow, error) {
	rows, err := q.db.Query(ctx, searchMemoryEntries,
		arg.MemoryID,
		arg.OwnerUserID,
		arg.AppName,
		arg.AgentUserID,
		arg.PlaintoTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMemoryEntriesRow{}
	for rows.Next() {
		var i SearchMemoryEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
