// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: model_catalog.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCatalogModel = `-- name: CreateCatalogModel :one
INSERT INTO catalog_models (provider_id, model, display_name, description, modality, featured)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, model, display_name, description, modality, featured, status, created_at
`

type CreateCatalogModelParams struct {
	ProviderID  int64  `json:"provider_id"`
	Model       string `json:"model"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	Modality    string `json:"modality"`
	Featured    bool   `json:"featured"`
}

func (q *Queries) CreateCatalogModel(ctx context.Context, arg CreateCatalogModelParams) (CatalogModel, error) {
	row := q.db.QueryRow(ctx, createCatalogModel,
		arg.ProviderID,
		arg.Model,
		arg.DisplayName,
		arg.Description,
		arg.Modality,
		arg.Featured,
	)
	var i CatalogModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.DisplayName,
		&i.Description,
		&i.Modality,
		&i.Featured,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createCatalogProvider = `-- name: CreateCatalogProvider :one
INSERT INTO catalog_providers (provider_key, display_name, icon, base_url)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_key, display_name, icon, base_url, status, created_at
`

type CreateCatalogProviderParams struct {
	ProviderKey string      `json:"provider_key"`
	DisplayName string      `json:"display_name"`
	Icon        pgtype.Text `json:"icon"`
	BaseUrl     pgtype.Text `json:"base_url"`
}

func (q *Queries) CreateCatalogProvider(ctx context.Context, arg CreateCatalogProviderParams) (CatalogProvider, error) {
	row := q.db.QueryRow(ctx, createCatalogProvider,
		arg.ProviderKey,
		arg.DisplayName,
		arg.Icon,
		arg.BaseUrl,
	)
	var i CatalogProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.DisplayName,
		&i.Icon,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCatalogModel = `-- name: DeleteCatalogModel :exec
DELETE FROM catalog_models WHERE id = $1
`

func (q *Queries) DeleteCatalogModel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCatalogModel, id)
	return err
}

const deleteCatalogProvider = `-- name: DeleteCatalogProvider :exec
DELETE FROM catalog_providers WHERE id = $1
`

func (q *Queries) DeleteCatalogProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCatalogProvider, id)
	return err
}

const getCatalogProvider = `-- name: GetCatalogProvider :one
SELECT id, provider_key, display_name, icon, base_url, status, created_at
FROM catalog_providers
WHERE id = $1
`

func (q *Queries) GetCatalogProvider(ctx context.Context, id int64) (CatalogProvider, error) {
	row := q.db.QueryRow(ctx, getCatalogProvider, id)
	var i CatalogProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.DisplayName,
		&i.Icon,
		&i.BaseUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCatalogModelsForProvider = `-- name: ListCatalogModelsForProvider :many
SELECT id, provider_id, model, display_name, description, modality, featured, status, created_at
FROM catalog_models
WHERE provider_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCatalogModelsForProvider(ctx context.Context, providerID int64) ([]CatalogModel, error) {
	rows, err := q.db.Query(ctx, listCatalogModelsForProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogModel{}
	for rows.Next() {
		var i CatalogModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.DisplayName,
			&i.Description,
			&i.Modality,
			&i.Featured,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogModelsPublic = `-- name: ListCatalogModelsPublic :many
SELECT
    cm.model, cm.display_name, cm.description, cm.modality, cm.featured,
    cp.provider_key, cp.display_name AS provider_display_name, cp.icon AS provider_icon
FROM catalog_models cm
JOIN catalog_providers cp ON cp.id = cm.provider_id
WHERE cm.status = 1 AND cp.status = 1
ORDER BY cp.created_at ASC, cm.created_at ASC
`

type ListCatalogModelsPublicRow struct {
	Model               string      `json:"model"`
	DisplayName         string      `json:"display_name"`
	Description         string      `json:"description"`
	Modality            string      `json:"modality"`
	Featured            bool        `json:"featured"`
	ProviderKey         string      `json:"provider_key"`
	ProviderDisplayName string      `json:"provider_display_name"`
	ProviderIcon        pgtype.Text `json:"provider_icon"`
}

// Joined read for 模型广场 (GET /model-catalog): only enabled models under
// enabled providers, newest provider first so a freshly configured provider
// surfaces near the top instead of at the bottom of an ORDER BY id.
func (q *Queries) ListCatalogModelsPublic(ctx context.Context) ([]ListCatalogModelsPublicRow, error) {
	rows, err := q.db.Query(ctx, listCatalogModelsPublic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogModelsPublicRow{}
	for rows.Next() {
		var i ListCatalogModelsPublicRow
		if err := rows.Scan(
			&i.Model,
			&i.DisplayName,
			&i.Description,
			&i.Modality,
			&i.Featured,
			&i.ProviderKey,
			&i.ProviderDisplayName,
			&i.ProviderIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogProviders = `-- name: ListCatalogProviders :many
SELECT id, provider_key, display_name, icon, base_url, status, created_at
FROM catalog_providers
ORDER BY created_at ASC
`

func (q *Queries) ListCatalogProviders(ctx context.Context) ([]CatalogProvider, error) {
	rows, err := q.db.Query(ctx, listCatalogProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProvider{}
	for rows.Next() {
		var i CatalogProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderKey,
			&i.DisplayName,
			&i.Icon,
			&i.BaseUrl,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCatalogModelStatus = `-- name: SetCatalogModelStatus :exec
UPDATE catalog_models SET status = $2 WHERE id = $1
`

type SetCatalogModelStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetCatalogModelStatus(ctx context.Context, arg SetCatalogModelStatusParams) error {
	_, err := q.db.Exec(ctx, setCatalogModelStatus, arg.ID, arg.Status)
	return err
}

const setCatalogProviderStatus = `-- name: SetCatalogProviderStatus :exec
UPDATE catalog_providers SET status = $2 WHERE id = $1
`

type SetCatalogProviderStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetCatalogProviderStatus(ctx context.Context, arg SetCatalogProviderStatusParams) error {
	_, err := q.db.Exec(ctx, setCatalogProviderStatus, arg.ID, arg.Status)
	return err
}
