// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_catalog.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCatalogModel = `-- name: CreateCatalogModel :one
INSERT INTO catalog_models (provider_id, model, display_name, description, modality, featured, params)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, model, display_name, description, modality, featured, status, created_at, params
`

type CreateCatalogModelParams struct {
	ProviderID  int64  `json:"provider_id"`
	Model       string `json:"model"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	Modality    string `json:"modality"`
	Featured    bool   `json:"featured"`
	Params      []byte `json:"params"`
}

// params 是模型级请求参数的取值（形状见渠道描述符的 request_params），
// 添加模型时经 modelcatalog.Service 按描述符校验后落库。
func (q *Queries) CreateCatalogModel(ctx context.Context, arg CreateCatalogModelParams) (CatalogModel, error) {
	row := q.db.QueryRow(ctx, createCatalogModel,
		arg.ProviderID,
		arg.Model,
		arg.DisplayName,
		arg.Description,
		arg.Modality,
		arg.Featured,
		arg.Params,
	)
	var i CatalogModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.DisplayName,
		&i.Description,
		&i.Modality,
		&i.Featured,
		&i.Status,
		&i.CreatedAt,
		&i.Params,
	)
	return i, err
}

const createCatalogProvider = `-- name: CreateCatalogProvider :one
INSERT INTO catalog_providers (provider_key, display_name, icon, base_url, template, descriptor)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_key, display_name, icon, base_url, template, status, created_at, (default_api_key_encrypted IS NOT NULL)::bool AS has_credential
`

type CreateCatalogProviderParams struct {
	ProviderKey string      `json:"provider_key"`
	DisplayName string      `json:"display_name"`
	Icon        pgtype.Text `json:"icon"`
	BaseUrl     pgtype.Text `json:"base_url"`
	Template    pgtype.Text `json:"template"`
	Descriptor  []byte      `json:"descriptor"`
}

type CreateCatalogProviderRow struct {
	ID            int64              `json:"id"`
	ProviderKey   string             `json:"provider_key"`
	DisplayName   string             `json:"display_name"`
	Icon          pgtype.Text        `json:"icon"`
	BaseUrl       pgtype.Text        `json:"base_url"`
	Template      pgtype.Text        `json:"template"`
	Status        int16              `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	HasCredential bool               `json:"has_credential"`
}

// descriptor 是渲染好的渠道描述符快照（见 internal/channeltemplates）。它
// 决定这个提供商实际怎么被调用；template 只记录"从哪个模板来的"，供界面
// 展示，不参与运行时。
func (q *Queries) CreateCatalogProvider(ctx context.Context, arg CreateCatalogProviderParams) (CreateCatalogProviderRow, error) {
	row := q.db.QueryRow(ctx, createCatalogProvider,
		arg.ProviderKey,
		arg.DisplayName,
		arg.Icon,
		arg.BaseUrl,
		arg.Template,
		arg.Descriptor,
	)
	var i CreateCatalogProviderRow
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.DisplayName,
		&i.Icon,
		&i.BaseUrl,
		&i.Template,
		&i.Status,
		&i.CreatedAt,
		&i.HasCredential,
	)
	return i, err
}

const deleteCatalogModel = `-- name: DeleteCatalogModel :exec
DELETE FROM catalog_models WHERE id = $1
`

func (q *Queries) DeleteCatalogModel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCatalogModel, id)
	return err
}

const deleteCatalogProvider = `-- name: DeleteCatalogProvider :exec
DELETE FROM catalog_providers WHERE id = $1
`

func (q *Queries) DeleteCatalogProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCatalogProvider, id)
	return err
}

const getCatalogModel = `-- name: GetCatalogModel :one
SELECT id, provider_id, model, display_name, description, modality, featured, status, created_at, params
FROM catalog_models
WHERE id = $1
`

func (q *Queries) GetCatalogModel(ctx context.Context, id int64) (CatalogModel, error) {
	row := q.db.QueryRow(ctx, getCatalogModel, id)
	var i CatalogModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.DisplayName,
		&i.Description,
		&i.Modality,
		&i.Featured,
		&i.Status,
		&i.CreatedAt,
		&i.Params,
	)
	return i, err
}

const getCatalogProvider = `-- name: GetCatalogProvider :one
SELECT id, provider_key, display_name, icon, base_url, template, descriptor, status, created_at, (default_api_key_encrypted IS NOT NULL)::bool AS has_credential
FROM catalog_providers
WHERE id = $1
`

type GetCatalogProviderRow struct {
	ID            int64              `json:"id"`
	ProviderKey   string             `json:"provider_key"`
	DisplayName   string             `json:"display_name"`
	Icon          pgtype.Text        `json:"icon"`
	BaseUrl       pgtype.Text        `json:"base_url"`
	Template      pgtype.Text        `json:"template"`
	Descriptor    []byte             `json:"descriptor"`
	Status        int16              `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	HasCredential bool               `json:"has_credential"`
}

// descriptor 一并取回：添加/编辑模型时要按快照里的 request_params 校验
// 管理员填的参数取值。
func (q *Queries) GetCatalogProvider(ctx context.Context, id int64) (GetCatalogProviderRow, error) {
	row := q.db.QueryRow(ctx, getCatalogProvider, id)
	var i GetCatalogProviderRow
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.DisplayName,
		&i.Icon,
		&i.BaseUrl,
		&i.Template,
		&i.Descriptor,
		&i.Status,
		&i.CreatedAt,
		&i.HasCredential,
	)
	return i, err
}

const listCatalogModelParams = `-- name: ListCatalogModelParams :many
SELECT cp.provider_key, cm.model, cm.params
FROM catalog_models cm
JOIN catalog_providers cp ON cp.id = cm.provider_id
WHERE cp.status = 1
ORDER BY cp.provider_key, cm.model
`

type ListCatalogModelParamsRow struct {
	ProviderKey string `json:"provider_key"`
	Model       string `json:"model"`
	Params      []byte `json:"params"`
}

// 网关注册表重建时一并取回每渠道每模型的请求参数（modelgateway.SetModelParams）。
// 停用提供商下的模型不出现，和渠道描述符（ListEnabledChannelDescriptors）
// 的口径保持一致：停用就该立刻调不通。
func (q *Queries) ListCatalogModelParams(ctx context.Context) ([]ListCatalogModelParamsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogModelParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogModelParamsRow{}
	for rows.Next() {
		var i ListCatalogModelParamsRow
		if err := rows.Scan(&i.ProviderKey, &i.Model, &i.Params); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogModelsForProvider = `-- name: ListCatalogModelsForProvider :many
SELECT id, provider_id, model, display_name, description, modality, featured, status, created_at, params
FROM catalog_models
WHERE provider_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCatalogModelsForProvider(ctx context.Context, providerID int64) ([]CatalogModel, error) {
	rows, err := q.db.Query(ctx, listCatalogModelsForProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogModel{}
	for rows.Next() {
		var i CatalogModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.DisplayName,
			&i.Description,
			&i.Modality,
			&i.Featured,
			&i.Status,
			&i.CreatedAt,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogModelsPublic = `-- name: ListCatalogModelsPublic :many
SELECT
    cm.model, cm.display_name, cm.description, cm.modality, cm.featured,
    cp.provider_key, cp.display_name AS provider_display_name, cp.icon AS provider_icon,
    cp.template AS provider_template
FROM catalog_models cm
JOIN catalog_providers cp ON cp.id = cm.provider_id
WHERE cm.status = 1 AND cp.status = 1
ORDER BY cp.created_at ASC, cm.created_at ASC
`

type ListCatalogModelsPublicRow struct {
	Model               string      `json:"model"`
	DisplayName         string      `json:"display_name"`
	Description         string      `json:"description"`
	Modality            string      `json:"modality"`
	Featured            bool        `json:"featured"`
	ProviderKey         string      `json:"provider_key"`
	ProviderDisplayName string      `json:"provider_display_name"`
	ProviderIcon        pgtype.Text `json:"provider_icon"`
	ProviderTemplate    pgtype.Text `json:"provider_template"`
}

// Joined read for 模型广场 (GET /model-catalog): only enabled models under
// enabled providers, newest provider first so a freshly configured provider
// surfaces near the top instead of at the bottom of an ORDER BY id.
func (q *Queries) ListCatalogModelsPublic(ctx context.Context) ([]ListCatalogModelsPublicRow, error) {
	rows, err := q.db.Query(ctx, listCatalogModelsPublic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogModelsPublicRow{}
	for rows.Next() {
		var i ListCatalogModelsPublicRow
		if err := rows.Scan(
			&i.Model,
			&i.DisplayName,
			&i.Description,
			&i.Modality,
			&i.Featured,
			&i.ProviderKey,
			&i.ProviderDisplayName,
			&i.ProviderIcon,
			&i.ProviderTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogProviderDefaultCredentials = `-- name: ListCatalogProviderDefaultCredentials :many
SELECT provider_key, base_url, default_api_key_encrypted
FROM catalog_providers
WHERE status = 1 AND default_api_key_encrypted IS NOT NULL
`

type ListCatalogProviderDefaultCredentialsRow struct {
	ProviderKey            string      `json:"provider_key"`
	BaseUrl                pgtype.Text `json:"base_url"`
	DefaultApiKeyEncrypted pgtype.Text `json:"default_api_key_encrypted"`
}

// Admin-set org-wide fallback credentials, for ProviderKeyStore.Keys to
// merge in when a user has no personal credential for that provider.
func (q *Queries) ListCatalogProviderDefaultCredentials(ctx context.Context) ([]ListCatalogProviderDefaultCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProviderDefaultCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProviderDefaultCredentialsRow{}
	for rows.Next() {
		var i ListCatalogProviderDefaultCredentialsRow
		if err := rows.Scan(&i.ProviderKey, &i.BaseUrl, &i.DefaultApiKeyEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogProviders = `-- name: ListCatalogProviders :many
SELECT id, provider_key, display_name, icon, base_url, template, descriptor, status, created_at, (default_api_key_encrypted IS NOT NULL)::bool AS has_credential
FROM catalog_providers
ORDER BY created_at ASC
`

type ListCatalogProvidersRow struct {
	ID            int64              `json:"id"`
	ProviderKey   string             `json:"provider_key"`
	DisplayName   string             `json:"display_name"`
	Icon          pgtype.Text        `json:"icon"`
	BaseUrl       pgtype.Text        `json:"base_url"`
	Template      pgtype.Text        `json:"template"`
	Descriptor    []byte             `json:"descriptor"`
	Status        int16              `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	HasCredential bool               `json:"has_credential"`
}

// descriptor 一并取回：管理端列表要从中解析 request_params 给添加模型表单用。
func (q *Queries) ListCatalogProviders(ctx context.Context) ([]ListCatalogProvidersRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProvidersRow{}
	for rows.Next() {
		var i ListCatalogProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderKey,
			&i.DisplayName,
			&i.Icon,
			&i.BaseUrl,
			&i.Template,
			&i.Descriptor,
			&i.Status,
			&i.CreatedAt,
			&i.HasCredential,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannelDescriptors = `-- name: ListEnabledChannelDescriptors :many
SELECT provider_key, descriptor
FROM catalog_providers
WHERE status = 1 AND descriptor IS NOT NULL
ORDER BY provider_key
`

type ListEnabledChannelDescriptorsRow struct {
	ProviderKey string `json:"provider_key"`
	Descriptor  []byte `json:"descriptor"`
}

// 进程启动和每次提供商增删改后，modelgateway 的渠道注册表从这里整体重
// 建。停用的提供商不出现——停用就该立刻调不通，而不是等下次重启。
func (q *Queries) ListEnabledChannelDescriptors(ctx context.Context) ([]ListEnabledChannelDescriptorsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledChannelDescriptors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledChannelDescriptorsRow{}
	for rows.Next() {
		var i ListEnabledChannelDescriptorsRow
		if err := rows.Scan(&i.ProviderKey, &i.Descriptor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCatalogModelStatus = `-- name: SetCatalogModelStatus :exec
UPDATE catalog_models SET status = $2 WHERE id = $1
`

type SetCatalogModelStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetCatalogModelStatus(ctx context.Context, arg SetCatalogModelStatusParams) error {
	_, err := q.db.Exec(ctx, setCatalogModelStatus, arg.ID, arg.Status)
	return err
}

const setCatalogProviderCredential = `-- name: SetCatalogProviderCredential :exec
UPDATE catalog_providers
SET base_url = $2,
    default_api_key_encrypted = COALESCE($3, default_api_key_encrypted)
WHERE id = $1
`

type SetCatalogProviderCredentialParams struct {
	ID           int64       `json:"id"`
	BaseUrl      pgtype.Text `json:"base_url"`
	EncryptedKey pgtype.Text `json:"encrypted_key"`
}

// encrypted_key is a nullable param: pass NULL to leave the stored key
// untouched (admin only changed base_url, left the api_key field blank in
// the edit dialog because it's already set), or an encrypted value to
// replace it.
func (q *Queries) SetCatalogProviderCredential(ctx context.Context, arg SetCatalogProviderCredentialParams) error {
	_, err := q.db.Exec(ctx, setCatalogProviderCredential, arg.ID, arg.BaseUrl, arg.EncryptedKey)
	return err
}

const setCatalogProviderStatus = `-- name: SetCatalogProviderStatus :exec
UPDATE catalog_providers SET status = $2 WHERE id = $1
`

type SetCatalogProviderStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetCatalogProviderStatus(ctx context.Context, arg SetCatalogProviderStatusParams) error {
	_, err := q.db.Exec(ctx, setCatalogProviderStatus, arg.ID, arg.Status)
	return err
}

const updateCatalogModelParams = `-- name: UpdateCatalogModelParams :exec
UPDATE catalog_models SET params = $2 WHERE id = $1
`

type UpdateCatalogModelParamsParams struct {
	ID     int64  `json:"id"`
	Params []byte `json:"params"`
}

// 编辑模型参数走独立语句：status 和 params 是两种不同的管理动作，合并成
// 一条可空字段的 UPDATE 反而要在调用侧区分"没传"和"清空"。
func (q *Queries) UpdateCatalogModelParams(ctx context.Context, arg UpdateCatalogModelParamsParams) error {
	_, err := q.db.Exec(ctx, updateCatalogModelParams, arg.ID, arg.Params)
	return err
}
