// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	AgentRef    string             `json:"agent_ref"`
	Version     string             `json:"version"`
	Definition  []byte             `json:"definition"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	Immutable   bool               `json:"immutable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    string             `json:"target_id"`
	Detail      []byte             `json:"detail"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Bundle struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	BundleRef   string             `json:"bundle_ref"`
	Version     string             `json:"version"`
	Definition  []byte             `json:"definition"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	Immutable   bool               `json:"immutable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BundleRun struct {
	ID                string             `json:"id"`
	BundleID          int64              `json:"bundle_id"`
	TriggeredBy       int64              `json:"triggered_by"`
	ViaListingID      pgtype.Int8        `json:"via_listing_id"`
	Status            string             `json:"status"`
	Error             pgtype.Text        `json:"error"`
	SharedState       []byte             `json:"shared_state"`
	TotalTokens       int64              `json:"total_tokens"`
	CostUsd           pgtype.Numeric     `json:"cost_usd"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
}

type BundleRunEvent struct {
	ID         int64              `json:"id"`
	RunID      string             `json:"run_id"`
	Type       string             `json:"type"`
	Node       pgtype.Text        `json:"node"`
	Payload    []byte             `json:"payload"`
	IsInternal bool               `json:"is_internal"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CatalogModel struct {
	ID          int64              `json:"id"`
	ProviderID  int64              `json:"provider_id"`
	Model       string             `json:"model"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	Modality    string             `json:"modality"`
	Featured    bool               `json:"featured"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CatalogProvider struct {
	ID          int64              `json:"id"`
	ProviderKey string             `json:"provider_key"`
	DisplayName string             `json:"display_name"`
	Icon        pgtype.Text        `json:"icon"`
	BaseUrl     pgtype.Text        `json:"base_url"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type HumanGate struct {
	ID             int64              `json:"id"`
	RunID          string             `json:"run_id"`
	Node           string             `json:"node"`
	Status         string             `json:"status"`
	TimeoutSeconds pgtype.Int4        `json:"timeout_seconds"`
	OnTimeout      string             `json:"on_timeout"`
	ApproverRoles  []byte             `json:"approver_roles"`
	ResolvedBy     pgtype.Int8        `json:"resolved_by"`
	Comment        pgtype.Text        `json:"comment"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

type IdempotencyKey struct {
	Key          string             `json:"key"`
	OwnerUserID  int64              `json:"owner_user_id"`
	StatusCode   int32              `json:"status_code"`
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type KnowledgeBasis struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Ref         string             `json:"ref"`
	Version     string             `json:"version"`
	Config      []byte             `json:"config"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	Immutable   bool               `json:"immutable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MarketplaceListing struct {
	ID              int64              `json:"id"`
	AuthorUserID    int64              `json:"author_user_id"`
	ResourceType    string             `json:"resource_type"`
	ResourceID      int64              `json:"resource_id"`
	ListingRef      string             `json:"listing_ref"`
	Version         string             `json:"version"`
	Visibility      string             `json:"visibility"`
	Changelog       pgtype.Text        `json:"changelog"`
	Distribution    int16              `json:"distribution"`
	SubscriberCount int32              `json:"subscriber_count"`
	RunCount        int64              `json:"run_count"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type McpServer struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Ref         string             `json:"ref"`
	Version     string             `json:"version"`
	Config      []byte             `json:"config"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	Health      string             `json:"health"`
	Immutable   bool               `json:"immutable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Memory struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Ref         string             `json:"ref"`
	Version     string             `json:"version"`
	Config      []byte             `json:"config"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	Immutable   bool               `json:"immutable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MemoryEntry struct {
	ID          int64              `json:"id"`
	MemoryID    int64              `json:"memory_id"`
	OwnerUserID int64              `json:"owner_user_id"`
	AppName     string             `json:"app_name"`
	AgentUserID string             `json:"agent_user_id"`
	SessionID   string             `json:"session_id"`
	Author      string             `json:"author"`
	Content     string             `json:"content"`
	ContentTsv  interface{}        `json:"content_tsv"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ModelProvider struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Provider    string             `json:"provider"`
	Credentials []byte             `json:"credentials"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	BaseUrl     pgtype.Text        `json:"base_url"`
}

type Permission struct {
	ID            int64              `json:"id"`
	PermissionKey string             `json:"permission_key"`
	Name          string             `json:"name"`
	Module        string             `json:"module"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID             int64              `json:"id"`
	ListingID      int64              `json:"listing_id"`
	ReporterUserID int64              `json:"reporter_user_id"`
	Reason         string             `json:"reason"`
	Status         string             `json:"status"`
	Resolution     pgtype.Text        `json:"resolution"`
	ResolvedBy     pgtype.Int8        `json:"resolved_by"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	RoleKey     string             `json:"role_key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type Skill struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Ref         string             `json:"ref"`
	Version     string             `json:"version"`
	Config      []byte             `json:"config"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	Immutable   bool               `json:"immutable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID           int64              `json:"id"`
	SubscriberID int64              `json:"subscriber_id"`
	ListingID    int64              `json:"listing_id"`
	LocalAlias   pgtype.Text        `json:"local_alias"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Tool struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Ref         string             `json:"ref"`
	Version     string             `json:"version"`
	Config      []byte             `json:"config"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	Immutable   bool               `json:"immutable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsAdmin      bool               `json:"is_admin"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}
