// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: model_providers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModelProvider = `-- name: CreateModelProvider :one
INSERT INTO model_providers (owner_user_id, provider, credentials)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, provider, status, created_at
`

type CreateModelProviderParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Provider    string `json:"provider"`
	Credentials []byte `json:"credentials"`
}

type CreateModelProviderRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Provider    string             `json:"provider"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateModelProvider(ctx context.Context, arg CreateModelProviderParams) (CreateModelProviderRow, error) {
	row := q.db.QueryRow(ctx, createModelProvider, arg.OwnerUserID, arg.Provider, arg.Credentials)
	var i CreateModelProviderRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Provider,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getModelProviderCredentials = `-- name: GetModelProviderCredentials :one
SELECT credentials FROM model_providers WHERE id = $1 AND owner_user_id = $2
`

type GetModelProviderCredentialsParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) GetModelProviderCredentials(ctx context.Context, arg GetModelProviderCredentialsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getModelProviderCredentials, arg.ID, arg.OwnerUserID)
	var credentials []byte
	err := row.Scan(&credentials)
	return credentials, err
}

const listModelProvidersForOwner = `-- name: ListModelProvidersForOwner :many
SELECT id, owner_user_id, provider, status, created_at
FROM model_providers
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

type ListModelProvidersForOwnerRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Provider    string             `json:"provider"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListModelProvidersForOwner(ctx context.Context, ownerUserID int64) ([]ListModelProvidersForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listModelProvidersForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelProvidersForOwnerRow{}
	for rows.Next() {
		var i ListModelProvidersForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Provider,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setModelProviderStatus = `-- name: SetModelProviderStatus :exec
UPDATE model_providers SET status = $2 WHERE id = $1
`

type SetModelProviderStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetModelProviderStatus(ctx context.Context, arg SetModelProviderStatusParams) error {
	_, err := q.db.Exec(ctx, setModelProviderStatus, arg.ID, arg.Status)
	return err
}
