// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plugins.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlugin = `-- name: CreatePlugin :one
INSERT INTO plugins (plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at
`

type CreatePluginParams struct {
	PluginID     string      `json:"plugin_id"`
	Version      string      `json:"version"`
	Manifest     []byte      `json:"manifest"`
	OssPrefix    string      `json:"oss_prefix"`
	PublisherID  pgtype.Int8 `json:"publisher_id"`
	Signature    string      `json:"signature"`
	Visibility   string      `json:"visibility"`
	ReviewStatus string      `json:"review_status"`
}

func (q *Queries) CreatePlugin(ctx context.Context, arg CreatePluginParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, createPlugin,
		arg.PluginID,
		arg.Version,
		arg.Manifest,
		arg.OssPrefix,
		arg.PublisherID,
		arg.Signature,
		arg.Visibility,
		arg.ReviewStatus,
	)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Version,
		&i.Manifest,
		&i.OssPrefix,
		&i.PublisherID,
		&i.Signature,
		&i.Visibility,
		&i.ReviewStatus,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPluginInstallation = `-- name: CreatePluginInstallation :one
INSERT INTO plugin_installations (owner_user_id, plugin_id, version, resolution, config, granted)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_user_id, plugin_id, version, resolution, config, granted, status, created_at
`

type CreatePluginInstallationParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	PluginID    string `json:"plugin_id"`
	Version     string `json:"version"`
	Resolution  string `json:"resolution"`
	Config      []byte `json:"config"`
	Granted     []byte `json:"granted"`
}

func (q *Queries) CreatePluginInstallation(ctx context.Context, arg CreatePluginInstallationParams) (PluginInstallation, error) {
	row := q.db.QueryRow(ctx, createPluginInstallation,
		arg.OwnerUserID,
		arg.PluginID,
		arg.Version,
		arg.Resolution,
		arg.Config,
		arg.Granted,
	)
	var i PluginInstallation
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PluginID,
		&i.Version,
		&i.Resolution,
		&i.Config,
		&i.Granted,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deletePluginInstallation = `-- name: DeletePluginInstallation :exec
DELETE FROM plugin_installations WHERE owner_user_id = $1 AND plugin_id = $2
`

type DeletePluginInstallationParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	PluginID    string `json:"plugin_id"`
}

func (q *Queries) DeletePluginInstallation(ctx context.Context, arg DeletePluginInstallationParams) error {
	_, err := q.db.Exec(ctx, deletePluginInstallation, arg.OwnerUserID, arg.PluginID)
	return err
}

const getLatestPluginVersion = `-- name: GetLatestPluginVersion :one
SELECT id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at FROM plugins WHERE plugin_id = $1 AND status = 1 ORDER BY created_at DESC LIMIT 1
`

// 未指定版本时用的"最新" — 按 created_at 取最近发布的一个版本，
// 和 GetBundleLatestByRef 的既有约定一致。
func (q *Queries) GetLatestPluginVersion(ctx context.Context, pluginID string) (Plugin, error) {
	row := q.db.QueryRow(ctx, getLatestPluginVersion, pluginID)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Version,
		&i.Manifest,
		&i.OssPrefix,
		&i.PublisherID,
		&i.Signature,
		&i.Visibility,
		&i.ReviewStatus,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPluginInstallation = `-- name: GetPluginInstallation :one
SELECT id, owner_user_id, plugin_id, version, resolution, config, granted, status, created_at FROM plugin_installations WHERE owner_user_id = $1 AND plugin_id = $2
`

type GetPluginInstallationParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	PluginID    string `json:"plugin_id"`
}

func (q *Queries) GetPluginInstallation(ctx context.Context, arg GetPluginInstallationParams) (PluginInstallation, error) {
	row := q.db.QueryRow(ctx, getPluginInstallation, arg.OwnerUserID, arg.PluginID)
	var i PluginInstallation
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PluginID,
		&i.Version,
		&i.Resolution,
		&i.Config,
		&i.Granted,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPluginVersion = `-- name: GetPluginVersion :one
SELECT id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at FROM plugins WHERE plugin_id = $1 AND version = $2
`

type GetPluginVersionParams struct {
	PluginID string `json:"plugin_id"`
	Version  string `json:"version"`
}

func (q *Queries) GetPluginVersion(ctx context.Context, arg GetPluginVersionParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, getPluginVersion, arg.PluginID, arg.Version)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Version,
		&i.Manifest,
		&i.OssPrefix,
		&i.PublisherID,
		&i.Signature,
		&i.Visibility,
		&i.ReviewStatus,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPublisherKey = `-- name: GetPublisherKey :one
SELECT user_id, public_key, created_at FROM plugin_publisher_keys WHERE user_id = $1
`

func (q *Queries) GetPublisherKey(ctx context.Context, userID int64) (PluginPublisherKey, error) {
	row := q.db.QueryRow(ctx, getPublisherKey, userID)
	var i PluginPublisherKey
	err := row.Scan(&i.UserID, &i.PublicKey, &i.CreatedAt)
	return i, err
}

const listMarketPlugins = `-- name: ListMarketPlugins :many
SELECT DISTINCT ON (plugin_id) id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at
FROM plugins
WHERE visibility = 'public' AND review_status = 'passed' AND status = 1
ORDER BY plugin_id, created_at DESC
`

// 组件广场"插件" Tab 用的市场列表：只列公开且审核通过的，每个 plugin_id 一行（最新版本）。
func (q *Queries) ListMarketPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.Query(ctx, listMarketPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Version,
			&i.Manifest,
			&i.OssPrefix,
			&i.PublisherID,
			&i.Signature,
			&i.Visibility,
			&i.ReviewStatus,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReviewPlugins = `-- name: ListPendingReviewPlugins :many
SELECT id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at FROM plugins WHERE review_status = 'pending' AND visibility = 'public' ORDER BY created_at ASC
`

func (q *Queries) ListPendingReviewPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.Query(ctx, listPendingReviewPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Version,
			&i.Manifest,
			&i.OssPrefix,
			&i.PublisherID,
			&i.Signature,
			&i.Visibility,
			&i.ReviewStatus,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginInstallations = `-- name: ListPluginInstallations :many
SELECT id, owner_user_id, plugin_id, version, resolution, config, granted, status, created_at FROM plugin_installations WHERE owner_user_id = $1 AND status = 1 ORDER BY plugin_id
`

func (q *Queries) ListPluginInstallations(ctx context.Context, ownerUserID int64) ([]PluginInstallation, error) {
	rows, err := q.db.Query(ctx, listPluginInstallations, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginInstallation{}
	for rows.Next() {
		var i PluginInstallation
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.PluginID,
			&i.Version,
			&i.Resolution,
			&i.Config,
			&i.Granted,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginVersions = `-- name: ListPluginVersions :many
SELECT id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at FROM plugins WHERE plugin_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPluginVersions(ctx context.Context, pluginID string) ([]Plugin, error) {
	rows, err := q.db.Query(ctx, listPluginVersions, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Version,
			&i.Manifest,
			&i.OssPrefix,
			&i.PublisherID,
			&i.Signature,
			&i.Visibility,
			&i.ReviewStatus,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsByPublisher = `-- name: ListPluginsByPublisher :many
SELECT id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at FROM plugins WHERE publisher_id = $1 ORDER BY plugin_id, created_at DESC
`

func (q *Queries) ListPluginsByPublisher(ctx context.Context, publisherID pgtype.Int8) ([]Plugin, error) {
	rows, err := q.db.Query(ctx, listPluginsByPublisher, publisherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Version,
			&i.Manifest,
			&i.OssPrefix,
			&i.PublisherID,
			&i.Signature,
			&i.Visibility,
			&i.ReviewStatus,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPluginReviewStatus = `-- name: SetPluginReviewStatus :one
UPDATE plugins SET review_status = $2 WHERE id = $1 RETURNING id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at
`

type SetPluginReviewStatusParams struct {
	ID           int64  `json:"id"`
	ReviewStatus string `json:"review_status"`
}

func (q *Queries) SetPluginReviewStatus(ctx context.Context, arg SetPluginReviewStatusParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, setPluginReviewStatus, arg.ID, arg.ReviewStatus)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Version,
		&i.Manifest,
		&i.OssPrefix,
		&i.PublisherID,
		&i.Signature,
		&i.Visibility,
		&i.ReviewStatus,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setPluginVisibility = `-- name: SetPluginVisibility :one
UPDATE plugins SET visibility = $2 WHERE id = $1 RETURNING id, plugin_id, version, manifest, oss_prefix, publisher_id, signature, visibility, review_status, status, created_at
`

type SetPluginVisibilityParams struct {
	ID         int64  `json:"id"`
	Visibility string `json:"visibility"`
}

func (q *Queries) SetPluginVisibility(ctx context.Context, arg SetPluginVisibilityParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, setPluginVisibility, arg.ID, arg.Visibility)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Version,
		&i.Manifest,
		&i.OssPrefix,
		&i.PublisherID,
		&i.Signature,
		&i.Visibility,
		&i.ReviewStatus,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updatePluginInstallation = `-- name: UpdatePluginInstallation :one
UPDATE plugin_installations
SET version = $3, resolution = $4, config = $5, granted = $6
WHERE owner_user_id = $1 AND plugin_id = $2
RETURNING id, owner_user_id, plugin_id, version, resolution, config, granted, status, created_at
`

type UpdatePluginInstallationParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	PluginID    string `json:"plugin_id"`
	Version     string `json:"version"`
	Resolution  string `json:"resolution"`
	Config      []byte `json:"config"`
	Granted     []byte `json:"granted"`
}

func (q *Queries) UpdatePluginInstallation(ctx context.Context, arg UpdatePluginInstallationParams) (PluginInstallation, error) {
	row := q.db.QueryRow(ctx, updatePluginInstallation,
		arg.OwnerUserID,
		arg.PluginID,
		arg.Version,
		arg.Resolution,
		arg.Config,
		arg.Granted,
	)
	var i PluginInstallation
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PluginID,
		&i.Version,
		&i.Resolution,
		&i.Config,
		&i.Granted,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPublisherKey = `-- name: UpsertPublisherKey :one
INSERT INTO plugin_publisher_keys (user_id, public_key)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET public_key = EXCLUDED.public_key
RETURNING user_id, public_key, created_at
`

type UpsertPublisherKeyParams struct {
	UserID    int64  `json:"user_id"`
	PublicKey []byte `json:"public_key"`
}

func (q *Queries) UpsertPublisherKey(ctx context.Context, arg UpsertPublisherKeyParams) (PluginPublisherKey, error) {
	row := q.db.QueryRow(ctx, upsertPublisherKey, arg.UserID, arg.PublicKey)
	var i PluginPublisherKey
	err := row.Scan(&i.UserID, &i.PublicKey, &i.CreatedAt)
	return i, err
}
