// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugin_kv.sql

package store

import (
	"context"
)

const getPluginKV = `-- name: GetPluginKV :one
SELECT plugin_id, owner_user_id, key, value, updated_at FROM plugin_kv WHERE plugin_id = $1 AND owner_user_id = $2 AND key = $3
`

type GetPluginKVParams struct {
	PluginID    string `json:"plugin_id"`
	OwnerUserID int64  `json:"owner_user_id"`
	Key         string `json:"key"`
}

func (q *Queries) GetPluginKV(ctx context.Context, arg GetPluginKVParams) (PluginKv, error) {
	row := q.db.QueryRow(ctx, getPluginKV, arg.PluginID, arg.OwnerUserID, arg.Key)
	var i PluginKv
	err := row.Scan(
		&i.PluginID,
		&i.OwnerUserID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPluginKV = `-- name: UpsertPluginKV :one
INSERT INTO plugin_kv (plugin_id, owner_user_id, key, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (plugin_id, owner_user_id, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING plugin_id, owner_user_id, key, value, updated_at
`

type UpsertPluginKVParams struct {
	PluginID    string `json:"plugin_id"`
	OwnerUserID int64  `json:"owner_user_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

func (q *Queries) UpsertPluginKV(ctx context.Context, arg UpsertPluginKVParams) (PluginKv, error) {
	row := q.db.QueryRow(ctx, upsertPluginKV,
		arg.PluginID,
		arg.OwnerUserID,
		arg.Key,
		arg.Value,
	)
	var i PluginKv
	err := row.Scan(
		&i.PluginID,
		&i.OwnerUserID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}
