// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveSubscribedListingsForAgentRef(ctx context.Context, arg CountActiveSubscribedListingsForAgentRefParams) (int64, error)
	CountActiveSubscribedListingsForBundleRef(ctx context.Context, arg CountActiveSubscribedListingsForBundleRefParams) (int64, error)
	CountAdminUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error)
	// Owner-view and subscriber-view queries are kept physically separate so the
	// subscriber path can never accidentally SELECT `definition` (see
	// docs/架构设计文档_AI-Agent平台_V1.md 五、"黑盒发布的实现要点").
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBundle(ctx context.Context, arg CreateBundleParams) (Bundle, error)
	CreateBundleRun(ctx context.Context, arg CreateBundleRunParams) (BundleRun, error)
	CreateCatalogModel(ctx context.Context, arg CreateCatalogModelParams) (CatalogModel, error)
	CreateCatalogProvider(ctx context.Context, arg CreateCatalogProviderParams) (CatalogProvider, error)
	CreateHumanGate(ctx context.Context, arg CreateHumanGateParams) (HumanGate, error)
	CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) (KnowledgeBasis, error)
	// Dependency closure (spec-08) is always owner-scoped: a Bundle/Agent only
	// ever references resources in the SAME owner's space by ref, so every
	// "is X published" check below joins through the resource table's
	// owner_user_id rather than trusting listing_ref alone (listing_ref is
	// globally unique across all authors, like an npm package name — see
	// migration 0003's UNIQUE(listing_ref, version)).
	//
	// distribution: 1 distributing / 2 stopped / 3 delisted (admin takedown).
	// "published" for dependency-satisfaction purposes means distribution != 3
	// — a stopped listing still satisfies dependents (spec-08 "无影响，继续可用"),
	// only an admin delisting actually removes it from the graph.
	CreateListing(ctx context.Context, arg CreateListingParams) (MarketplaceListing, error)
	CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateModelProvider(ctx context.Context, arg CreateModelProviderParams) (CreateModelProviderRow, error)
	CreatePlugin(ctx context.Context, arg CreatePluginParams) (Plugin, error)
	CreatePluginInstallation(ctx context.Context, arg CreatePluginInstallationParams) (PluginInstallation, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateSkillFile(ctx context.Context, arg CreateSkillFileParams) error
	// ── Subscriptions ────────────────────────────────────────────────────
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementListingSubscriberCount(ctx context.Context, id int64) error
	DeleteAgent(ctx context.Context, id int64) error
	DeleteAgentsByRef(ctx context.Context, arg DeleteAgentsByRefParams) error
	DeleteBundle(ctx context.Context, id int64) error
	DeleteBundlesByRef(ctx context.Context, arg DeleteBundlesByRefParams) error
	DeleteCatalogModel(ctx context.Context, id int64) error
	DeleteCatalogProvider(ctx context.Context, id int64) error
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	DeletePluginInstallation(ctx context.Context, arg DeletePluginInstallationParams) (int64, error)
	DeleteRole(ctx context.Context, id int64) error
	DeleteRolePermissions(ctx context.Context, roleID int64) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	DeleteUserRoles(ctx context.Context, userID int64) error
	// Knowledge bases surface to an Agent as an entry in capabilities.tools
	// (the DSL has no separate knowledge_base array) — same lookup as tools.
	FindAgentsReferencingKnowledgeBaseRef(ctx context.Context, arg FindAgentsReferencingKnowledgeBaseRefParams) ([]FindAgentsReferencingKnowledgeBaseRefRow, error)
	FindAgentsReferencingMCPServerRef(ctx context.Context, arg FindAgentsReferencingMCPServerRefParams) ([]FindAgentsReferencingMCPServerRefRow, error)
	FindAgentsReferencingSkillRef(ctx context.Context, arg FindAgentsReferencingSkillRefParams) ([]FindAgentsReferencingSkillRefRow, error)
	FindAgentsReferencingToolRef(ctx context.Context, arg FindAgentsReferencingToolRefParams) ([]FindAgentsReferencingToolRefRow, error)
	FindBundlesReferencingAgentRef(ctx context.Context, arg FindBundlesReferencingAgentRefParams) ([]FindBundlesReferencingAgentRefRow, error)
	FindPublishedAgentsReferencingSkillRef(ctx context.Context, arg FindPublishedAgentsReferencingSkillRefParams) ([]FindPublishedAgentsReferencingSkillRefRow, error)
	FindPublishedAgentsReferencingToolRef(ctx context.Context, arg FindPublishedAgentsReferencingToolRefParams) ([]FindPublishedAgentsReferencingToolRefRow, error)
	// ── Reverse-dependency checks (unpublish-time, 70007) ───────────────────
	// Which of the owner's *currently published* Bundles reference this Agent
	// ref (any version — used to block unpublishing the Agent entirely; the
	// exact-version variant used at publish-time doesn't apply here since any
	// version of the agent being gone would break the dependent Bundle).
	FindPublishedBundlesReferencingAgentRef(ctx context.Context, arg FindPublishedBundlesReferencingAgentRefParams) ([]FindPublishedBundlesReferencingAgentRefRow, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	// Constraints summary is extracted field-by-field via JSONB path operators
	// so the full `definition` blob never has to leave Postgres — the same
	// "DAO 层强制隔离" principle as the display-only list queries above, just
	// applied to a handful of numeric/string fields instead of a whole column.
	// Every field of Agent.constraints is optional in the DSL (schema defaults
	// apply at runtime), so a raw ::int/::text cast on a possibly-absent key
	// would scan a Postgres NULL into a non-nullable Go int32/string and
	// panic. COALESCE to the DSL's own documented defaults (max_tool_calls 20,
	// timeout_seconds 300) keeps the value meaningful; estimated_tokens_range
	// has no default, so it's coalesced to '' and the API layer treats an
	// empty string as "not disclosed" rather than guessing a range.
	GetAgentConstraintsSummaryByListingID(ctx context.Context, id int64) (GetAgentConstraintsSummaryByListingIDRow, error)
	GetAgentDisplayForSubscriber(ctx context.Context, id int64) (GetAgentDisplayForSubscriberRow, error)
	GetAgentForOwner(ctx context.Context, arg GetAgentForOwnerParams) (Agent, error)
	GetAgentLatestByRef(ctx context.Context, arg GetAgentLatestByRefParams) (Agent, error)
	GetAgentListingDisplayByListingID(ctx context.Context, id int64) (GetAgentListingDisplayByListingIDRow, error)
	// ── Dependency-satisfaction checks (publish-time closure walk) ──────────
	GetAgentListingForOwnerByRefVersion(ctx context.Context, arg GetAgentListingForOwnerByRefVersionParams) (MarketplaceListing, error)
	// Internal use only (spec-11 run engine): fetches the full row, including
	// `definition`, by raw id regardless of owner — a run compiles a Bundle
	// whose owner may not be the requesting subscriber. Never exposed
	// directly to an HTTP response; the blackbox boundary is enforced by the
	// handler layer, not by this query.
	GetBundleByID(ctx context.Context, id int64) (Bundle, error)
	GetBundleConstraintsSummaryByListingID(ctx context.Context, id int64) (GetBundleConstraintsSummaryByListingIDRow, error)
	GetBundleDisplayForSubscriber(ctx context.Context, id int64) (GetBundleDisplayForSubscriberRow, error)
	GetBundleForOwner(ctx context.Context, arg GetBundleForOwnerParams) (Bundle, error)
	// "Latest enabled version" per api/openapi.yaml's createRun: "bundle_version
	// 省略则使用最新启用版本".
	GetBundleLatestByRef(ctx context.Context, arg GetBundleLatestByRefParams) (Bundle, error)
	GetBundleListingDisplayByListingID(ctx context.Context, id int64) (GetBundleListingDisplayByListingIDRow, error)
	GetBundleListingForOwnerByRefVersion(ctx context.Context, arg GetBundleListingForOwnerByRefVersionParams) (MarketplaceListing, error)
	GetBundleRun(ctx context.Context, id string) (BundleRun, error)
	GetCatalogProvider(ctx context.Context, id int64) (CatalogProvider, error)
	GetHumanGateByID(ctx context.Context, id int64) (HumanGate, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetKnowledgeBaseByIDForOwner(ctx context.Context, arg GetKnowledgeBaseByIDForOwnerParams) (KnowledgeBasis, error)
	GetKnowledgeBaseLatestByRef(ctx context.Context, arg GetKnowledgeBaseLatestByRefParams) (KnowledgeBasis, error)
	GetKnowledgeBaseLatestStatusByRef(ctx context.Context, arg GetKnowledgeBaseLatestStatusByRefParams) (int16, error)
	// 未指定版本时用的"最新" — 按 created_at 取最近发布的一个版本，
	// 和 GetBundleLatestByRef 的既有约定一致。
	GetLatestPluginVersion(ctx context.Context, pluginID string) (Plugin, error)
	GetListingByID(ctx context.Context, id int64) (MarketplaceListing, error)
	GetListingByListingRefAndVersion(ctx context.Context, arg GetListingByListingRefAndVersionParams) (MarketplaceListing, error)
	GetListingByListingRefLatestPublished(ctx context.Context, listingRef string) (MarketplaceListing, error)
	GetMCPServerByIDForOwner(ctx context.Context, arg GetMCPServerByIDForOwnerParams) (McpServer, error)
	GetMCPServerByRefVersionForOwner(ctx context.Context, arg GetMCPServerByRefVersionForOwnerParams) (McpServer, error)
	GetMCPServerLatestByRef(ctx context.Context, arg GetMCPServerLatestByRefParams) (McpServer, error)
	GetMCPServerLatestStatusByRef(ctx context.Context, arg GetMCPServerLatestStatusByRefParams) (int16, error)
	GetMCPServerListingDisplayByListingID(ctx context.Context, id int64) (GetMCPServerListingDisplayByListingIDRow, error)
	GetMCPServerListingForOwnerByRef(ctx context.Context, arg GetMCPServerListingForOwnerByRefParams) (MarketplaceListing, error)
	GetMemoryByIDForOwner(ctx context.Context, arg GetMemoryByIDForOwnerParams) (Memory, error)
	GetModelProviderCredentials(ctx context.Context, arg GetModelProviderCredentialsParams) ([]byte, error)
	// The run engine's "which memory store backs this owner's runs" lookup —
	// newest-enabled-wins, the same rule postgres.ProviderKeyStore already
	// applies to provider credentials.
	GetNewestEnabledMemoryForOwner(ctx context.Context, ownerUserID int64) (Memory, error)
	// A node can gate more than once across a Bundle's lifetime (e.g. inside a
	// self-loop retry), so this always resolves to the most recent occurrence
	// for that run+node — the one actually blocking right now.
	GetPendingHumanGateForRunNode(ctx context.Context, arg GetPendingHumanGateForRunNodeParams) (HumanGate, error)
	GetPermissionIDsByKeys(ctx context.Context, keys []string) ([]int64, error)
	GetPluginInstallation(ctx context.Context, arg GetPluginInstallationParams) (PluginInstallation, error)
	GetPluginVersion(ctx context.Context, arg GetPluginVersionParams) (Plugin, error)
	GetPublisherKey(ctx context.Context, userID int64) (PluginPublisherKey, error)
	GetReportByID(ctx context.Context, id int64) (Report, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetSkillByIDForOwner(ctx context.Context, arg GetSkillByIDForOwnerParams) (Skill, error)
	GetSkillByRefVersionForOwner(ctx context.Context, arg GetSkillByRefVersionForOwnerParams) (Skill, error)
	GetSkillLatestByRef(ctx context.Context, arg GetSkillLatestByRefParams) (Skill, error)
	GetSkillLatestStatusByRef(ctx context.Context, arg GetSkillLatestStatusByRefParams) (int16, error)
	GetSkillListingDisplayByListingID(ctx context.Context, id int64) (GetSkillListingDisplayByListingIDRow, error)
	// Skill/MCP refs in an Agent's capabilities are not version-pinned in the
	// DSL (unlike Bundle.agents[].version), so satisfaction only requires SOME
	// published version of the ref to exist — the most recently published one.
	GetSkillListingForOwnerByRef(ctx context.Context, arg GetSkillListingForOwnerByRefParams) (MarketplaceListing, error)
	GetSubscriptionByIDForSubscriber(ctx context.Context, arg GetSubscriptionByIDForSubscriberParams) (Subscription, error)
	GetSubscriptionByListingAndSubscriber(ctx context.Context, arg GetSubscriptionByListingAndSubscriberParams) (Subscription, error)
	// Enforces "一个 ref 只保留一个生效订阅" (spec-08 已决事项): a subscriber can
	// have at most one active subscription per listing_ref, regardless of
	// which version it's bound to — switching versions is an explicit upgrade,
	// never a second subscribe.
	GetSubscriptionForSubscriberByListingRef(ctx context.Context, arg GetSubscriptionForSubscriberByListingRefParams) (Subscription, error)
	GetToolByIDForOwner(ctx context.Context, arg GetToolByIDForOwnerParams) (Tool, error)
	// Used by the run engine (spec-10/11) to build a real tool.Tool from the
	// resource's config — capabilities.tools[] refs aren't version-pinned, so
	// this is always "whatever's currently live", same as the status lookup.
	GetToolLatestByRef(ctx context.Context, arg GetToolLatestByRefParams) (Tool, error)
	GetToolLatestStatusByRef(ctx context.Context, arg GetToolLatestStatusByRefParams) (int16, error)
	GetUsageBreakdownByBundleForUser(ctx context.Context, arg GetUsageBreakdownByBundleForUserParams) ([]GetUsageBreakdownByBundleForUserRow, error)
	GetUsageBreakdownByDayForUser(ctx context.Context, arg GetUsageBreakdownByDayForUserParams) ([]GetUsageBreakdownByDayForUserRow, error)
	// ── Usage & cost (/usage/me) ─────────────────────────────────────────
	// Usage is always scoped to the person who triggered the run — spec-09:
	// "黑盒资源的用量算订阅者的" — a subscriber running someone else's
	// published Bundle is the one whose usage this counts against, which
	// `triggered_by` already captures regardless of `via_listing_id`.
	GetUsageSummaryForUser(ctx context.Context, arg GetUsageSummaryForUserParams) (GetUsageSummaryForUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	IncrementListingSubscriberCount(ctx context.Context, id int64) error
	InsertBundleRunEvent(ctx context.Context, arg InsertBundleRunEventParams) (BundleRunEvent, error)
	InsertMemoryEntry(ctx context.Context, arg InsertMemoryEntryParams) (int64, error)
	InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error
	InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error
	ListAPIKeysForOwner(ctx context.Context, ownerUserID int64) ([]ListAPIKeysForOwnerRow, error)
	ListAgentVersionsForOwner(ctx context.Context, arg ListAgentVersionsForOwnerParams) ([]Agent, error)
	ListAgentsForOwner(ctx context.Context, ownerUserID int64) ([]Agent, error)
	// One row per agent_ref (its most recently created version), per
	// api/openapi.yaml's "每个 ref 返回最新启用版本" list contract.
	ListAgentsForOwnerLatestPage(ctx context.Context, arg ListAgentsForOwnerLatestPageParams) ([]Agent, error)
	ListAuditLogsForActorPage(ctx context.Context, arg ListAuditLogsForActorPageParams) ([]AuditLog, error)
	ListAuditLogsForTarget(ctx context.Context, arg ListAuditLogsForTargetParams) ([]AuditLog, error)
	ListBundleRunEventsAfter(ctx context.Context, arg ListBundleRunEventsAfterParams) ([]BundleRunEvent, error)
	ListBundleRunEventsAfterExternal(ctx context.Context, arg ListBundleRunEventsAfterExternalParams) ([]BundleRunEvent, error)
	ListBundleRunsByBundleAndStatus(ctx context.Context, arg ListBundleRunsByBundleAndStatusParams) ([]BundleRun, error)
	ListBundleRunsForUser(ctx context.Context, arg ListBundleRunsForUserParams) ([]BundleRun, error)
	// bundle_ref/status filters are optional: pass '' to mean "no filter" on
	// that column (sqlc can't express NULL-able string params cleanly here,
	// and callers already have the value-or-empty from query params). Paginated
	// by offset, matching ListBundleRunsForUser's existing convention — run ids
	// are random, not monotonically sortable, so they can't back a keyset cursor.
	ListBundleRunsForUserFiltered(ctx context.Context, arg ListBundleRunsForUserFilteredParams) ([]ListBundleRunsForUserFilteredRow, error)
	ListBundleVersionsForOwner(ctx context.Context, arg ListBundleVersionsForOwnerParams) ([]Bundle, error)
	ListBundlesForOwner(ctx context.Context, ownerUserID int64) ([]Bundle, error)
	// One row per bundle_ref (its most recently created version).
	ListBundlesForOwnerLatestPage(ctx context.Context, arg ListBundlesForOwnerLatestPageParams) ([]Bundle, error)
	ListCatalogModelsForProvider(ctx context.Context, providerID int64) ([]CatalogModel, error)
	// Joined read for 模型广场 (GET /model-catalog): only enabled models under
	// enabled providers, newest provider first so a freshly configured provider
	// surfaces near the top instead of at the bottom of an ORDER BY id.
	ListCatalogModelsPublic(ctx context.Context) ([]ListCatalogModelsPublicRow, error)
	ListCatalogProviders(ctx context.Context) ([]CatalogProvider, error)
	ListHumanGatesForRun(ctx context.Context, runID string) ([]HumanGate, error)
	ListKnowledgeBasesForOwnerPage(ctx context.Context, arg ListKnowledgeBasesForOwnerPageParams) ([]KnowledgeBasis, error)
	ListListingVersionHistory(ctx context.Context, listingRef string) ([]ListListingVersionHistoryRow, error)
	ListMCPServersForOwnerPage(ctx context.Context, arg ListMCPServersForOwnerPageParams) ([]McpServer, error)
	// 组件广场"插件" Tab 用的市场列表：只列公开且审核通过的，每个 plugin_id 一行（最新版本）。
	ListMarketPlugins(ctx context.Context) ([]Plugin, error)
	ListMemoriesForOwnerPage(ctx context.Context, arg ListMemoriesForOwnerPageParams) ([]Memory, error)
	ListModelProvidersForOwner(ctx context.Context, ownerUserID int64) ([]ListModelProvidersForOwnerRow, error)
	// Backs the timeout-scanning job (spec-11): a pending gate with a
	// timeout_seconds set, whose deadline has passed.
	ListPendingHumanGatesPastTimeout(ctx context.Context) ([]HumanGate, error)
	ListPendingReportsPage(ctx context.Context, arg ListPendingReportsPageParams) ([]Report, error)
	ListPendingReviewPlugins(ctx context.Context) ([]Plugin, error)
	ListPermissionKeysForUser(ctx context.Context, userID int64) ([]string, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPluginInstallations(ctx context.Context, ownerUserID int64) ([]PluginInstallation, error)
	ListPluginVersions(ctx context.Context, pluginID string) ([]Plugin, error)
	ListPluginsByPublisher(ctx context.Context, publisherID pgtype.Int8) ([]Plugin, error)
	// ── Browse / detail (blackbox: display_meta only, never definition) ────
	ListPublishedAgentListingsPage(ctx context.Context, arg ListPublishedAgentListingsPageParams) ([]ListPublishedAgentListingsPageRow, error)
	ListPublishedBundleListingsPage(ctx context.Context, arg ListPublishedBundleListingsPageParams) ([]ListPublishedBundleListingsPageRow, error)
	ListPublishedMCPServerListingsPage(ctx context.Context, arg ListPublishedMCPServerListingsPageParams) ([]ListPublishedMCPServerListingsPageRow, error)
	ListPublishedSkillListingsPage(ctx context.Context, arg ListPublishedSkillListingsPageParams) ([]ListPublishedSkillListingsPageRow, error)
	ListRolePermissionKeys(ctx context.Context, roleIds []int64) ([]ListRolePermissionKeysRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRolesForUser(ctx context.Context, userID int64) ([]Role, error)
	ListSkillFilesForSkill(ctx context.Context, arg ListSkillFilesForSkillParams) ([]SkillFile, error)
	ListSkillsForOwnerPage(ctx context.Context, arg ListSkillsForOwnerPageParams) ([]Skill, error)
	ListSubscriptionsForUserPage(ctx context.Context, arg ListSubscriptionsForUserPageParams) ([]Subscription, error)
	ListToolsForOwnerPage(ctx context.Context, arg ListToolsForOwnerPageParams) ([]Tool, error)
	ListUserRoleIDs(ctx context.Context, userIds []int64) ([]ListUserRoleIDsRow, error)
	ListUsersForAdmin(ctx context.Context, search string) ([]ListUsersForAdminRow, error)
	MarkAgentImmutable(ctx context.Context, id int64) error
	MarkBundleImmutable(ctx context.Context, id int64) error
	MarkBundleRunCancelRequested(ctx context.Context, id string) error
	MarkKnowledgeBaseImmutable(ctx context.Context, id int64) error
	MarkMCPServerImmutable(ctx context.Context, id int64) error
	MarkSkillImmutable(ctx context.Context, id int64) error
	MarkToolImmutable(ctx context.Context, id int64) error
	PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) error
	ResolveHumanGate(ctx context.Context, arg ResolveHumanGateParams) (HumanGate, error)
	ResolveReport(ctx context.Context, arg ResolveReportParams) (Report, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SearchMemoryEntries(ctx context.Context, arg SearchMemoryEntriesParams) ([]SearchMemoryEntriesRow, error)
	SetAgentDisplayMeta(ctx context.Context, arg SetAgentDisplayMetaParams) error
	SetAgentStatusByID(ctx context.Context, arg SetAgentStatusByIDParams) error
	SetBundleDisplayMeta(ctx context.Context, arg SetBundleDisplayMetaParams) error
	SetBundleStatusByID(ctx context.Context, arg SetBundleStatusByIDParams) error
	SetCatalogModelStatus(ctx context.Context, arg SetCatalogModelStatusParams) error
	SetCatalogProviderStatus(ctx context.Context, arg SetCatalogProviderStatusParams) error
	SetListingDistribution(ctx context.Context, arg SetListingDistributionParams) error
	SetMCPServerDisplayMeta(ctx context.Context, arg SetMCPServerDisplayMetaParams) error
	SetMCPServerStatusByID(ctx context.Context, arg SetMCPServerStatusByIDParams) error
	SetModelProviderStatus(ctx context.Context, arg SetModelProviderStatusParams) error
	SetPluginReviewStatus(ctx context.Context, arg SetPluginReviewStatusParams) (Plugin, error)
	SetPluginVisibility(ctx context.Context, arg SetPluginVisibilityParams) (Plugin, error)
	SetSkillDisplayMeta(ctx context.Context, arg SetSkillDisplayMetaParams) error
	SetSkillStatusByID(ctx context.Context, arg SetSkillStatusByIDParams) error
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) error
	TouchAPIKeyLastUsed(ctx context.Context, id int64) error
	UpdateBundleRunStatus(ctx context.Context, arg UpdateBundleRunStatusParams) error
	UpdateBundleRunUsage(ctx context.Context, arg UpdateBundleRunUsageParams) error
	UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (KnowledgeBasis, error)
	UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error)
	UpdateMCPServerHealth(ctx context.Context, arg UpdateMCPServerHealthParams) error
	UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error)
	UpdatePluginInstallation(ctx context.Context, arg UpdatePluginInstallationParams) (PluginInstallation, error)
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
	UpdateSubscriptionListing(ctx context.Context, arg UpdateSubscriptionListingParams) (Subscription, error)
	UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error)
	UpsertPublisherKey(ctx context.Context, arg UpsertPublisherKeyParams) (PluginPublisherKey, error)
	UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
