// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
)

type Querier interface {
	CountActiveSubscribedListingsForAgentRef(ctx context.Context, arg CountActiveSubscribedListingsForAgentRefParams) (int64, error)
	CountActiveSubscribedListingsForBundleRef(ctx context.Context, arg CountActiveSubscribedListingsForBundleRefParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	// Owner-view and subscriber-view queries are kept physically separate so the
	// subscriber path can never accidentally SELECT `definition` (see
	// docs/架构设计文档_AI-Agent平台_V1.md 五、"黑盒发布的实现要点").
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateBundle(ctx context.Context, arg CreateBundleParams) (Bundle, error)
	CreateBundleRun(ctx context.Context, arg CreateBundleRunParams) (BundleRun, error)
	CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) (KnowledgeBasis, error)
	CreateListing(ctx context.Context, arg CreateListingParams) (MarketplaceListing, error)
	CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error)
	CreateModelProvider(ctx context.Context, arg CreateModelProviderParams) (CreateModelProviderRow, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementListingSubscriberCount(ctx context.Context, id int64) error
	DeleteAgent(ctx context.Context, id int64) error
	DeleteAgentsByRef(ctx context.Context, arg DeleteAgentsByRefParams) error
	DeleteBundle(ctx context.Context, id int64) error
	DeleteBundlesByRef(ctx context.Context, arg DeleteBundlesByRefParams) error
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	// Knowledge bases surface to an Agent as an entry in capabilities.tools
	// (the DSL has no separate knowledge_base array) — same lookup as tools.
	FindAgentsReferencingKnowledgeBaseRef(ctx context.Context, arg FindAgentsReferencingKnowledgeBaseRefParams) ([]FindAgentsReferencingKnowledgeBaseRefRow, error)
	FindAgentsReferencingMCPServerRef(ctx context.Context, arg FindAgentsReferencingMCPServerRefParams) ([]FindAgentsReferencingMCPServerRefRow, error)
	FindAgentsReferencingSkillRef(ctx context.Context, arg FindAgentsReferencingSkillRefParams) ([]FindAgentsReferencingSkillRefRow, error)
	FindAgentsReferencingToolRef(ctx context.Context, arg FindAgentsReferencingToolRefParams) ([]FindAgentsReferencingToolRefRow, error)
	FindBundlesReferencingAgentRef(ctx context.Context, arg FindBundlesReferencingAgentRefParams) ([]FindBundlesReferencingAgentRefRow, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAgentDisplayForSubscriber(ctx context.Context, id int64) (GetAgentDisplayForSubscriberRow, error)
	GetAgentForOwner(ctx context.Context, arg GetAgentForOwnerParams) (Agent, error)
	GetAgentLatestByRef(ctx context.Context, arg GetAgentLatestByRefParams) (Agent, error)
	GetBundleDisplayForSubscriber(ctx context.Context, id int64) (GetBundleDisplayForSubscriberRow, error)
	GetBundleForOwner(ctx context.Context, arg GetBundleForOwnerParams) (Bundle, error)
	GetBundleRun(ctx context.Context, id string) (BundleRun, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetKnowledgeBaseByIDForOwner(ctx context.Context, arg GetKnowledgeBaseByIDForOwnerParams) (KnowledgeBasis, error)
	GetKnowledgeBaseLatestStatusByRef(ctx context.Context, arg GetKnowledgeBaseLatestStatusByRefParams) (int16, error)
	GetListingByRefVersion(ctx context.Context, arg GetListingByRefVersionParams) (MarketplaceListing, error)
	GetMCPServerByIDForOwner(ctx context.Context, arg GetMCPServerByIDForOwnerParams) (McpServer, error)
	GetMCPServerLatestStatusByRef(ctx context.Context, arg GetMCPServerLatestStatusByRefParams) (int16, error)
	GetModelProviderCredentials(ctx context.Context, arg GetModelProviderCredentialsParams) ([]byte, error)
	GetSkillByIDForOwner(ctx context.Context, arg GetSkillByIDForOwnerParams) (Skill, error)
	GetSkillLatestStatusByRef(ctx context.Context, arg GetSkillLatestStatusByRefParams) (int16, error)
	GetToolByIDForOwner(ctx context.Context, arg GetToolByIDForOwnerParams) (Tool, error)
	GetToolLatestStatusByRef(ctx context.Context, arg GetToolLatestStatusByRefParams) (int16, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	IncrementListingSubscriberCount(ctx context.Context, id int64) error
	InsertBundleRunEvent(ctx context.Context, arg InsertBundleRunEventParams) (BundleRunEvent, error)
	ListAPIKeysForOwner(ctx context.Context, ownerUserID int64) ([]ListAPIKeysForOwnerRow, error)
	ListAgentVersionsForOwner(ctx context.Context, arg ListAgentVersionsForOwnerParams) ([]Agent, error)
	ListAgentsForOwner(ctx context.Context, ownerUserID int64) ([]Agent, error)
	// One row per agent_ref (its most recently created version), per
	// api/openapi.yaml's "每个 ref 返回最新启用版本" list contract.
	ListAgentsForOwnerLatestPage(ctx context.Context, arg ListAgentsForOwnerLatestPageParams) ([]Agent, error)
	ListBundleRunEventsAfter(ctx context.Context, arg ListBundleRunEventsAfterParams) ([]BundleRunEvent, error)
	ListBundleRunEventsAfterExternal(ctx context.Context, arg ListBundleRunEventsAfterExternalParams) ([]BundleRunEvent, error)
	ListBundleRunsByBundleAndStatus(ctx context.Context, arg ListBundleRunsByBundleAndStatusParams) ([]BundleRun, error)
	ListBundleRunsForUser(ctx context.Context, arg ListBundleRunsForUserParams) ([]BundleRun, error)
	ListBundleVersionsForOwner(ctx context.Context, arg ListBundleVersionsForOwnerParams) ([]Bundle, error)
	ListBundlesForOwner(ctx context.Context, ownerUserID int64) ([]Bundle, error)
	// One row per bundle_ref (its most recently created version).
	ListBundlesForOwnerLatestPage(ctx context.Context, arg ListBundlesForOwnerLatestPageParams) ([]Bundle, error)
	ListKnowledgeBasesForOwnerPage(ctx context.Context, arg ListKnowledgeBasesForOwnerPageParams) ([]KnowledgeBasis, error)
	ListListingsByType(ctx context.Context, arg ListListingsByTypeParams) ([]MarketplaceListing, error)
	ListMCPServersForOwnerPage(ctx context.Context, arg ListMCPServersForOwnerPageParams) ([]McpServer, error)
	ListModelProvidersForOwner(ctx context.Context, ownerUserID int64) ([]ListModelProvidersForOwnerRow, error)
	ListSkillsForOwnerPage(ctx context.Context, arg ListSkillsForOwnerPageParams) ([]Skill, error)
	ListSubscriptionsForUser(ctx context.Context, subscriberID int64) ([]Subscription, error)
	ListToolsForOwnerPage(ctx context.Context, arg ListToolsForOwnerPageParams) ([]Tool, error)
	MarkAgentImmutable(ctx context.Context, id int64) error
	MarkBundleImmutable(ctx context.Context, id int64) error
	MarkKnowledgeBaseImmutable(ctx context.Context, id int64) error
	MarkMCPServerImmutable(ctx context.Context, id int64) error
	MarkSkillImmutable(ctx context.Context, id int64) error
	MarkToolImmutable(ctx context.Context, id int64) error
	PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SetListingDistribution(ctx context.Context, arg SetListingDistributionParams) error
	SetModelProviderStatus(ctx context.Context, arg SetModelProviderStatusParams) error
	TouchAPIKeyLastUsed(ctx context.Context, id int64) error
	UpdateBundleRunStatus(ctx context.Context, arg UpdateBundleRunStatusParams) error
	UpdateBundleRunUsage(ctx context.Context, arg UpdateBundleRunUsageParams) error
	UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (KnowledgeBasis, error)
	UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error)
	UpdateMCPServerHealth(ctx context.Context, arg UpdateMCPServerHealthParams) error
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
	UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error)
}

var _ Querier = (*Queries)(nil)
