// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (role_key, name, description)
VALUES ($1, $2, $3)
RETURNING id, role_key, name, description, created_at
`

type CreateRoleParams struct {
	RoleKey     string `json:"role_key"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.RoleKey, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleKey,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getPermissionIDsByKeys = `-- name: GetPermissionIDsByKeys :many
SELECT id FROM permissions WHERE permission_key = ANY($1::text[])
`

func (q *Queries) GetPermissionIDsByKeys(ctx context.Context, keys []string) ([]int64, error) {
	rows, err := q.db.Query(ctx, getPermissionIDsByKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRole = `-- name: GetRole :one
SELECT id, role_key, name, description, created_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleKey,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertRolePermissionParams struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertUserRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserID, arg.RoleID)
	return err
}

const listPermissionKeysForUser = `-- name: ListPermissionKeysForUser :many
SELECT DISTINCT p.permission_key
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
`

func (q *Queries) ListPermissionKeysForUser(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, permission_key, name, module, created_at
FROM permissions
ORDER BY module ASC, id ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.PermissionKey,
			&i.Name,
			&i.Module,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionKeys = `-- name: ListRolePermissionKeys :many
SELECT r.role_id, p.permission_key
FROM role_permissions r
JOIN permissions p ON p.id = r.permission_id
WHERE r.role_id = ANY($1::bigint[])
`

type ListRolePermissionKeysRow struct {
	RoleID        int64  `json:"role_id"`
	PermissionKey string `json:"permission_key"`
}

func (q *Queries) ListRolePermissionKeys(ctx context.Context, roleIds []int64) ([]ListRolePermissionKeysRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissionKeys, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionKeysRow{}
	for rows.Next() {
		var i ListRolePermissionKeysRow
		if err := rows.Scan(&i.RoleID, &i.PermissionKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, role_key, name, description, created_at
FROM roles
ORDER BY created_at ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleKey,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT r.id, r.role_key, r.name, r.description, r.created_at
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.created_at ASC
`

func (q *Queries) ListRolesForUser(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleKey,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleIDs = `-- name: ListUserRoleIDs :many
SELECT role_id, user_id FROM user_roles WHERE user_id = ANY($1::bigint[])
`

type ListUserRoleIDsRow struct {
	RoleID int64 `json:"role_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) ListUserRoleIDs(ctx context.Context, userIds []int64) ([]ListUserRoleIDsRow, error) {
	rows, err := q.db.Query(ctx, listUserRoleIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRoleIDsRow{}
	for rows.Next() {
		var i ListUserRoleIDsRow
		if err := rows.Scan(&i.RoleID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT id, email, display_name, status, is_admin, created_at
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1::text || '%' OR display_name ILIKE '%' || $1::text || '%')
ORDER BY created_at ASC
`

type ListUsersForAdminRow struct {
	ID          int64              `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Status      int16              `json:"status"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersForAdmin(ctx context.Context, search string) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForAdminRow{}
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users SET status = $2 WHERE id = $1
`

type SetUserStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status)
	return err
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    JOIN role_permissions rp ON rp.role_id = ur.role_id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE ur.user_id = $1 AND p.permission_key = $2
) AS has_permission
`

type UserHasPermissionParams struct {
	UserID        int64  `json:"user_id"`
	PermissionKey string `json:"permission_key"`
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasPermission, arg.UserID, arg.PermissionKey)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
