// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (listing_id, reporter_user_id, reason)
VALUES ($1, $2, $3)
RETURNING id, listing_id, reporter_user_id, reason, status, resolution, resolved_by, resolved_at, created_at
`

type CreateReportParams struct {
	ListingID      int64  `json:"listing_id"`
	ReporterUserID int64  `json:"reporter_user_id"`
	Reason         string `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport, arg.ListingID, arg.ReporterUserID, arg.Reason)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ReporterUserID,
		&i.Reason,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, listing_id, reporter_user_id, reason, status, resolution, resolved_by, resolved_at, created_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id int64) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ReporterUserID,
		&i.Reason,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingReportsPage = `-- name: ListPendingReportsPage :many
SELECT id, listing_id, reporter_user_id, reason, status, resolution, resolved_by, resolved_at, created_at FROM reports WHERE status = 'pending' AND id < $1 ORDER BY id DESC LIMIT $2
`

type ListPendingReportsPageParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

func (q *Queries) ListPendingReportsPage(ctx context.Context, arg ListPendingReportsPageParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listPendingReportsPage, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.ReporterUserID,
			&i.Reason,
			&i.Status,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :one
UPDATE reports SET status = 'resolved', resolution = $2, resolved_by = $3, resolved_at = now()
WHERE id = $1
RETURNING id, listing_id, reporter_user_id, reason, status, resolution, resolved_by, resolved_at, created_at
`

type ResolveReportParams struct {
	ID         int64       `json:"id"`
	Resolution pgtype.Text `json:"resolution"`
	ResolvedBy pgtype.Int8 `json:"resolved_by"`
}

func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, resolveReport, arg.ID, arg.Resolution, arg.ResolvedBy)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ReporterUserID,
		&i.Reason,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}
