// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (owner_user_id, type, ref, version, config, display_meta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_user_id, type, ref, version, config, display_meta, status, immutable, created_at
`

type CreateResourceParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Type        string `json:"type"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
	Config      []byte `json:"config"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.OwnerUserID,
		arg.Type,
		arg.Ref,
		arg.Version,
		arg.Config,
		arg.DisplayMeta,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Type,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResourceDisplayForSubscriber = `-- name: GetResourceDisplayForSubscriber :one
SELECT id, owner_user_id, type, ref, version, display_meta, status, created_at
FROM resources
WHERE id = $1
`

type GetResourceDisplayForSubscriberRow struct {
	ID          int64              `json:"id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Type        string             `json:"type"`
	Ref         string             `json:"ref"`
	Version     string             `json:"version"`
	DisplayMeta []byte             `json:"display_meta"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetResourceDisplayForSubscriber(ctx context.Context, id int64) (GetResourceDisplayForSubscriberRow, error) {
	row := q.db.QueryRow(ctx, getResourceDisplayForSubscriber, id)
	var i GetResourceDisplayForSubscriberRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Type,
		&i.Ref,
		&i.Version,
		&i.DisplayMeta,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getResourceForOwner = `-- name: GetResourceForOwner :one
SELECT id, owner_user_id, type, ref, version, config, display_meta, status, immutable, created_at FROM resources
WHERE owner_user_id = $1 AND type = $2 AND ref = $3 AND version = $4
`

type GetResourceForOwnerParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Type        string `json:"type"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
}

func (q *Queries) GetResourceForOwner(ctx context.Context, arg GetResourceForOwnerParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceForOwner,
		arg.OwnerUserID,
		arg.Type,
		arg.Ref,
		arg.Version,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Type,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const listResourcesForOwner = `-- name: ListResourcesForOwner :many
SELECT id, owner_user_id, type, ref, version, config, display_meta, status, immutable, created_at FROM resources
WHERE owner_user_id = $1
ORDER BY type, ref, created_at DESC
`

func (q *Queries) ListResourcesForOwner(ctx context.Context, ownerUserID int64) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Type,
			&i.Ref,
			&i.Version,
			&i.Config,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResourceImmutable = `-- name: MarkResourceImmutable :exec
UPDATE resources SET immutable = true WHERE id = $1
`

func (q *Queries) MarkResourceImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markResourceImmutable, id)
	return err
}

const setResourceStatus = `-- name: SetResourceStatus :exec
UPDATE resources SET status = $2 WHERE id = $1
`

type SetResourceStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) SetResourceStatus(ctx context.Context, arg SetResourceStatusParams) error {
	_, err := q.db.Exec(ctx, setResourceStatus, arg.ID, arg.Status)
	return err
}
