// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBundleRun = `-- name: CreateBundleRun :one
INSERT INTO bundle_runs (id, bundle_id, triggered_by, via_listing_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bundle_id, triggered_by, via_listing_id, status, error, shared_state, total_tokens, cost_usd, created_at, finished_at, cancel_requested_at
`

type CreateBundleRunParams struct {
	ID           string      `json:"id"`
	BundleID     int64       `json:"bundle_id"`
	TriggeredBy  int64       `json:"triggered_by"`
	ViaListingID pgtype.Int8 `json:"via_listing_id"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateBundleRun(ctx context.Context, arg CreateBundleRunParams) (BundleRun, error) {
	row := q.db.QueryRow(ctx, createBundleRun,
		arg.ID,
		arg.BundleID,
		arg.TriggeredBy,
		arg.ViaListingID,
		arg.Status,
	)
	var i BundleRun
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.TriggeredBy,
		&i.ViaListingID,
		&i.Status,
		&i.Error,
		&i.SharedState,
		&i.TotalTokens,
		&i.CostUsd,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
	)
	return i, err
}

const getBundleRun = `-- name: GetBundleRun :one
SELECT id, bundle_id, triggered_by, via_listing_id, status, error, shared_state, total_tokens, cost_usd, created_at, finished_at, cancel_requested_at FROM bundle_runs WHERE id = $1
`

func (q *Queries) GetBundleRun(ctx context.Context, id string) (BundleRun, error) {
	row := q.db.QueryRow(ctx, getBundleRun, id)
	var i BundleRun
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.TriggeredBy,
		&i.ViaListingID,
		&i.Status,
		&i.Error,
		&i.SharedState,
		&i.TotalTokens,
		&i.CostUsd,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
	)
	return i, err
}

const getUsageBreakdownByBundleForUser = `-- name: GetUsageBreakdownByBundleForUser :many
SELECT
    b.bundle_ref AS key,
    COALESCE(SUM(br.total_tokens), 0)::bigint AS tokens,
    COALESCE(SUM(br.cost_usd), 0)::numeric AS cost_usd,
    COUNT(*)::bigint AS run_count
FROM bundle_runs br
JOIN bundles b ON b.id = br.bundle_id
WHERE br.triggered_by = $1 AND br.created_at >= $2
GROUP BY b.bundle_ref
ORDER BY tokens DESC
`

type GetUsageBreakdownByBundleForUserParams struct {
	TriggeredBy int64              `json:"triggered_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GetUsageBreakdownByBundleForUserRow struct {
	Key      string         `json:"key"`
	Tokens   int64          `json:"tokens"`
	CostUsd  pgtype.Numeric `json:"cost_usd"`
	RunCount int64          `json:"run_count"`
}

func (q *Queries) GetUsageBreakdownByBundleForUser(ctx context.Context, arg GetUsageBreakdownByBundleForUserParams) ([]GetUsageBreakdownByBundleForUserRow, error) {
	rows, err := q.db.Query(ctx, getUsageBreakdownByBundleForUser, arg.TriggeredBy, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageBreakdownByBundleForUserRow{}
	for rows.Next() {
		var i GetUsageBreakdownByBundleForUserRow
		if err := rows.Scan(
			&i.Key,
			&i.Tokens,
			&i.CostUsd,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageBreakdownByDayForUser = `-- name: GetUsageBreakdownByDayForUser :many
SELECT
    to_char(br.created_at, 'YYYY-MM-DD') AS key,
    COALESCE(SUM(br.total_tokens), 0)::bigint AS tokens,
    COALESCE(SUM(br.cost_usd), 0)::numeric AS cost_usd,
    COUNT(*)::bigint AS run_count
FROM bundle_runs br
WHERE br.triggered_by = $1 AND br.created_at >= $2
GROUP BY to_char(br.created_at, 'YYYY-MM-DD')
ORDER BY key DESC
`

type GetUsageBreakdownByDayForUserParams struct {
	TriggeredBy int64              `json:"triggered_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GetUsageBreakdownByDayForUserRow struct {
	Key      string         `json:"key"`
	Tokens   int64          `json:"tokens"`
	CostUsd  pgtype.Numeric `json:"cost_usd"`
	RunCount int64          `json:"run_count"`
}

func (q *Queries) GetUsageBreakdownByDayForUser(ctx context.Context, arg GetUsageBreakdownByDayForUserParams) ([]GetUsageBreakdownByDayForUserRow, error) {
	rows, err := q.db.Query(ctx, getUsageBreakdownByDayForUser, arg.TriggeredBy, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageBreakdownByDayForUserRow{}
	for rows.Next() {
		var i GetUsageBreakdownByDayForUserRow
		if err := rows.Scan(
			&i.Key,
			&i.Tokens,
			&i.CostUsd,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSummaryForUser = `-- name: GetUsageSummaryForUser :one

SELECT
    COALESCE(SUM(total_tokens), 0)::bigint AS total_tokens,
    COALESCE(SUM(cost_usd), 0)::numeric AS total_cost_usd,
    COUNT(*)::bigint AS run_count
FROM bundle_runs
WHERE triggered_by = $1 AND created_at >= $2
`

type GetUsageSummaryForUserParams struct {
	TriggeredBy int64              `json:"triggered_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GetUsageSummaryForUserRow struct {
	TotalTokens  int64          `json:"total_tokens"`
	TotalCostUsd pgtype.Numeric `json:"total_cost_usd"`
	RunCount     int64          `json:"run_count"`
}

// ── Usage & cost (/usage/me) ─────────────────────────────────────────
// Usage is always scoped to the person who triggered the run — spec-09:
// "黑盒资源的用量算订阅者的" — a subscriber running someone else's
// published Bundle is the one whose usage this counts against, which
// `triggered_by` already captures regardless of `via_listing_id`.
func (q *Queries) GetUsageSummaryForUser(ctx context.Context, arg GetUsageSummaryForUserParams) (GetUsageSummaryForUserRow, error) {
	row := q.db.QueryRow(ctx, getUsageSummaryForUser, arg.TriggeredBy, arg.CreatedAt)
	var i GetUsageSummaryForUserRow
	err := row.Scan(&i.TotalTokens, &i.TotalCostUsd, &i.RunCount)
	return i, err
}

const insertBundleRunEvent = `-- name: InsertBundleRunEvent :one
INSERT INTO bundle_run_events (run_id, type, node, payload, is_internal)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, type, node, payload, is_internal, created_at
`

type InsertBundleRunEventParams struct {
	RunID      string      `json:"run_id"`
	Type       string      `json:"type"`
	Node       pgtype.Text `json:"node"`
	Payload    []byte      `json:"payload"`
	IsInternal bool        `json:"is_internal"`
}

func (q *Queries) InsertBundleRunEvent(ctx context.Context, arg InsertBundleRunEventParams) (BundleRunEvent, error) {
	row := q.db.QueryRow(ctx, insertBundleRunEvent,
		arg.RunID,
		arg.Type,
		arg.Node,
		arg.Payload,
		arg.IsInternal,
	)
	var i BundleRunEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Type,
		&i.Node,
		&i.Payload,
		&i.IsInternal,
		&i.CreatedAt,
	)
	return i, err
}

const listBundleRunEventsAfter = `-- name: ListBundleRunEventsAfter :many
SELECT id, run_id, type, node, payload, is_internal, created_at FROM bundle_run_events
WHERE run_id = $1 AND id > $2
ORDER BY id ASC
`

type ListBundleRunEventsAfterParams struct {
	RunID string `json:"run_id"`
	ID    int64  `json:"id"`
}

func (q *Queries) ListBundleRunEventsAfter(ctx context.Context, arg ListBundleRunEventsAfterParams) ([]BundleRunEvent, error) {
	rows, err := q.db.Query(ctx, listBundleRunEventsAfter, arg.RunID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BundleRunEvent{}
	for rows.Next() {
		var i BundleRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Type,
			&i.Node,
			&i.Payload,
			&i.IsInternal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleRunEventsAfterExternal = `-- name: ListBundleRunEventsAfterExternal :many
SELECT id, run_id, type, node, payload, is_internal, created_at FROM bundle_run_events
WHERE run_id = $1 AND id > $2 AND is_internal = false
ORDER BY id ASC
`

type ListBundleRunEventsAfterExternalParams struct {
	RunID string `json:"run_id"`
	ID    int64  `json:"id"`
}

func (q *Queries) ListBundleRunEventsAfterExternal(ctx context.Context, arg ListBundleRunEventsAfterExternalParams) ([]BundleRunEvent, error) {
	rows, err := q.db.Query(ctx, listBundleRunEventsAfterExternal, arg.RunID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BundleRunEvent{}
	for rows.Next() {
		var i BundleRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Type,
			&i.Node,
			&i.Payload,
			&i.IsInternal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleRunsByBundleAndStatus = `-- name: ListBundleRunsByBundleAndStatus :many
SELECT id, bundle_id, triggered_by, via_listing_id, status, error, shared_state, total_tokens, cost_usd, created_at, finished_at, cancel_requested_at FROM bundle_runs
WHERE bundle_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListBundleRunsByBundleAndStatusParams struct {
	BundleID int64  `json:"bundle_id"`
	Status   string `json:"status"`
}

func (q *Queries) ListBundleRunsByBundleAndStatus(ctx context.Context, arg ListBundleRunsByBundleAndStatusParams) ([]BundleRun, error) {
	rows, err := q.db.Query(ctx, listBundleRunsByBundleAndStatus, arg.BundleID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BundleRun{}
	for rows.Next() {
		var i BundleRun
		if err := rows.Scan(
			&i.ID,
			&i.BundleID,
			&i.TriggeredBy,
			&i.ViaListingID,
			&i.Status,
			&i.Error,
			&i.SharedState,
			&i.TotalTokens,
			&i.CostUsd,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleRunsForUser = `-- name: ListBundleRunsForUser :many
SELECT id, bundle_id, triggered_by, via_listing_id, status, error, shared_state, total_tokens, cost_usd, created_at, finished_at, cancel_requested_at FROM bundle_runs
WHERE triggered_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBundleRunsForUserParams struct {
	TriggeredBy int64 `json:"triggered_by"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListBundleRunsForUser(ctx context.Context, arg ListBundleRunsForUserParams) ([]BundleRun, error) {
	rows, err := q.db.Query(ctx, listBundleRunsForUser, arg.TriggeredBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BundleRun{}
	for rows.Next() {
		var i BundleRun
		if err := rows.Scan(
			&i.ID,
			&i.BundleID,
			&i.TriggeredBy,
			&i.ViaListingID,
			&i.Status,
			&i.Error,
			&i.SharedState,
			&i.TotalTokens,
			&i.CostUsd,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleRunsForUserFiltered = `-- name: ListBundleRunsForUserFiltered :many
SELECT br.id, br.bundle_id, br.triggered_by, br.via_listing_id, br.status, br.error, br.shared_state, br.total_tokens, br.cost_usd, br.created_at, br.finished_at, br.cancel_requested_at, b.bundle_ref AS bundle_ref, b.version AS bundle_version FROM bundle_runs br
JOIN bundles b ON b.id = br.bundle_id
WHERE br.triggered_by = $1
  AND ($2::text = '' OR b.bundle_ref = $2)
  AND ($3::text = '' OR br.status = $3)
ORDER BY br.created_at DESC
LIMIT $5 OFFSET $4
`

type ListBundleRunsForUserFilteredParams struct {
	TriggeredBy int64  `json:"triggered_by"`
	BundleRef   string `json:"bundle_ref"`
	RunStatus   string `json:"run_status"`
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
}

type ListBundleRunsForUserFilteredRow struct {
	ID                string             `json:"id"`
	BundleID          int64              `json:"bundle_id"`
	TriggeredBy       int64              `json:"triggered_by"`
	ViaListingID      pgtype.Int8        `json:"via_listing_id"`
	Status            string             `json:"status"`
	Error             pgtype.Text        `json:"error"`
	SharedState       []byte             `json:"shared_state"`
	TotalTokens       int64              `json:"total_tokens"`
	CostUsd           pgtype.Numeric     `json:"cost_usd"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
	BundleRef         string             `json:"bundle_ref"`
	BundleVersion     string             `json:"bundle_version"`
}

// bundle_ref/status filters are optional: pass ” to mean "no filter" on
// that column (sqlc can't express NULL-able string params cleanly here,
// and callers already have the value-or-empty from query params). Paginated
// by offset, matching ListBundleRunsForUser's existing convention — run ids
// are random, not monotonically sortable, so they can't back a keyset cursor.
func (q *Queries) ListBundleRunsForUserFiltered(ctx context.Context, arg ListBundleRunsForUserFilteredParams) ([]ListBundleRunsForUserFilteredRow, error) {
	rows, err := q.db.Query(ctx, listBundleRunsForUserFiltered,
		arg.TriggeredBy,
		arg.BundleRef,
		arg.RunStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBundleRunsForUserFilteredRow{}
	for rows.Next() {
		var i ListBundleRunsForUserFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.BundleID,
			&i.TriggeredBy,
			&i.ViaListingID,
			&i.Status,
			&i.Error,
			&i.SharedState,
			&i.TotalTokens,
			&i.CostUsd,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.BundleRef,
			&i.BundleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBundleRunCancelRequested = `-- name: MarkBundleRunCancelRequested :exec
UPDATE bundle_runs SET cancel_requested_at = now() WHERE id = $1 AND status = 'running'
`

func (q *Queries) MarkBundleRunCancelRequested(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markBundleRunCancelRequested, id)
	return err
}

const updateBundleRunStatus = `-- name: UpdateBundleRunStatus :exec
UPDATE bundle_runs SET status = $2, error = $3, finished_at = $4 WHERE id = $1
`

type UpdateBundleRunStatusParams struct {
	ID         string             `json:"id"`
	Status     string             `json:"status"`
	Error      pgtype.Text        `json:"error"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateBundleRunStatus(ctx context.Context, arg UpdateBundleRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateBundleRunStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.FinishedAt,
	)
	return err
}

const updateBundleRunUsage = `-- name: UpdateBundleRunUsage :exec
UPDATE bundle_runs SET total_tokens = total_tokens + $2, cost_usd = cost_usd + $3 WHERE id = $1
`

type UpdateBundleRunUsageParams struct {
	ID          string         `json:"id"`
	TotalTokens int64          `json:"total_tokens"`
	CostUsd     pgtype.Numeric `json:"cost_usd"`
}

func (q *Queries) UpdateBundleRunUsage(ctx context.Context, arg UpdateBundleRunUsageParams) error {
	_, err := q.db.Exec(ctx, updateBundleRunUsage, arg.ID, arg.TotalTokens, arg.CostUsd)
	return err
}
