// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: skill_files.sql

package store

import (
	"context"
)

const createSkillFile = `-- name: CreateSkillFile :exec
INSERT INTO skill_files (skill_id, owner_user_id, path, size_bytes, content_type)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSkillFileParams struct {
	SkillID     int64  `json:"skill_id"`
	OwnerUserID int64  `json:"owner_user_id"`
	Path        string `json:"path"`
	SizeBytes   int64  `json:"size_bytes"`
	ContentType string `json:"content_type"`
}

func (q *Queries) CreateSkillFile(ctx context.Context, arg CreateSkillFileParams) error {
	_, err := q.db.Exec(ctx, createSkillFile,
		arg.SkillID,
		arg.OwnerUserID,
		arg.Path,
		arg.SizeBytes,
		arg.ContentType,
	)
	return err
}

const listSkillFilesForSkill = `-- name: ListSkillFilesForSkill :many
SELECT id, skill_id, owner_user_id, path, size_bytes, content_type, created_at FROM skill_files WHERE skill_id = $1 AND owner_user_id = $2 ORDER BY path ASC
`

type ListSkillFilesForSkillParams struct {
	SkillID     int64 `json:"skill_id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) ListSkillFilesForSkill(ctx context.Context, arg ListSkillFilesForSkillParams) ([]SkillFile, error) {
	rows, err := q.db.Query(ctx, listSkillFilesForSkill, arg.SkillID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillFile{}
	for rows.Next() {
		var i SkillFile
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.OwnerUserID,
			&i.Path,
			&i.SizeBytes,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
