// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: skills.sql

package store

import (
	"context"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (owner_user_id, ref, version, config, display_meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type CreateSkillParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
	Config      []byte `json:"config"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.OwnerUserID,
		arg.Ref,
		arg.Version,
		arg.Config,
		arg.DisplayMeta,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const findAgentsReferencingSkillRef = `-- name: FindAgentsReferencingSkillRef :many
SELECT owner_user_id, agent_ref, version FROM agents
WHERE owner_user_id = $1
  AND (definition->'capabilities'->'skills') ? $2::text
`

type FindAgentsReferencingSkillRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Column2     string `json:"column_2"`
}

type FindAgentsReferencingSkillRefRow struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
}

func (q *Queries) FindAgentsReferencingSkillRef(ctx context.Context, arg FindAgentsReferencingSkillRefParams) ([]FindAgentsReferencingSkillRefRow, error) {
	rows, err := q.db.Query(ctx, findAgentsReferencingSkillRef, arg.OwnerUserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAgentsReferencingSkillRefRow{}
	for rows.Next() {
		var i FindAgentsReferencingSkillRefRow
		if err := rows.Scan(&i.OwnerUserID, &i.AgentRef, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillByIDForOwner = `-- name: GetSkillByIDForOwner :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM skills WHERE id = $1 AND owner_user_id = $2
`

type GetSkillByIDForOwnerParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) GetSkillByIDForOwner(ctx context.Context, arg GetSkillByIDForOwnerParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByIDForOwner, arg.ID, arg.OwnerUserID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillLatestStatusByRef = `-- name: GetSkillLatestStatusByRef :one
SELECT status FROM skills WHERE owner_user_id = $1 AND ref = $2 ORDER BY created_at DESC LIMIT 1
`

type GetSkillLatestStatusByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
}

func (q *Queries) GetSkillLatestStatusByRef(ctx context.Context, arg GetSkillLatestStatusByRefParams) (int16, error) {
	row := q.db.QueryRow(ctx, getSkillLatestStatusByRef, arg.OwnerUserID, arg.Ref)
	var status int16
	err := row.Scan(&status)
	return status, err
}

const listSkillsForOwnerPage = `-- name: ListSkillsForOwnerPage :many
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM skills WHERE owner_user_id = $1 AND id > $2 ORDER BY id ASC LIMIT $3
`

type ListSkillsForOwnerPageParams struct {
	OwnerUserID int64 `json:"owner_user_id"`
	ID          int64 `json:"id"`
	Limit       int32 `json:"limit"`
}

func (q *Queries) ListSkillsForOwnerPage(ctx context.Context, arg ListSkillsForOwnerPageParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsForOwnerPage, arg.OwnerUserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Ref,
			&i.Version,
			&i.Config,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSkillImmutable = `-- name: MarkSkillImmutable :exec
UPDATE skills SET immutable = true WHERE id = $1
`

func (q *Queries) MarkSkillImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSkillImmutable, id)
	return err
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills SET display_meta = $3, config = $4, status = $5
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type UpdateSkillParams struct {
	ID          int64  `json:"id"`
	OwnerUserID int64  `json:"owner_user_id"`
	DisplayMeta []byte `json:"display_meta"`
	Config      []byte `json:"config"`
	Status      int16  `json:"status"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayMeta,
		arg.Config,
		arg.Status,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}
