// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: skill_sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkillSource = `-- name: CreateSkillSource :one
INSERT INTO skill_sources (name, base_url)
VALUES ($1, $2)
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at
`

type CreateSkillSourceParams struct {
	Name    string `json:"name"`
	BaseUrl string `json:"base_url"`
}

func (q *Queries) CreateSkillSource(ctx context.Context, arg CreateSkillSourceParams) (SkillSource, error) {
	row := q.db.QueryRow(ctx, createSkillSource, arg.Name, arg.BaseUrl)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSkillSource = `-- name: DeleteSkillSource :execrows
DELETE FROM skill_sources WHERE id = $1
`

func (q *Queries) DeleteSkillSource(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleMarketSkills = `-- name: DeleteStaleMarketSkills :execrows
DELETE FROM market_skills
WHERE source_id = $1 AND slug <> ALL($2::text[])
`

type DeleteStaleMarketSkillsParams struct {
	SourceID int64    `json:"source_id"`
	Column2  []string `json:"column_2"`
}

func (q *Queries) DeleteStaleMarketSkills(ctx context.Context, arg DeleteStaleMarketSkillsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleMarketSkills, arg.SourceID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMarketSkill = `-- name: GetMarketSkill :one
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.changelog, m.topics, m.stars, m.downloads, m.updated_at, m.raw, m.synced_at, s.name AS source_name, s.base_url AS source_base_url
FROM market_skills m
JOIN skill_sources s ON s.id = m.source_id
WHERE m.source_id = $1 AND m.slug = $2
`

type GetMarketSkillParams struct {
	SourceID int64  `json:"source_id"`
	Slug     string `json:"slug"`
}

type GetMarketSkillRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	Changelog     pgtype.Text        `json:"changelog"`
	Topics        []string           `json:"topics"`
	Stars         int64              `json:"stars"`
	Downloads     int64              `json:"downloads"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

func (q *Queries) GetMarketSkill(ctx context.Context, arg GetMarketSkillParams) (GetMarketSkillRow, error) {
	row := q.db.QueryRow(ctx, getMarketSkill, arg.SourceID, arg.Slug)
	var i GetMarketSkillRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Version,
		&i.License,
		&i.Changelog,
		&i.Topics,
		&i.Stars,
		&i.Downloads,
		&i.UpdatedAt,
		&i.Raw,
		&i.SyncedAt,
		&i.SourceName,
		&i.SourceBaseUrl,
	)
	return i, err
}

const getSkillSource = `-- name: GetSkillSource :one
SELECT id, name, base_url, status, last_synced_at, last_sync_error, created_at FROM skill_sources WHERE id = $1
`

func (q *Queries) GetSkillSource(ctx context.Context, id int64) (SkillSource, error) {
	row := q.db.QueryRow(ctx, getSkillSource, id)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillSourceByURL = `-- name: GetSkillSourceByURL :one
SELECT id, name, base_url, status, last_synced_at, last_sync_error, created_at FROM skill_sources WHERE base_url = $1
`

func (q *Queries) GetSkillSourceByURL(ctx context.Context, baseUrl string) (SkillSource, error) {
	row := q.db.QueryRow(ctx, getSkillSourceByURL, baseUrl)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const listMarketSkills = `-- name: ListMarketSkills :many
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.changelog, m.topics, m.stars, m.downloads, m.updated_at, m.raw, m.synced_at, s.name AS source_name, s.base_url AS source_base_url
FROM market_skills m
JOIN skill_sources s ON s.id = m.source_id AND s.status = 1
ORDER BY m.updated_at DESC NULLS LAST
`

type ListMarketSkillsRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	Changelog     pgtype.Text        `json:"changelog"`
	Topics        []string           `json:"topics"`
	Stars         int64              `json:"stars"`
	Downloads     int64              `json:"downloads"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

// Skill 管理 → 市场视图：所有启用源的缓存条目，附源信息供卡片和详情回链。
func (q *Queries) ListMarketSkills(ctx context.Context) ([]ListMarketSkillsRow, error) {
	rows, err := q.db.Query(ctx, listMarketSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketSkillsRow{}
	for rows.Next() {
		var i ListMarketSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.Version,
			&i.License,
			&i.Changelog,
			&i.Topics,
			&i.Stars,
			&i.Downloads,
			&i.UpdatedAt,
			&i.Raw,
			&i.SyncedAt,
			&i.SourceName,
			&i.SourceBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillSources = `-- name: ListSkillSources :many
SELECT s.id, s.name, s.base_url, s.status, s.last_synced_at, s.last_sync_error, s.created_at, COUNT(m.id)::bigint AS skill_count
FROM skill_sources s
LEFT JOIN market_skills m ON m.source_id = s.id
GROUP BY s.id
ORDER BY s.created_at DESC
`

type ListSkillSourcesRow struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	BaseUrl       string             `json:"base_url"`
	Status        int16              `json:"status"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncError pgtype.Text        `json:"last_sync_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SkillCount    int64              `json:"skill_count"`
}

// 左联 market_skills 只为拿每个源的条目数，设置页直接展示。
func (q *Queries) ListSkillSources(ctx context.Context) ([]ListSkillSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSkillSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillSourcesRow{}
	for rows.Next() {
		var i ListSkillSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.CreatedAt,
			&i.SkillCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSkillSourceSyncError = `-- name: MarkSkillSourceSyncError :one
UPDATE skill_sources
SET last_synced_at = now(), last_sync_error = $2
WHERE id = $1
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at
`

type MarkSkillSourceSyncErrorParams struct {
	ID            int64       `json:"id"`
	LastSyncError pgtype.Text `json:"last_sync_error"`
}

func (q *Queries) MarkSkillSourceSyncError(ctx context.Context, arg MarkSkillSourceSyncErrorParams) (SkillSource, error) {
	row := q.db.QueryRow(ctx, markSkillSourceSyncError, arg.ID, arg.LastSyncError)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const markSkillSourceSynced = `-- name: MarkSkillSourceSynced :one
UPDATE skill_sources
SET last_synced_at = now(), last_sync_error = NULL
WHERE id = $1
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at
`

func (q *Queries) MarkSkillSourceSynced(ctx context.Context, id int64) (SkillSource, error) {
	row := q.db.QueryRow(ctx, markSkillSourceSynced, id)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMarketSkill = `-- name: UpsertMarketSkill :one
INSERT INTO market_skills (source_id, slug, name, summary, version, license, changelog, topics, stars, downloads, updated_at, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (source_id, slug) DO UPDATE SET
    name        = EXCLUDED.name,
    summary     = EXCLUDED.summary,
    version     = EXCLUDED.version,
    license     = EXCLUDED.license,
    changelog   = EXCLUDED.changelog,
    topics      = EXCLUDED.topics,
    stars       = EXCLUDED.stars,
    downloads   = EXCLUDED.downloads,
    updated_at  = EXCLUDED.updated_at,
    raw         = EXCLUDED.raw,
    synced_at   = now()
RETURNING id, source_id, slug, name, summary, version, license, changelog, topics, stars, downloads, updated_at, raw, synced_at
`

type UpsertMarketSkillParams struct {
	SourceID  int64              `json:"source_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Summary   pgtype.Text        `json:"summary"`
	Version   pgtype.Text        `json:"version"`
	License   pgtype.Text        `json:"license"`
	Changelog pgtype.Text        `json:"changelog"`
	Topics    []string           `json:"topics"`
	Stars     int64              `json:"stars"`
	Downloads int64              `json:"downloads"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Raw       []byte             `json:"raw"`
}

// 同步落库：同一 (source, slug) 覆盖刷新，上次同步后被上游下架的条目由
// Sync 清理（见 DeleteStaleMarketSkills）。
func (q *Queries) UpsertMarketSkill(ctx context.Context, arg UpsertMarketSkillParams) (MarketSkill, error) {
	row := q.db.QueryRow(ctx, upsertMarketSkill,
		arg.SourceID,
		arg.Slug,
		arg.Name,
		arg.Summary,
		arg.Version,
		arg.License,
		arg.Changelog,
		arg.Topics,
		arg.Stars,
		arg.Downloads,
		arg.UpdatedAt,
		arg.Raw,
	)
	var i MarketSkill
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Version,
		&i.License,
		&i.Changelog,
		&i.Topics,
		&i.Stars,
		&i.Downloads,
		&i.UpdatedAt,
		&i.Raw,
		&i.SyncedAt,
	)
	return i, err
}
