// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: skill_sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMarketSkillsByReview = `-- name: CountMarketSkillsByReview :many
SELECT review_status, COUNT(*)::bigint AS count
FROM market_skills
WHERE ($1::bigint IS NULL OR source_id = $1::bigint)
GROUP BY review_status
`

type CountMarketSkillsByReviewRow struct {
	ReviewStatus string `json:"review_status"`
	Count        int64  `json:"count"`
}

// 审核台顶部的状态计数，一次查完免得前端按状态各拉一遍。source_id 为空时
// 统计全部源；审核台是按源进的，那里必须传源 ID，否则顶部计数和下面的列表
// 对不上。
func (q *Queries) CountMarketSkillsByReview(ctx context.Context, sourceID pgtype.Int8) ([]CountMarketSkillsByReviewRow, error) {
	rows, err := q.db.Query(ctx, countMarketSkillsByReview, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMarketSkillsByReviewRow{}
	for rows.Next() {
		var i CountMarketSkillsByReviewRow
		if err := rows.Scan(&i.ReviewStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMarketSkillsForReview = `-- name: CountMarketSkillsForReview :one
SELECT COUNT(*)::bigint
FROM market_skills m
JOIN skill_sources s ON s.id = m.source_id
WHERE ($1::text IS NULL OR m.review_status = $1::text)
  AND ($2::bigint IS NULL OR m.source_id = $2::bigint)
  AND ($3::text IS NULL
       OR m.slug ILIKE '%' || $3::text || '%'
       OR m.name ILIKE '%' || $3::text || '%'
       OR COALESCE(m.summary, '') ILIKE '%' || $3::text || '%')
`

type CountMarketSkillsForReviewParams struct {
	ReviewStatus pgtype.Text `json:"review_status"`
	SourceID     pgtype.Int8 `json:"source_id"`
	Search       pgtype.Text `json:"search"`
}

// 与 ListMarketSkillsForReview 同一套筛选条件下的总数，供前端算总页数。
func (q *Queries) CountMarketSkillsForReview(ctx context.Context, arg CountMarketSkillsForReviewParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMarketSkillsForReview, arg.ReviewStatus, arg.SourceID, arg.Search)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSkillSource = `-- name: CreateSkillSource :one
INSERT INTO skill_sources (name, base_url)
VALUES ($1, $2)
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at
`

type CreateSkillSourceParams struct {
	Name    string `json:"name"`
	BaseUrl string `json:"base_url"`
}

func (q *Queries) CreateSkillSource(ctx context.Context, arg CreateSkillSourceParams) (SkillSource, error) {
	row := q.db.QueryRow(ctx, createSkillSource, arg.Name, arg.BaseUrl)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSkillSource = `-- name: DeleteSkillSource :execrows
DELETE FROM skill_sources WHERE id = $1
`

func (q *Queries) DeleteSkillSource(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleMarketSkills = `-- name: DeleteStaleMarketSkills :execrows
DELETE FROM market_skills
WHERE source_id = $1 AND slug <> ALL($2::text[])
`

type DeleteStaleMarketSkillsParams struct {
	SourceID int64    `json:"source_id"`
	Column2  []string `json:"column_2"`
}

func (q *Queries) DeleteStaleMarketSkills(ctx context.Context, arg DeleteStaleMarketSkillsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleMarketSkills, arg.SourceID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMarketSkill = `-- name: GetMarketSkill :one
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.changelog, m.topics, m.stars, m.downloads, m.updated_at, m.raw, m.synced_at, m.review_status, m.review_note, m.reviewed_at, m.reviewed_by, m.icon_url, s.name AS source_name, s.base_url AS source_base_url
FROM market_skills m
JOIN skill_sources s ON s.id = m.source_id
WHERE m.source_id = $1 AND m.slug = $2
`

type GetMarketSkillParams struct {
	SourceID int64  `json:"source_id"`
	Slug     string `json:"slug"`
}

type GetMarketSkillRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	Changelog     pgtype.Text        `json:"changelog"`
	Topics        []string           `json:"topics"`
	Stars         int64              `json:"stars"`
	Downloads     int64              `json:"downloads"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	ReviewStatus  string             `json:"review_status"`
	ReviewNote    pgtype.Text        `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.Int8        `json:"reviewed_by"`
	IconUrl       pgtype.Text        `json:"icon_url"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

func (q *Queries) GetMarketSkill(ctx context.Context, arg GetMarketSkillParams) (GetMarketSkillRow, error) {
	row := q.db.QueryRow(ctx, getMarketSkill, arg.SourceID, arg.Slug)
	var i GetMarketSkillRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Version,
		&i.License,
		&i.Changelog,
		&i.Topics,
		&i.Stars,
		&i.Downloads,
		&i.UpdatedAt,
		&i.Raw,
		&i.SyncedAt,
		&i.ReviewStatus,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.IconUrl,
		&i.SourceName,
		&i.SourceBaseUrl,
	)
	return i, err
}

const getSkillSource = `-- name: GetSkillSource :one
SELECT id, name, base_url, status, last_synced_at, last_sync_error, created_at FROM skill_sources WHERE id = $1
`

func (q *Queries) GetSkillSource(ctx context.Context, id int64) (SkillSource, error) {
	row := q.db.QueryRow(ctx, getSkillSource, id)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillSourceByURL = `-- name: GetSkillSourceByURL :one
SELECT id, name, base_url, status, last_synced_at, last_sync_error, created_at FROM skill_sources WHERE base_url = $1
`

func (q *Queries) GetSkillSourceByURL(ctx context.Context, baseUrl string) (SkillSource, error) {
	row := q.db.QueryRow(ctx, getSkillSourceByURL, baseUrl)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const listMarketSkills = `-- name: ListMarketSkills :many
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.changelog, m.topics, m.stars, m.downloads, m.updated_at, m.raw, m.synced_at, m.review_status, m.review_note, m.reviewed_at, m.reviewed_by, m.icon_url, s.name AS source_name, s.base_url AS source_base_url
FROM market_skills m
JOIN skill_sources s ON s.id = m.source_id AND s.status = 1
WHERE m.review_status = 'approved'
ORDER BY m.updated_at DESC NULLS LAST
`

type ListMarketSkillsRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	Changelog     pgtype.Text        `json:"changelog"`
	Topics        []string           `json:"topics"`
	Stars         int64              `json:"stars"`
	Downloads     int64              `json:"downloads"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	ReviewStatus  string             `json:"review_status"`
	ReviewNote    pgtype.Text        `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.Int8        `json:"reviewed_by"`
	IconUrl       pgtype.Text        `json:"icon_url"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

// Skill 管理 → 市场视图：所有启用源里**审核通过**的缓存条目，附源信息供
// 卡片和详情回链。未过审的条目对普通用户根本不存在（审核台走
// ListMarketSkillsForReview）。
func (q *Queries) ListMarketSkills(ctx context.Context) ([]ListMarketSkillsRow, error) {
	rows, err := q.db.Query(ctx, listMarketSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketSkillsRow{}
	for rows.Next() {
		var i ListMarketSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.Version,
			&i.License,
			&i.Changelog,
			&i.Topics,
			&i.Stars,
			&i.Downloads,
			&i.UpdatedAt,
			&i.Raw,
			&i.SyncedAt,
			&i.ReviewStatus,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.IconUrl,
			&i.SourceName,
			&i.SourceBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketSkillsForReview = `-- name: ListMarketSkillsForReview :many
SELECT m.id, m.source_id, m.slug, m.name, m.summary, m.version, m.license, m.changelog, m.topics, m.stars, m.downloads, m.updated_at, m.raw, m.synced_at, m.review_status, m.review_note, m.reviewed_at, m.reviewed_by, m.icon_url, s.name AS source_name, s.base_url AS source_base_url
FROM market_skills m
JOIN skill_sources s ON s.id = m.source_id
WHERE ($1::text IS NULL OR m.review_status = $1::text)
  AND ($2::bigint IS NULL OR m.source_id = $2::bigint)
  AND ($3::text IS NULL
       OR m.slug ILIKE '%' || $3::text || '%'
       OR m.name ILIKE '%' || $3::text || '%'
       OR COALESCE(m.summary, '') ILIKE '%' || $3::text || '%')
ORDER BY m.review_status = 'pending' DESC, m.synced_at DESC, m.slug
LIMIT $5 OFFSET $4
`

type ListMarketSkillsForReviewParams struct {
	ReviewStatus pgtype.Text `json:"review_status"`
	SourceID     pgtype.Int8 `json:"source_id"`
	Search       pgtype.Text `json:"search"`
	Off          int32       `json:"off"`
	Lim          int32       `json:"lim"`
}

type ListMarketSkillsForReviewRow struct {
	ID            int64              `json:"id"`
	SourceID      int64              `json:"source_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Summary       pgtype.Text        `json:"summary"`
	Version       pgtype.Text        `json:"version"`
	License       pgtype.Text        `json:"license"`
	Changelog     pgtype.Text        `json:"changelog"`
	Topics        []string           `json:"topics"`
	Stars         int64              `json:"stars"`
	Downloads     int64              `json:"downloads"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Raw           []byte             `json:"raw"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	ReviewStatus  string             `json:"review_status"`
	ReviewNote    pgtype.Text        `json:"review_note"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.Int8        `json:"reviewed_by"`
	IconUrl       pgtype.Text        `json:"icon_url"`
	SourceName    string             `json:"source_name"`
	SourceBaseUrl string             `json:"source_base_url"`
}

// 审核台（系统配置 → Skill 源）：不筛源状态、不筛审核状态地列出同步条目，
// 让管理员看得到"同步进来了什么"。sqlc.narg 为空时该条件不生效。
//
// 分页在这里做而不是前端切片：一个公开源同步下来动辄成百上千条，全量返回
// 一次要拖着整张表过网络。搜索同理——只筛当前页等于没筛。
func (q *Queries) ListMarketSkillsForReview(ctx context.Context, arg ListMarketSkillsForReviewParams) ([]ListMarketSkillsForReviewRow, error) {
	rows, err := q.db.Query(ctx, listMarketSkillsForReview,
		arg.ReviewStatus,
		arg.SourceID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketSkillsForReviewRow{}
	for rows.Next() {
		var i ListMarketSkillsForReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.Version,
			&i.License,
			&i.Changelog,
			&i.Topics,
			&i.Stars,
			&i.Downloads,
			&i.UpdatedAt,
			&i.Raw,
			&i.SyncedAt,
			&i.ReviewStatus,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.IconUrl,
			&i.SourceName,
			&i.SourceBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillSources = `-- name: ListSkillSources :many
SELECT s.id, s.name, s.base_url, s.status, s.last_synced_at, s.last_sync_error, s.created_at, COUNT(m.id)::bigint AS skill_count
FROM skill_sources s
LEFT JOIN market_skills m ON m.source_id = s.id
GROUP BY s.id
ORDER BY s.created_at DESC
`

type ListSkillSourcesRow struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	BaseUrl       string             `json:"base_url"`
	Status        int16              `json:"status"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncError pgtype.Text        `json:"last_sync_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SkillCount    int64              `json:"skill_count"`
}

// 左联 market_skills 只为拿每个源的条目数，设置页直接展示。
func (q *Queries) ListSkillSources(ctx context.Context) ([]ListSkillSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSkillSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillSourcesRow{}
	for rows.Next() {
		var i ListSkillSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.CreatedAt,
			&i.SkillCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSkillSourceSyncError = `-- name: MarkSkillSourceSyncError :one
UPDATE skill_sources
SET last_synced_at = now(), last_sync_error = $2
WHERE id = $1
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at
`

type MarkSkillSourceSyncErrorParams struct {
	ID            int64       `json:"id"`
	LastSyncError pgtype.Text `json:"last_sync_error"`
}

func (q *Queries) MarkSkillSourceSyncError(ctx context.Context, arg MarkSkillSourceSyncErrorParams) (SkillSource, error) {
	row := q.db.QueryRow(ctx, markSkillSourceSyncError, arg.ID, arg.LastSyncError)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const markSkillSourceSynced = `-- name: MarkSkillSourceSynced :one
UPDATE skill_sources
SET last_synced_at = now(), last_sync_error = NULL
WHERE id = $1
RETURNING id, name, base_url, status, last_synced_at, last_sync_error, created_at
`

func (q *Queries) MarkSkillSourceSynced(ctx context.Context, id int64) (SkillSource, error) {
	row := q.db.QueryRow(ctx, markSkillSourceSynced, id)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
	)
	return i, err
}

const setMarketSkillReview = `-- name: SetMarketSkillReview :execrows
UPDATE market_skills
SET review_status = $3, review_note = $4, reviewed_at = now(), reviewed_by = $5
WHERE source_id = $1 AND slug = $2
`

type SetMarketSkillReviewParams struct {
	SourceID     int64       `json:"source_id"`
	Slug         string      `json:"slug"`
	ReviewStatus string      `json:"review_status"`
	ReviewNote   pgtype.Text `json:"review_note"`
	ReviewedBy   pgtype.Int8 `json:"reviewed_by"`
}

func (q *Queries) SetMarketSkillReview(ctx context.Context, arg SetMarketSkillReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMarketSkillReview,
		arg.SourceID,
		arg.Slug,
		arg.ReviewStatus,
		arg.ReviewNote,
		arg.ReviewedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMarketSkill = `-- name: UpsertMarketSkill :one
INSERT INTO market_skills (source_id, slug, name, summary, version, license, changelog, topics, stars, downloads, updated_at, raw, icon_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (source_id, slug) DO UPDATE SET
    name        = EXCLUDED.name,
    summary     = EXCLUDED.summary,
    version     = EXCLUDED.version,
    license     = EXCLUDED.license,
    changelog   = EXCLUDED.changelog,
    topics      = EXCLUDED.topics,
    stars       = EXCLUDED.stars,
    downloads   = EXCLUDED.downloads,
    icon_url    = EXCLUDED.icon_url,
    updated_at  = EXCLUDED.updated_at,
    raw         = EXCLUDED.raw,
    synced_at   = now()
RETURNING id, source_id, slug, name, summary, version, license, changelog, topics, stars, downloads, updated_at, raw, synced_at, review_status, review_note, reviewed_at, reviewed_by, icon_url
`

type UpsertMarketSkillParams struct {
	SourceID  int64              `json:"source_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Summary   pgtype.Text        `json:"summary"`
	Version   pgtype.Text        `json:"version"`
	License   pgtype.Text        `json:"license"`
	Changelog pgtype.Text        `json:"changelog"`
	Topics    []string           `json:"topics"`
	Stars     int64              `json:"stars"`
	Downloads int64              `json:"downloads"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Raw       []byte             `json:"raw"`
	IconUrl   pgtype.Text        `json:"icon_url"`
}

// 同步落库：同一 (source, slug) 覆盖刷新，上次同步后被上游下架的条目由
// Sync 清理（见 DeleteStaleMarketSkills）。
//
// review_status/review_note/reviewed_* 刻意不在 DO UPDATE 里：审核结论是
// 本地的判断，不是上游字段。每次同步都重置的话，管理员批准过的条目会在下
// 次同步后集体打回待审，等于审核白做。
func (q *Queries) UpsertMarketSkill(ctx context.Context, arg UpsertMarketSkillParams) (MarketSkill, error) {
	row := q.db.QueryRow(ctx, upsertMarketSkill,
		arg.SourceID,
		arg.Slug,
		arg.Name,
		arg.Summary,
		arg.Version,
		arg.License,
		arg.Changelog,
		arg.Topics,
		arg.Stars,
		arg.Downloads,
		arg.UpdatedAt,
		arg.Raw,
		arg.IconUrl,
	)
	var i MarketSkill
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Version,
		&i.License,
		&i.Changelog,
		&i.Topics,
		&i.Stars,
		&i.Downloads,
		&i.UpdatedAt,
		&i.Raw,
		&i.SyncedAt,
		&i.ReviewStatus,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.IconUrl,
	)
	return i, err
}
