// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package store

import (
	"context"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tools (owner_user_id, ref, version, config, display_meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type CreateToolParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
	Version     string `json:"version"`
	Config      []byte `json:"config"`
	DisplayMeta []byte `json:"display_meta"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.OwnerUserID,
		arg.Ref,
		arg.Version,
		arg.Config,
		arg.DisplayMeta,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const findAgentsReferencingToolRef = `-- name: FindAgentsReferencingToolRef :many
SELECT owner_user_id, agent_ref, version FROM agents
WHERE owner_user_id = $1
  AND (definition->'capabilities'->'tools') ? $2::text
`

type FindAgentsReferencingToolRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Column2     string `json:"column_2"`
}

type FindAgentsReferencingToolRefRow struct {
	OwnerUserID int64  `json:"owner_user_id"`
	AgentRef    string `json:"agent_ref"`
	Version     string `json:"version"`
}

func (q *Queries) FindAgentsReferencingToolRef(ctx context.Context, arg FindAgentsReferencingToolRefParams) ([]FindAgentsReferencingToolRefRow, error) {
	rows, err := q.db.Query(ctx, findAgentsReferencingToolRef, arg.OwnerUserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAgentsReferencingToolRefRow{}
	for rows.Next() {
		var i FindAgentsReferencingToolRefRow
		if err := rows.Scan(&i.OwnerUserID, &i.AgentRef, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolByIDForOwner = `-- name: GetToolByIDForOwner :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM tools WHERE id = $1 AND owner_user_id = $2
`

type GetToolByIDForOwnerParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) GetToolByIDForOwner(ctx context.Context, arg GetToolByIDForOwnerParams) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByIDForOwner, arg.ID, arg.OwnerUserID)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getToolLatestByRef = `-- name: GetToolLatestByRef :one
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM tools WHERE owner_user_id = $1 AND ref = $2 ORDER BY created_at DESC LIMIT 1
`

type GetToolLatestByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
}

// Used by the run engine (spec-10/11) to build a real tool.Tool from the
// resource's config — capabilities.tools[] refs aren't version-pinned, so
// this is always "whatever's currently live", same as the status lookup.
func (q *Queries) GetToolLatestByRef(ctx context.Context, arg GetToolLatestByRefParams) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolLatestByRef, arg.OwnerUserID, arg.Ref)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}

const getToolLatestStatusByRef = `-- name: GetToolLatestStatusByRef :one
SELECT status FROM tools WHERE owner_user_id = $1 AND ref = $2 ORDER BY created_at DESC LIMIT 1
`

type GetToolLatestStatusByRefParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	Ref         string `json:"ref"`
}

func (q *Queries) GetToolLatestStatusByRef(ctx context.Context, arg GetToolLatestStatusByRefParams) (int16, error) {
	row := q.db.QueryRow(ctx, getToolLatestStatusByRef, arg.OwnerUserID, arg.Ref)
	var status int16
	err := row.Scan(&status)
	return status, err
}

const listToolsForOwnerPage = `-- name: ListToolsForOwnerPage :many
SELECT id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at FROM tools WHERE owner_user_id = $1 AND id > $2 ORDER BY id ASC LIMIT $3
`

type ListToolsForOwnerPageParams struct {
	OwnerUserID int64 `json:"owner_user_id"`
	ID          int64 `json:"id"`
	Limit       int32 `json:"limit"`
}

func (q *Queries) ListToolsForOwnerPage(ctx context.Context, arg ListToolsForOwnerPageParams) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listToolsForOwnerPage, arg.OwnerUserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Ref,
			&i.Version,
			&i.Config,
			&i.DisplayMeta,
			&i.Status,
			&i.Immutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markToolImmutable = `-- name: MarkToolImmutable :exec
UPDATE tools SET immutable = true WHERE id = $1
`

func (q *Queries) MarkToolImmutable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markToolImmutable, id)
	return err
}

const updateTool = `-- name: UpdateTool :one
UPDATE tools SET display_meta = $3, config = $4, status = $5
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, ref, version, config, display_meta, status, immutable, created_at
`

type UpdateToolParams struct {
	ID          int64  `json:"id"`
	OwnerUserID int64  `json:"owner_user_id"`
	DisplayMeta []byte `json:"display_meta"`
	Config      []byte `json:"config"`
	Status      int16  `json:"status"`
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateTool,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayMeta,
		arg.Config,
		arg.Status,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ref,
		&i.Version,
		&i.Config,
		&i.DisplayMeta,
		&i.Status,
		&i.Immutable,
		&i.CreatedAt,
	)
	return i, err
}
